### PR TITLE
Cache UCollator objects for String.prototype.localeCompare

### LINKED ISSUE #2352: Intl should cache and re-use various formatters
[InitializeDateTimeFormat](https://github.com/Microsoft/ChakraCore/blob/master/lib/Runtime/Library/InJavascript/Intl.js#L1113) method takes an empty object dateTimeFormat and sets various properties on it
based on `options` and `localeList`. Inside `platform.createDateTime()`, it caches an instance of `dateTimeFormatter` as `hiddenObject` property on `dateTimeFormat` object.
If InitializeDateTimeFormat() is called from ctor of Intl.DateTimeFormat, then various methods like `Intl.DateTimeFormat.prototype.format()` called on the instance will reuse the `dateTimeFormatter` and other other cached properties on `dateTimeFormat`. 

However InitializeDateTimeFormat() is also called from non Intl methods like `Date.prototype.toLocale*String()`, in which case a new `dateTimeFormatter` is created every time and is thrown away. Below code can be written better, but is a good example to demonstrate the creation of `dateTimeFormatter` every time `toLocaleString` is called.

```js
  var utcDate = new Date(Date.UTC(96, 11, 1, 0, 0, 0));
  for(var i = 0;i < 10000; i++){
    print(typeof utcDate);
    print(utcDate.toLocaleString()); // dateTimeFormatter is created every time.
  }
```

Ideal solution would be to cache dateTimeFormat based on `localList` and `options` parameters, so we don't have to
1. Initialize `dateTimeFormat` object
2. Create dateTimeformatters

Above comment holds true for [InitializeNumberFormat()](https://github.com/Microsoft/ChakraCore/blob/master/lib/Runtime/Library/InJavascript/Intl.js#L661) and [InitializeCollator()](https://github.com/Microsoft/ChakraCore/blob/master/lib/Runtime/Library/InJavascript/Intl.js#L432) methods and APIs that consume these methods.

### LINKED ISSUE #4921: Intl-ICU: String.prototype.localeCompare(other) is 4x slower than with WinGlob
The simplest of microbenchmarks for proof:

```js
const start = Date.now();
let result = 0;
for (var i = 0; i < 1e5; ++i) {
    result -= "a".localeCompare("A");
}
const end = Date.now();

print(`Elapsed: ${end - start}, result: ${result}`);
```

This takes ~22ms in WinGlob and ~100ms in ICU on my machine using jshost.exe x64_test_pogo. 

For a real world case, this 4x regression is visible in a 70% regression in JetStream's CDjs benchmark, which uses localeCompare for comparing nodes in a particularly hot red-black tree.

### PR DESCRIPTION
**Pull request by jackhorton**
Fixes #4921 
Fixes #2352 (NumberFormat and DateTimeFormat already cache their underlying objects)

With this change, my local build of x64_test was competitive with a WinGlob baseline x64_test_pogo build (approximately 28ms to 21ms)

### CODE REVIEW

File: lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp [hunk 1]
```diff
@@ -1665,118 +1697,134 @@ namespace Js
...
-        char localeID[ULOC_FULLNAME_CAPACITY] = { 0 };
-        int32_t length = 0;
-        if (langtag == nullptr)
+        JavascriptString *left = JavascriptString::UnsafeFromVar(args[1]);
+        JavascriptString *right = JavascriptString::UnsafeFromVar(args[2]);
+        DynamicObject *state = DynamicObject::UnsafeFromVar(args[3]);
+
+        // Below, we lazy-initialize the backing UCollator on the first call to localeCompare
+        // On subsequent calls, the UCollator will be cached in state.hiddenObject
+        // TODO(jahorto): Make these property IDs sane, so that hiddenObject doesn't have different meanings in different contexts
```
Comment (sethbrenith) [inline lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp]: Agreed, hiddenObject is a super generic term. Can we just call it collator or something?

File: lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp [hunk 2]
```diff
@@ -1665,118 +1697,134 @@ namespace Js
...
+        Var hiddenObject = nullptr;
+        FinalizableUCollator *coll = nullptr;
+        UErrorCode status = U_ZERO_ERROR;
+        if (state->GetInternalProperty(state, Js::InternalPropertyIds::HiddenObject, &hiddenObject, nullptr, scriptContext))
         {
-            length = uloc_getName(nullptr, localeID, _countof(localeID), &error);
+            coll = reinterpret_cast<FinalizableUCollator *>(hiddenObject);
```
Comment (sethbrenith) [inline lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp]: This feels to me like a case where we might benefit from verifying that we actually have a FinalizableUCollator before casting (and crash the program otherwise). Looks like you would have to use DEFINE_VTABLE_CTOR_NOBASE in FinalizableICUObject if you want to check the vtable. On the other hand, I can't think of any concrete way to attack this: somebody would need to either call directly into this method or poison the value of localeCompareStateCache, both of which _should_ be impossible.

File: lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp [hunk 3]
```diff
@@ -350,6 +350,38 @@ namespace Js
...
+
+        return T::UnsafeFromVar(propertyValue);
+    }
+
+    static int AssertIntegerProperty(DynamicObject *state, PropertyIds propertyId)
+    {
+        Var propertyValue = nullptr;
+        JavascriptOperators::GetProperty(state, propertyId, &propertyValue, state->GetScriptContext());
+
+        AssertOrFailFast(propertyValue && TaggedInt::Is(propertyValue));
```
Comment (sethbrenith) [inline lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp]: >TaggedInt [](start = 42, length = 9)

I could be mistaken, but I think that TaggedInt is an optimization detail that we shouldn't rely on at this level. It is possible that earlier code for some reason decided to represent this int as a tagged float or as a heap-allocated JavascriptNumber, and we shouldn't fail if it chose to do so.

Comment (sethbrenith) [reply lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp]: I guess we control the `toEnum` function that generates these though, so if it works then it wouldn't break due to differences in user code.

---
In reply to: [178879992](https://github.com/Microsoft/ChakraCore/pull/4926#discussion_r178879992) [](ancestors = 178879992)

Comment (jackhorton) [reply lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp]: The previous version of the code here used it. I suppose that if I am going to abstract this into `AssertIntegerProperty`, it wouldn't hurt to check both TaggedInt and JavascriptNumber. I do think that allowing JavascriptNumberObjects would be too permissive though, Intl.js really shouldn't be working with Number objects.

File: lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp (hunk 2 above)
Comment (jackhorton) [reply lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp]: Yeah... the whole way these stashed objects work is super awkward and probably not particularly safe. With that being said, this is how the other caches work... Any work done here should be done to the others as well, and is probably out of scope for this PR. I can make an issue for it if you want.

**Comment by jackhorton** [comment]
@dotnet-bot 
test OSX _no_git_shared_osx_osx_test please
test OSX static_osx_osx_debug please
test OSX static_osx_osx_release please

**Comment by jackhorton** [comment]
@dotnet-bot test OSX _no_git_shared_osx_osx_test please
test OSX static_osx_osx_debug please
test OSX static_osx_osx_release please

**Comment by jackhorton** [comment]
@dotnet-bot  test OSX _no_jit_shared_osx_osx_test please

File: lib/Runtime/Library/InJavascript/Intl.js [hunk 4]
```diff
@@ -954,18 +955,23 @@
...
-                thisStr,
-                thatStr,
-                stateObject.locale,
-                stateObject.sensitivityEnum,
-                stateObject.ignorePunctuation,
-                stateObject.numeric,
-                stateObject.caseFirstEnum
-            ));
+
+            // Performance optimization to cache the state object and UCollator when the default arguments are provided
```
Comment (dilijev) [inline lib/Runtime/Library/InJavascript/Intl.js]: >default arguments [](start = 89, length = 17)

@jackhorton I thought the other caches were already more sophisticated than this -- maybe I'm just remembering our discussion on caching "nice-to-have's"

**Comment by dilijev** [comment]
FWIW LGTM

File: lib/Runtime/Library/InJavascript/Intl.js (hunk 4 above)
Comment (jackhorton) [reply lib/Runtime/Library/InJavascript/Intl.js]: This is caching the Intl.Collator object for `"a".localeCompare("b")`. The PR also caches the UCollator object for each Intl.Collator. This brings Collator in line with how NumberFormat and DateTimeFormat work (the actual implementation is more like DateTimeFormat, where we lazy-initialize the underlying ICU object on the first call to `compare()`).

Comment (dilijev) [reply lib/Runtime/Library/InJavascript/Intl.js]: Gotcha -- this block is more about the lazy init and caching of the underlying object? But in addition don't we have a multiple-entry-deep cache for previously constructed Intl objects that works for more than the default params in general? (I guess that wasn't touched by this PR.)

Comment (jackhorton) [reply lib/Runtime/Library/InJavascript/Intl.js]: We have that DateToLocaleStringCache or something since there are multiple toLocaleStrings and they all want the same caching behavior, this block accomplishes the same thing. The lazy-initialization and caching of the UCollator happens in IntlBlahBlahBlah.cpp

**Comment by jefgen** [comment]
Just curious, but does Chakra have any way to be notified and/or any hooks to say "Hey the OS Locale changed" at all?
I'm just wondering how you might possibly invalidate the various cached state if the user changed their default locale.
Or perhaps this is a non-concern and the answer is "reload the webpage"?.

**Comment by jefgen** [comment]
Otherwise, similar to Doug, LGTM (though I'm not super familiar with the Chakra codebase).

**Comment by jackhorton** [comment]
I believe we investigated this and other engines don't pick this up without a restart of the _browser_. That was at least the case with time zones.
