### PR TITLE
fixes #5549 implement defineOwnProperty for typedarray object

### LINKED ISSUE #5549: Chakra should returns false if key is a numeric index and desc.writable is false
Hi everyone,
according to [9.4.5.3](https://www.ecma-international.org/ecma-262/8.0/index.html#sec-integer-indexed-exotic-objects-defineownproperty-p-desc) it is possible define a property key if it is a numeric index, Chakra throws a TypeError instead.

OS: Ubuntu 16.04
version: 1.10.1

Steps to reproduce:
```
var sample = new Float64Array(2)
print(Reflect.defineProperty(sample, "0", {
  value: 42,
  configurable: false,
  enumerable: true,
  writable: false
}))
```
Actual results:
TypeError: Cannot redefine non-configurable property '0'

Expected results:
false

V8, SpiderMonkey and JSC works as expected.

cinfuzz

### PR DESCRIPTION
**Pull request by duongnhn**
- ES2017 implement defineOwnProperty for each object types: 
https://www.ecma-international.org/ecma-262/8.0/index.html#sec-definepropertyorthrow

### CODE REVIEW

File: lib/Runtime/Library/JavascriptObject.cpp [hunk 1]
```diff
@@ -2128,11 +2128,19 @@ BOOL JavascriptObject::DefineOwnPropertyHelper(RecyclableObject* obj, PropertyId
     // so there is no benefit in using ES5 DefineOwnPropertyDescriptor for it, use old implementation.
     if (TypeIds_HostDispatch != obj->GetTypeId())
     {
+        // for Array Exotic Objects
         if (DynamicObject::IsAnyArray(obj))
         {
             returnValue = JavascriptOperators::DefineOwnPropertyForArray(
                 JavascriptArray::FromAnyArray(obj), propId, descriptor, throwOnError, scriptContext);
         }
+        // for Integer Indexed Exotic Objects
```
Comment (duongnhn) [inline lib/Runtime/Library/JavascriptObject.cpp]: call DefineOwnProperty for typedarray object

File: lib/Runtime/Language/JavascriptOperators.cpp [hunk 2]
```diff
@@ -9043,6 +9043,74 @@ using namespace Js;
         return DefineOwnPropertyDescriptor(arr, propId, descriptor, throwOnError, scriptContext);
     }
 
+    // ES2017: 9.4.5.3
+    BOOL JavascriptOperators::DefineOwnPropertyForTypedArray(TypedArrayBase* typedArray, PropertyId propId, const PropertyDescriptor& descriptor, bool throwOnError, ScriptContext* scriptContext)
```
Comment (duongnhn) [inline lib/Runtime/Language/JavascriptOperators.cpp]: implement DefineOwnProperty according to ES2017: 9.4.5.3

**Comment by sethbrenith** [comment]
I think you need a `#` character in the description for GitHub to automatically close the issue. More info: https://help.github.com/articles/closing-issues-using-keywords/ https://help.github.com/articles/autolinked-references-and-urls/

File: test/typedarray/reflect_defineProperty.js [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+var result = null;
+
+// false: writable false
+result = Reflect.defineProperty(sample, "0", {
+    value: 42,
+    configurable: false,
+    enumerable: true,
+    writable: false,
+});
+console.log(sample[0]);
```
Comment (sethbrenith) [inline test/typedarray/reflect_defineProperty.js]: We have lots of existing tests that use baseline files, but I believe we're trying to prefer assertion-style tests where possible, because it's easier to read when the code and the expected output is together in one file. Take a look at test/typedarray/delete.js as an example (there are many examples, I just chose one at random). It loads `UnitTestFramework.js` at the top, which provides the `assert` object used in the test cases. It invokes the tests with `testRunner.runTests`, and doesn't provide a baseline file.

**Comment by duongnhn** [comment]
good catch, will do!

---
In reply to: [413228389](https://github.com/Microsoft/ChakraCore/pull/5597#issuecomment-413228389) [](ancestors = 413228389)

File: lib/Runtime/Language/JavascriptOperators.cpp [hunk 4]
```diff
@@ -9043,6 +9043,74 @@ using namespace Js;
         return DefineOwnPropertyDescriptor(arr, propId, descriptor, throwOnError, scriptContext);
     }
 
+    // ES2017: 9.4.5.3
```
Comment (sethbrenith) [inline lib/Runtime/Language/JavascriptOperators.cpp]: Section numbers can change, but links aren't supposed to, so could you please reference the link like this? [https://tc39.github.io/ecma262/#sec-integer-indexed-exotic-objects-defineownproperty-p-desc](https://tc39.github.io/ecma262/#sec-integer-indexed-exotic-objects-defineownproperty-p-desc)

**Comment by sethbrenith** [comment]
> BOOL JavascriptObject::DefineOwnPropertyHelper(RecyclableObject* obj, PropertyId propId, const PropertyDescriptor& descriptor, ScriptContext* scriptContext, bool throwOnError /* = true*/)

@rajatd does the jitted code call into this helper or do we need additional changes elsewhere?

---
Refers to: lib/Runtime/Library/JavascriptObject.cpp:2119 in 394cbd1. [](commit_id = 394cbd17397bd408e4fd2573c4049791f629c03a, deletion_comment = False)

**Comment by rajatd** [comment]
There doesn't seem to be any special handling (i.e., inlining) for Reflect.defineProperty in the JIT. It should just be getting lowered as a CallI to `JavascriptReflect::EntryDefineProperty`

**Comment by duongnhn** [comment]
:thumbsup: 

---
In reply to: [413285900](https://github.com/Microsoft/ChakraCore/pull/5597#issuecomment-413285900) [](ancestors = 413285900)
