### PR TITLE
Fixes #804 Json parsing errors mention JSON.parse in errors

### LINKED ISSUE #804: JSON.parse("") gives very ambigious "Syntax Error".
```javascript
JSON.parse("")
```

```
$ ch.exe jsonParseEmpty.js
SyntaxError: Syntax error
   at Global code (d:\personal\chakracore\build\vcbuild\bin\x64_debug\test.js:1:1)
```

'Syntax Error' is very ambiguous error. It could mean a lot of things. When its part of a large callstack, I would think its a javascript syntax error somewhere in my js files. The callstack doesn't even mention JSON.parse.

Chrome gives
```
VM145:1 Uncaught SyntaxError: Unexpected end of JSON input(…) 
```

Ideal error should mention something like "JSON.parse Syntax error: Empty string" or "JSON.parse Syntax Error: unexpected end of json input."

### PR DESCRIPTION
**Pull request by nojvek**
I added JSON.parse specific errors. It still doesn't feel very clean as there is no column info. Would this be relatively easy to add?

### CODE REVIEW

**Comment by ianwjhalliday** [comment]
Thanks @nojvek, these new error messages are definitely more helpful.

The error stack will have the line column information for the source of the throw, which will be where the JSON.parse call occurred, so we do have that already.

Could also be useful to have character offset (or line/column?) information for the source of the error in the JSON string passed to parse.  I don't know if that would require much additional work on in the JSON parser or not.  Certainly this can be raised as a new separate `Suggestion` issue if you think it is a good idea.

@abchatra any concerns over adding new error messages?

**Comment by nojvek** [comment]
Right now there seems to be a LSC_ERROR_MSG(..) macro definition of a
syntax error.

How do I throw a syntax error with a dynamically created string ?

**Comment by ianwjhalliday** [comment]
Look at `rterrors.h` where we have errors with two forms of their message string.  The first form has a %s parameter that will be replaced by the given string to the `JavascriptError::Throw*` methods.

I believe you should be able to move the errors to `rterrors.h` and still use them for `ThrowSyntaxError` without any issues.

**Comment by abchatra** [comment]
> @abchatra any concerns over adding new error messages?

I am happy to see improvement in the error messages.

**Comment by nojvek** [comment]
Thanks abchatra for the help today. I have made the fixes to show the position just like v8 does for JSON.parse. wdyt?

**Comment by ianwjhalliday** [comment]
Looks great!  Thanks @nojvek, I'll get this merged.

**Comment by ianwjhalliday** [comment]
@nojvek turns out we have some JSON tests that do not run in jenkins currently because they depend on timezone.

You will need to manually run these two tests, `test/JSON/jx2.js` and `test/es5/jx2.js`, and update their baselines to match your change before we can merge this in.  These two tests happen to run with no ch.exe command line switches, but in general when running tests manually you'd want to confirm you are using the right switches by examining the `test/.../rlexe.xml` file to see if it specifies switches and if so what they are.  Also this will show you what the baseline file is named, sometimes it doesn't match the source file.

I also just noticed that your new test `syntaxerror.js` is not added to `test/JSON/rlexe.xml`.  Please add it there so that it runs in the test runner.

**Comment by ianwjhalliday** [comment]
Note the json tests that don't run in jenkins because of their timezone dependency is an understood issue that we have not fixed yet.  It depends on PST timezone.

File: lib/Runtime/Library/JSONParser.cpp [hunk 1]
```diff
@@ -404,12 +404,13 @@ namespace JSON
...
                 // check  and consume the ending '}"
-                CheckCurrentToken(tkRCurly, ERRnoRcurly);
+                CheckCurrentToken(tkRCurly, JSERR_JsonNoRcurly);
                 return object;
             }
 
         default:
-            Js::JavascriptError::ThrowSyntaxError(scriptContext, ERRsyntax);
+            m_scanner.ThrowSyntaxError(JSERR_JsonSyntax);
+            return NULL;
```
Comment (abchatra) [inline lib/Runtime/Library/JSONParser.cpp]: Not required. This statement won't be reached.

File: lib/Runtime/Library/JSONScanner.h [hunk 2]
```diff
@@ -20,9 +20,16 @@ namespace JSON
...
-        char16* GetCurrentString(){return currentString;}
-        uint GetCurrentStringLen(){return currentIndex;}
+        char16* GetCurrentString() { return currentString; } 
+        uint GetCurrentStringLen() { return currentIndex; }
+        uint GetScanPos() { return uint(currentChar - inputText); }
 
+        void ThrowSyntaxError(int wErr)
+        {
+            char16 scanPos[16];
+            ::_itow_s(GetScanPos(), scanPos, sizeof(scanPos) / sizeof(char16), 10);
```
Comment (abchatra) [inline lib/Runtime/Library/JSONScanner.h]: Use _countof(scanPos)

File: lib/Runtime/Library/JSONScanner.h [hunk 3]
```diff
@@ -20,9 +20,16 @@ namespace JSON
             ::Js::ScriptContext* sc, const char16* current, ArenaAllocator* allocator);
 
         void Finalizer();
-        char16* GetCurrentString(){return currentString;}
-        uint GetCurrentStringLen(){return currentIndex;}
+        char16* GetCurrentString() { return currentString; } 
+        uint GetCurrentStringLen() { return currentIndex; }
+        uint GetScanPos() { return uint(currentChar - inputText); }
```
Comment (abchatra) [inline lib/Runtime/Library/JSONScanner.h]: Nit: Rename to GetScanPosition?

File: lib/Runtime/Library/JSONScanner.h [hunk 4]
```diff
@@ -20,9 +20,16 @@ namespace JSON
...
 
+        void ThrowSyntaxError(int wErr)
```
Comment (abchatra) [inline lib/Runtime/Library/JSONScanner.h]: This should be long right?

File: lib/Runtime/Library/JSONParser.cpp (hunk 1 above)
Comment (nojvek) [inline lib/Runtime/Library/JSONParser.cpp]: Without this C++ won't compile.

>e:\personal\chakracore\lib\runtime\library\jsonparser.cpp(415): warning C4715: 'JSON::JSONParser::ParseObject': not all control paths return a value

File: lib/Runtime/Library/JSONScanner.h (hunk 4 above)
Comment (nojvek) [inline lib/Runtime/Library/JSONScanner.h]: the function takes a int32 hcode

err_method(ScriptContext* scriptContext, int32 hCode, PCWSTR varName = nullptr)

File: lib/Runtime/Library/JSONParser.cpp (hunk 1 above)
Comment (ianwjhalliday) [inline lib/Runtime/Library/JSONParser.cpp]: That is because `JSONScanner::ThrowSyntaxError` is not marked with `__declspec(noreturn)`.

Probably reasonable to change the definition of `JSONScanner::ThrowSyntaxError` to:
```c++
void __declspec(noreturn) ThrowSyntaxError(int wErr)
```

Comment (nojvek) [inline lib/Runtime/Library/JSONParser.cpp]: done.

File: lib/Runtime/Library/JSONScanner.h (hunk 2 above)
Comment (nojvek) [inline lib/Runtime/Library/JSONScanner.h]: done.

File: lib/Runtime/Library/JSONScanner.h (hunk 3 above)
Comment (nojvek) [inline lib/Runtime/Library/JSONScanner.h]: done.

**Comment by nojvek** [comment]
Ensured tests pass in  runtests.cmd -x64 -debug and added syntaxError.js to rl.xml

**Comment by ianwjhalliday** [comment]
@nojvek you forgot to update the baseline for `test\es5\jx2.js` as well.

**Comment by nojvek** [comment]
Oh forgot that. I updated Json/jx2.js

**Comment by ianwjhalliday** [comment]
@nojvek when you get a chance please update `test\es5\jx3.baseline`.  I've updated internal test baselines so once you've done that I believe we'll be all ready to merge your change.

**Comment by nojvek** [comment]
Done. Ran all 1655 tests and confirmed they passed.

Not sure why baseline for jx2.js was called jx3.js. I've renamed to
jx2.baseline.

Soz for delay

**Comment by ianwjhalliday** [comment]
Awesome, thanks for the rename.  I don't know why it was different either.  Probably some historical reason that didn't get cleaned up nicely.

**Comment by nojvek** [comment]
Would be great to see this go in today. Let me know if you need anything else from my side. Thanks

**Comment by ianwjhalliday** [comment]
@nojvek we're all good, merged!  Thanks for improving these error messages

**Comment by nojvek** [comment]
That's awesome. Thanks Ian.

**Comment by abchatra** [comment]
Thank you @nojvek

**Comment by dilijev** [comment]
Note that we're tracking the timezone-sensitive tests issue in #319
