### PR TITLE
Fix timeZone and timeZoneName for Intl-ICU

### LINKED ISSUE #4694: Intl.DateTimeFormat with timeZone and timeZoneName options crashes
Found this while investigating #3096. As a result of that bug, we don't have any tests for timeZone or timeZoneName in ChakraCore, and so we never noticed that the implementation is broken with ICU.

### PR DESCRIPTION
**Pull request by jackhorton**
Previously, using any timeZone aside from simple, already-all-uppercase ones like GMT or UTC would fail  ("AMERICA/LOS_ANGELES" isn't a valid timezone, and also we were passing undefined to raiseOptionValueOutOfRange_3 which was triggering an Assert).

Fixes #4694

### CODE REVIEW

File: lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp [hunk 1]
```diff
@@ -2192,17 +2192,40 @@ namespace Js
             return scriptContext->GetLibrary()->GetUndefined();
         }
 #else
-        int required = ValidateAndCanonicalizeTimeZone(tz->GetSz());
-        if (required > 0)
+        UErrorCode status = U_ZERO_ERROR;
+
+        // TODO(jahorto): Is this the list of timeZones that we want? How is this different from
+        // the other two enum values or ucal_openTimeZones?
+        UEnumeration *available = ucal_openTimeZoneIDEnumeration(UCAL_ZONE_TYPE_ANY, nullptr, nullptr, &status);
```
Comment (sethbrenith) [inline lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp]: >&status [](start = 103, length = 7)

Do we need to assert this status is valid before continuing to the following line that overwrites status?

File: lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp [hunk 2]
```diff
@@ -2192,17 +2192,40 @@ namespace Js
...
+                ICU_ASSERT(status, true);
+                size_t len = wcslen(reinterpret_cast<const char16 *>(match));
+                AssertMsg(len < MaxCharCount, "Returned canonicalized timezone is far too long");
+                matchLen = (charcount_t)len;
+                break;
+            }
         }
-        else
+
+        uenum_close(available);
```
Comment (sethbrenith) [inline lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp]: >uenum_close [](start = 8, length = 11)

Do we have a strict guarantee that all of the above code can't throw? Does UEnumeration already do this for us in its destructor? If the answers are both no, then we need a wrapper class to make sure we tear down correctly.

File: lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp [hunk 3]
```diff
@@ -2192,17 +2192,40 @@ namespace Js
...
+            int curLen = -1;
+            const UChar *cur = uenum_unext(available, &curLen, &status);
+            ICU_ASSERT(status, curLen > 0);
+            if (_wcsicmp(reinterpret_cast<const char16 *>(cur), tz->GetSz()) == 0)
+            {
+                ucal_getCanonicalTimeZoneID(cur, curLen, match, _countof(match), nullptr, &status);
+                ICU_ASSERT(status, true);
+                size_t len = wcslen(reinterpret_cast<const char16 *>(match));
+                AssertMsg(len < MaxCharCount, "Returned canonicalized timezone is far too long");
+                matchLen = (charcount_t)len;
```
Comment (sethbrenith) [inline lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp]: >(charcount_t) [](start = 27, length = 13)

static_cast

File: lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp (hunk 2 above)
Comment (jackhorton) [reply lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp]: UEnumeration is a `void *` that is actually an `icu::StringEnumeration`, and `uenum_close()` just calls `delete stringEnum` in (almost?) all cases. So, it cant throw per destructor rules about throwing.

File: lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp (hunk 1 above)
Comment (jackhorton) [reply lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp]: All ICU APIs ignore calls if the passed in status is already in a failure state, so if you don't care about intermediate failure states, you could actually not check for U_FAILURE(status) until the caller is otherwise about to return something. So, it was easier to me to assert the status once since the uenum_count operation won't have any negative side effects if the enum failed to open.

I can probably add that as a comment, though.

Comment (sethbrenith) [reply lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp]: If that's standard with other ICU methods, then I don't think it needs a comment here. I wasn't familiar with the in-out style status pointer, but it's a neat idea.

---
In reply to: [169468076](https://github.com/Microsoft/ChakraCore/pull/4703#discussion_r169468076) [](ancestors = 169468076)

File: lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp (hunk 2 above)
Comment (sethbrenith) [reply lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp]: My question wasn't about uenum_close throwing, it was about earlier exceptions making us fail to close. Sorry I was unclear.

---
In reply to: [169467337](https://github.com/Microsoft/ChakraCore/pull/4703#discussion_r169467337) [](ancestors = 169467337)
