### PR TITLE
Array.copyWithin should throw when invoked on TypedArray with missing slots

### LINKED ISSUE #4356: Array.prototype.copyWithin should throw when trying to delete a non-configurable property
I wrote the following test case (which could go in ES6ArrayApi.js), and `copyWithin` fails to throw where expected.

```javascript
    {
        name: "Array.copyWithin() should respect overridden `length` property on TypedArray instance",
        body: function () {
            var x = new Int32Array([1,2,3]);
            Object.defineProperty(x, "length", { value: 4 });
            assert.throws(function() { Array.prototype.copyWithin.call(x, 1, 2); }, TypeError,
                "We should get a TypeError when trying to delete an item of TypedArray");
            assert.areEqual("1,3,3,", Array.prototype.join.call(x, ","),
                "We should have already modified previous items before throwing");

            x[1] = 2;
            Object.setPrototypeOf(x, { "3": 5 });
            assert.throws(function() { Array.prototype.copyWithin.call(x, 1, 2); }, TypeError,
                "We should still get a TypeError because [[HasProperty]] on an Integer Indexed Exotic Object returns false for out-of-bounds values");
            assert.areEqual("1,3,3,", Array.prototype.join.call(x, ","),
                "We should not read prototype properties of TypedArray by index");

            x[2] = 4;
            Int32Array.prototype.copyWithin.call(x, 0, 1);
            assert.areEqual("3,4,4,", Array.prototype.join.call(x, ","),
                "TypedArray copyWithin ignores overridden length property and uses internal [[ArrayLength]]");
        }
    },
```

It seems that the issue stems from the fact that several places in `JavascriptArray::CopyWithinHelper` call `OP_DeleteElementI` or `DeleteItem` but don't wrap the call in a `ThrowTypeErrorOnFailure`.

This bug is possible because correct usage of `PropertyOperation_ThrowOnDeleteIfNotConfig` is super confusing: it looks like it should make `DeleteItem` throw, but it doesn't. Either we should remove that enum value or we should update `DeleteItem` and friends respect it.

### PR DESCRIPTION
**Pull request by irinayat-MS**
Fixes #4356 

  | delete   obj.foo   non-configurable | delete   ta.foo   configurable | delete   ta.foo   doesn't   exist | delete   ta.foo    non-configurable | delete   ta[index] | Array.copyWithin      with   delete
-- | -- | -- | -- | -- | -- | --
strict | throw | delete, return true | nop, return true | throw | throw | throw
non-strict | nop, return false | delete, return true | nop, return true | nop, return false | nop, return false | throw

### CODE REVIEW

File: lib/Runtime/Language/JavascriptOperators.cpp [hunk 1]
```diff
@@ -4818,7 +4818,8 @@ namespace Js
 #endif
         }
 
-        if (result == FALSE && (propertyOperationFlags & PropertyOperation_StrictMode))
+        if (result == FALSE && 
+            (propertyOperationFlags & (PropertyOperation_StrictMode | PropertyOperation_ThrowOnDeleteIfNotConfig)))
```
Comment (MSLaguana) [inline lib/Runtime/Language/JavascriptOperators.cpp]: This looks reasonable to me, but it does make me wonder whether there's some other scenario somewhere that might directly call into `someArray->DeleteItem` and expect that it throws when appropriate; a quick look around showed code like this: https://github.com/Microsoft/ChakraCore/blob/master/lib/Runtime/Library/JavascriptArray.cpp#L5649 which I think converts the `false` return into throwing explicitly, but seems to expect the typed array will do something with the flag it is given rather than completely ignoring it. Do you know if there are any other potential scenarios?

Comment (boingoing) [reply lib/Runtime/Language/JavascriptOperators.cpp]: +1

Not sure this is the right place for this check. When `result == FALSE`, it might be for another reason other than not `configurable`.

**Comment by boingoing** [comment]
@dotnet-bot test Pre-Merge signing tool please

**Comment by MSLaguana** [comment]
That's not part of the dotnet CI; I think a push will be required to trigger that.

File: lib/Runtime/Language/JavascriptOperators.cpp (hunk 1 above)
Comment (digitalinfinity) [reply lib/Runtime/Language/JavascriptOperators.cpp]: `result` looks like it always is returned by `JavascriptOperators::DeleteProperty`. What other reason could it return false for?

File: lib/Runtime/Library/JavascriptArray.cpp [hunk 2]
```diff
@@ -9131,7 +9131,8 @@ namespace Js
                 }
                 else
                 {
-                    JS_REENTRANT(jsReentLock, obj->DeleteItem(toIndex, PropertyOperation_ThrowOnDeleteIfNotConfig));
+                    JavascriptOperators::OP_DeleteElementI(obj, JavascriptNumber::ToVar(toIndex, scriptContext), scriptContext, PropertyOperation_ThrowOnDeleteIfNotConfig);
```
Comment (digitalinfinity) [inline lib/Runtime/Library/JavascriptArray.cpp]: Don't we still need to wrap this in JS_REENTRANT?

Comment (sethbrenith) [reply lib/Runtime/Library/JavascriptArray.cpp]: For more context, we explicitly mark any lines in here that are allowed to call back into script (it would be a bug if any line without such a marking could call script). This pattern is useful because we can assume that certain things don't change as long as we haven't called into script (for instance, an instance of JavascriptArray hasn't magically transformed itself into an instance of ES5Array). The object here could be a Proxy with a deleteProperty handler, in which case this deletion operation would call script.

---
In reply to: [173333445](https://github.com/Microsoft/ChakraCore/pull/4790#discussion_r173333445) [](ancestors = 173333445)

File: lib/Runtime/Language/JavascriptOperators.cpp (hunk 1 above)
Comment (sethbrenith) [reply lib/Runtime/Language/JavascriptOperators.cpp]: It looks to me like result is only false in the non-configurable case, so this should work.

Like Jimmy mentioned, various other methods invite misuse because they accept a PropertyOperationFlags parameter but don't pay attention to PropertyOperation_ThrowOnDeleteIfNotConfig. It seems somewhat inconsistent; some methods like PathTypeHandlerBase::DeleteProperty do respect that flag, but others don't. I'm not sure if it's worth trying to track them all down at this point.

---
In reply to: [173333391](https://github.com/Microsoft/ChakraCore/pull/4790#discussion_r173333391) [](ancestors = 173333391)

File: lib/Runtime/Language/JavascriptOperators.cpp [hunk 3]
```diff
@@ -4818,7 +4818,8 @@ namespace Js
...
         {
             JavascriptError::ThrowCantDelete(propertyOperationFlags, scriptContext, GetPropertyDisplayNameForError(index, scriptContext)->GetString());
```
Comment (boingoing) [inline lib/Runtime/Language/JavascriptOperators.cpp]: Doesn't `JavascriptError::ThrowCantDelete` already check `propertyOperationFlags`? Can we write this as:

```cpp
if (!result)
{
    JavascriptError::ThrowCantDelete(propertyOperationFlags, scriptContext, GetPropertyDisplayNameForError(index, scriptContext)->GetString());
}
```

File: lib/Runtime/Library/JavascriptArray.cpp [hunk 4]
```diff
@@ -9131,7 +9131,8 @@ namespace Js
...
+                    //JS_REENTRANT(jsReentLock, obj->DeleteItem(toIndex, PropertyOperation_ThrowOnDeleteIfNotConfig));
```
Comment (boingoing) [inline lib/Runtime/Library/JavascriptArray.cpp]: Also nitpick, please delete this commented line.

Comment (irinayat-MS) [reply lib/Runtime/Library/JavascriptArray.cpp]: I'm moving the throw into TypedArrayBase to be aligned with other DeleteProperty/DeleteItem handlers, so there will be no change here.

---
In reply to: [173349228](https://github.com/Microsoft/ChakraCore/pull/4790#discussion_r173349228) [](ancestors = 173349228)

File: lib/Runtime/Library/JavascriptArray.cpp (hunk 2 above)
Comment (irinayat-MS) [reply lib/Runtime/Library/JavascriptArray.cpp]: Thank you for the explanations! I'm reverting this file but I might need to follow up offline to understand better about the Proxies and reentrancy :)

---
In reply to: [173337067](https://github.com/Microsoft/ChakraCore/pull/4790#discussion_r173337067) [](ancestors = 173337067,173333445)

File: lib/Runtime/Language/JavascriptOperators.cpp (hunk 1 above)
Comment (irinayat-MS) [reply lib/Runtime/Language/JavascriptOperators.cpp]: After all, it seems that it's better to have this handling in TypedArrayBase::DeleteItem as we discussed before :)

---
In reply to: [173024703](https://github.com/Microsoft/ChakraCore/pull/4790#discussion_r173024703) [](ancestors = 173024703)

File: lib/Runtime/Library/JavascriptError.cpp [hunk 5]
```diff
@@ -694,7 +694,7 @@ namespace Js
         return false;
     }
 
-    bool JavascriptError::ThrowCantDelete(PropertyOperationFlags flags, ScriptContext* scriptContext, PCWSTR varName)
+    bool JavascriptError::ThrowCantDeleteIfStrictModeOrNonconfigurable(PropertyOperationFlags flags, ScriptContext* scriptContext, PCWSTR varName)
```
Comment (irinayat-MS) [inline lib/Runtime/Library/JavascriptError.cpp]: >ThrowCantDeleteIfStrictModeOrNonconfigurable [](start = 26, length = 44)

Ugly name, but similar to "ThrowCantDeleteIfStrictMode".

File: lib/Runtime/Language/JavascriptOperators.cpp [hunk 6]
```diff
@@ -4818,11 +4818,6 @@ namespace Js
 #endif
         }
 
-        if (result == FALSE && (propertyOperationFlags & PropertyOperation_StrictMode))
```
Comment (MSLaguana) [inline lib/Runtime/Language/JavascriptOperators.cpp]: To try and catch any errors in future, it might be worth to add an assert here along the lines of `Assert(result || !(propertyOperationFlags & PropertyOperation_StrictMode)`; that way there is no overhead in release builds, but we should catch regressions in testing.

File: lib/Runtime/Library/TypedArray.cpp [hunk 7]
```diff
@@ -851,6 +851,13 @@ namespace Js
         return PropertyQueryFlags::Property_NotFound_NoProto;
     }
 
+    BOOL TypedArrayBase::DeleteItem(uint32 index, Js::PropertyOperationFlags flags)
```
Comment (irinayat-MS) [inline lib/Runtime/Library/TypedArray.cpp]: >flags [](start = 77, length = 5)

when running in strict mode, the flags will contain PropertyOperation_StrictMode
methods such as copyWithin would pass PropertyOperation_ThrowOnDeleteIfNotConfig

File: lib/Runtime/Types/DictionaryTypeHandler.cpp [hunk 8]
```diff
@@ -912,7 +912,8 @@ namespace Js
             else if (!(descriptor->Attributes & PropertyConfigurable))
             {
                 // Let/const properties do not have attributes and they cannot be deleted
-                JavascriptError::ThrowCantDelete(propertyOperationFlags, scriptContext, propertyNameString->GetString());
+                JavascriptError::ThrowCantDeleteIfStrictModeOrNonconfigurable(
```
Comment (irinayat-MS) [inline lib/Runtime/Types/DictionaryTypeHandler.cpp]: >ThrowCantDeleteIfStrictModeOrNonconfigurable [](start = 33, length = 44)

I wonder whether this one (and a few other current callers of ThrowCantDeleteIfStrictModeOrNonconfigurable) should actually call ThrowCantDeleteIfStrictMode because I don't think the flags would be set here to PropertyOperation_ThrowOnDeleteIfNotConfig (but I don't know how to confirm this).

File: lib/Runtime/Types/PathTypeHandler.cpp [hunk 9]
```diff
@@ -879,7 +879,8 @@ namespace Js
         }
         if (!(attr & ObjectSlotAttr_Configurable))
         {
-            JavascriptError::ThrowCantDelete(PropertyOperation_None, scriptContext, scriptContext->GetPropertyName(propertyId)->GetBuffer());
+            JavascriptError::ThrowCantDeleteIfStrictModeOrNonconfigurable(
+                flags, scriptContext, scriptContext->GetPropertyName(propertyId)->GetBuffer());
```
Comment (irinayat-MS) [inline lib/Runtime/Types/PathTypeHandler.cpp]: >flags [](start = 16, length = 5)

Fix for #4118 (to throw when deleting non-configurable properties in strict mode)

File: test/strict/rlexe.xml [hunk 10]
```diff
@@ -441,7 +441,12 @@
...
       <baseline>13.delete.baseline</baseline>
       <compile-flags>-ES6RegExPrototypeProperties-</compile-flags>
-      <!-- TODO: Delete depends on flag on scriptContext. Add a new opcode for delete 13.delete_sm.js -->
+    </default>
+  </test>
+  <test>
+    <default>
+      <files>13.delete_sm.js</files>
+      <baseline>13.delete_sm.baseline</baseline>
     </default>
```
Comment (irinayat-MS) [inline test/strict/rlexe.xml]: This existing test passes "as is" so decided not to rewrite it :)

**Comment by MSLaguana** [comment]
Looks like this test has caused a test in `ES6TypedArrayExtensions.js` to fail. From what I can tell, it seems that it is expecting one kind of error, but is now getting an error on deleting a nonconfiguable property

**Comment by MSLaguana** [comment]
I think the new behavior is more correct, so the test just needs to have its expectation updated I believe.

File: lib/Runtime/Language/JavascriptOperators.cpp (hunk 6 above)
Comment (sethbrenith) [reply lib/Runtime/Language/JavascriptOperators.cpp]: maybe `result || !(propertyOperationFlags & (PropertyOperation_StrictMode | PropertyOperation_ThrowOnDeleteOrNotConfig))`, since the point of this change is updating the contract elsewhere to respect both flags

---
In reply to: [173516816](https://github.com/Microsoft/ChakraCore/pull/4790#discussion_r173516816) [](ancestors = 173516816)

File: lib/Runtime/Library/JavascriptError.cpp (hunk 5 above)
Comment (sethbrenith) [reply lib/Runtime/Library/JavascriptError.cpp]: `ThrowCantDeleteIfRequiredForNonConfigurableProperty`? Current name sounds like it would throw if the property was nonconfigurable (regardless of the operation flags), which isn't true (and in fact this method has no way to even know if the property was configurable, which must be checked by the caller).

---
In reply to: [173516752](https://github.com/Microsoft/ChakraCore/pull/4790#discussion_r173516752) [](ancestors = 173516752)

Comment (sethbrenith) [reply lib/Runtime/Library/JavascriptError.cpp]: Also, on the topic of this method, I don't like how it forces the caller to do a possibly-expensive conversion to string before figuring out whether we need it. I'd rather take a Var and do `GetPropertyDisplayNameForError(varName, scriptContext)->GetString()` only once we determine that we actually need to throw. Throwing is super expensive anyway, so any additional conversion cost there doesn't particularly matter. Anyhow, this wasn't introduced by your change, so feel free to leave as-is.

---
In reply to: [173520340](https://github.com/Microsoft/ChakraCore/pull/4790#discussion_r173520340) [](ancestors = 173520340,173516752)

**Comment by irinayat-MS** [comment]
Yes, a different error message because. I've updated the test. 

---
In reply to: [371887110](https://github.com/Microsoft/ChakraCore/pull/4790#issuecomment-371887110) [](ancestors = 371887110)

**Comment by irinayat-MS** [comment]
I don't know why the signing tool didn't kick in on my PRs yesterday, but it seems to be doing so now.

---
In reply to: [371616241](https://github.com/Microsoft/ChakraCore/pull/4790#issuecomment-371616241) [](ancestors = 371616241)

File: lib/Runtime/Types/DictionaryTypeHandler.cpp (hunk 8 above)
Comment (sethbrenith) [reply lib/Runtime/Types/DictionaryTypeHandler.cpp]: Seems safer to call the one that respects both flags. If ThrowOnDeleteIfNotConfig is never set, then it would make no difference in behavior.

---
In reply to: [173517742](https://github.com/Microsoft/ChakraCore/pull/4790#discussion_r173517742) [](ancestors = 173517742)

File: lib/Runtime/Library/JavascriptError.cpp (hunk 5 above)
Comment (irinayat-MS) [reply lib/Runtime/Library/JavascriptError.cpp]: 1. name: it throws either in strict mode or if non-configurable. Because this information can only be extracted from the flags, I think the name is more clear now (it doesn't give the impression that it guarantees to throw anymore).
2. string vs var: the callers seem to differ in how they get hold of the string and I don't have a good grasp of details to assess whether var would make perf better for them.

---
In reply to: [173521221](https://github.com/Microsoft/ChakraCore/pull/4790#discussion_r173521221) [](ancestors = 173521221,173520340,173516752)

File: lib/Runtime/Types/DictionaryTypeHandler.cpp (hunk 8 above)
Comment (irinayat-MS) [reply lib/Runtime/Types/DictionaryTypeHandler.cpp]: Agree, that it's safer. I was wondering about whether we could limit usage of ThrowCantDeleteIfStrictModeOrNonconfigurable (because I don't like this method :)).

---
In reply to: [173523027](https://github.com/Microsoft/ChakraCore/pull/4790#discussion_r173523027) [](ancestors = 173523027,173517742)

File: lib/Runtime/Library/JavascriptError.cpp (hunk 5 above)
Comment (boingoing) [reply lib/Runtime/Library/JavascriptError.cpp]: Would be fair to have an overload of this method which takes a `Var` for `varName` and then use `GetPropertyDisplayNameForError` if we'll throw an error. Otherwise don't do the conversion. Could save some time in that case.
