### PR TITLE
Fix a number of Intl-related GitHub and test262 issues, add support for ICU 62.1

### LINKED ISSUE #637: Intl functions shouldn't be constructible
According to the [spec](https://tc39.github.io/ecma262/#sec-built-in-function-objects):

> Built-in function objects that are not identified as constructors do not implement the [[Construct]] internal method unless otherwise specified in the description of a particular function

Since our Intl functions are script functions (implemented in `Intl.js`), they are constructible by default. For example,

``` JS
new Intl.Collator.prototype.compare
```

causes the error:

> TypeError: Collator.prototype.compare: 'this' is not a Collator object

instead of:

> TypeError: Function is not a constructor

### LINKED ISSUE #3332: Native function toString is inconsistent with other engines
We are correct according to the spec (both current and proposed), but all other engines include the name of the function in the toString, whereas we do not.

/cc @bterlson

```
> eshost -h d8,node,sm,jsc,ch-dev-che3 -its .\test.js
## Source
print('' + Intl.DateTimeFormat.supportedLocalesOf);
print('' + Intl.getCanonicalLocales);


┌─────────────┬──────────────────────────────────────────────────┐
│ d8          │ function supportedLocalesOf() { [native code] }  │
│ node        │ function getCanonicalLocales() { [native code] } │
├─────────────┼──────────────────────────────────────────────────┤
│ jsc         │ function supportedLocalesOf() {                  │
│ sm          │     [native code]                                │
│             │ }                                                │
│             │ function getCanonicalLocales() {                 │
│             │     [native code]                                │
│             │ }                                                │
├─────────────┼──────────────────────────────────────────────────┤
│ ch-dev-che3 │ function() {                                     │
│             │     [native code]                                │
│             │ }                                                │
│             │ function() {                                     │
│             │     [native code]                                │
│             │ }                                                │
└─────────────┴──────────────────────────────────────────────────┘
```

https://github.com/Microsoft/ChakraCore/issues/3204#issuecomment-313806817:

> See https://tc39.github.io/Function-prototype-toString-revision/#sec-function.prototype.tostring for a revision to the relevant spec text.
> 
> The gist is: in both old and new spec text, the function name is optional. Old: name can be anything. New: if included, the name must match the actual name of the function. The following two options (and variations of whitespace therein) are allowed:
> 
> ```
> function() {
>     [native code]
> }
> 
> function name() {
>     [native code]
> }
> ```

### LINKED ISSUE #3427: Include function name in built-in function toString (Intl functions)
See: https://github.com/Microsoft/ChakraCore/issues/3204#issuecomment-313806817

The current spec (and proposed, see [proposal](https://tc39.github.io/Function-prototype-toString-revision/#sec-function.prototype.tostring) also linked from the comment above) require that a the toString of a built-in function object matches the NativeFunction grammar, which states that the function name is optional (can be blank) or "the portion of the returned String that would be matched by IdentifierName must be the initial value of the name property of func"

Currently, we omit the name. But I would maintain that it would be a better developer experience if we included the name. Additionally, all the Intl constructors report their name while all (AFAICT) functions omit their name from the toString.

@bterlson: opinions?
/cc @atulkatti

### LINKED ISSUE #3513: [INTL] Change Intl prototypes to plain objects
https://github.com/tc39/ecma402/issues/122

### LINKED ISSUE #3692: Intl.[ctor] called with unusual target produces strange behavior
Found by reading code and wondering "what does this button do?"

Apparently Intl.* constructors do not actually have to be called with new, and can be called with anything as the target.

Using `Intl` or `undefined` as the target (first param of `call`) produces the same result as calling new.
Specifically allowing the target to be `Intl` or `undefined` (see Intl.js code, snippet below) allows for calling as `Intl.NumberFormat` and assigning the same to a var and then calling, producing the same results.

```js
// function NumberFormat
if (this === Intl || this === undefined) {
    // after the call to the same function using new, this === NumberFormat, but any other value of this will be allowed past this check, leading to strange behavior
    return new NumberFormat(locales, options);
}
```

```
## Source
let options = {style:'currency', currency:'USD'};
print(new Intl.NumberFormat('en-us', options).format(42));
print(Intl.NumberFormat.call(Intl, 'en-us', options).format(42));
print(Intl.NumberFormat.call(undefined, 'en-us', options).format(42));

print(Intl.NumberFormat('en-us', options).format(42)); /* call(Intl, ...) */
nf = Intl.NumberFormat;
print(nf('en-us', options).format(42)); /* call(undefined, ...) */

┌──────────────────┬────────┐
│ ch-1.7.1         │ $42.00 │
│ ch-master-latest │ $42.00 │
│ d8               │ $42.00 │
│ jsc              │ $42.00 │
│ node             │ $42.00 │
│ node-ch          │        │
│ sm               │        │
└──────────────────┴────────┘
```

Using anything else apparently returns the object passed in:

```
## Source
let options = {style:'currency', currency:'USD'};
let a = Intl.NumberFormat.call({}, 'en-us', options);
print(a);
print(a.format(42));

┌──────────────────┬───────────────────────────────────────────────────────────────┐
│ d8               │ [object Object]                                               │
│ jsc              │ $42.00                                                        │
│ sm               │                                                               │
├──────────────────┼───────────────────────────────────────────────────────────────┤
│ ch-1.7.1         │ [object Object]                                               │
│ ch-master-latest │ TypeError: Object doesn't support property or method 'format' │
├──────────────────┼───────────────────────────────────────────────────────────────┤
│ node-ch          │ {}                                                            │
│                  │ TypeError: Object doesn't support property or method 'format' │
├──────────────────┼───────────────────────────────────────────────────────────────┤
│ node             │ NumberFormat {}                                               │
│                  │ $42.00                                                        │
└──────────────────┴───────────────────────────────────────────────────────────────┘
```

```
## Source
let options = {style:'currency', currency:'USD'};
let a = Intl.NumberFormat.call(function foo() {}, 'en-us', options);
print(a);
print(a.format(42));

┌──────────────────┬───────────────────────────────────────────────────────────────┐
│ d8               │ [object Object]                                               │
│ jsc              │ $42.00                                                        │
│ sm               │                                                               │
├──────────────────┼───────────────────────────────────────────────────────────────┤
│ ch-1.7.1         │ function foo() {}                                             │
│ ch-master-latest │ TypeError: Object doesn't support property or method 'format' │
├──────────────────┼───────────────────────────────────────────────────────────────┤
│ node-ch          │ [Function: foo]                                               │
│                  │ TypeError: Object doesn't support property or method 'format' │
├──────────────────┼───────────────────────────────────────────────────────────────┤
│ node             │ NumberFormat {}                                               │
│                  │ $42.00                                                        │
└──────────────────┴───────────────────────────────────────────────────────────────┘
```

```
## Source
let options = {style:'currency', currency:'USD'};
let a = Intl.NumberFormat.call(new (function foo() {}), 'en-us', options);
print(a);
print(a.format(42));

┌──────────────────┬───────────────────────────────────────────────────────────────┐
│ d8               │ [object Object]                                               │
│ jsc              │ $42.00                                                        │
│ sm               │                                                               │
├──────────────────┼───────────────────────────────────────────────────────────────┤
│ ch-1.7.1         │ [object Object]                                               │
│ ch-master-latest │ TypeError: Object doesn't support property or method 'format' │
├──────────────────┼───────────────────────────────────────────────────────────────┤
│ node-ch          │ foo {}                                                        │
│                  │ TypeError: Object doesn't support property or method 'format' │
├──────────────────┼───────────────────────────────────────────────────────────────┤
│ node             │ NumberFormat {}                                               │
│                  │ $42.00                                                        │
└──────────────────┴───────────────────────────────────────────────────────────────┘
```

Which leads to fun things like formatting a Date with something you would have hoped was a NumberFormat object

```
## Source
let a = Intl.NumberFormat.call(Intl.DateTimeFormat, 'en-us', { style: 'percent' });
print(a);
print((a.format || (new a).format)(new Date(2017,0,1)));


┌──────────────────┬────────────────────────────────────────────────────────────────────────┐
│ d8               │ [object Object]                                                        │
│ jsc              │ 148,325,760,000,000%                                                   │
│ sm               │                                                                        │
├──────────────────┼────────────────────────────────────────────────────────────────────────┤
│ ch-1.7.1         │ function DateTimeFormat() { [native code] }                            │
│ ch-master-latest │ ?1?/?1?/?2017                                                          │
├──────────────────┼────────────────────────────────────────────────────────────────────────┤
│ node-ch          │ { [Function: DateTimeFormat] __relevantExtensionKeys: [ 'ca', 'nu' ] } │
│                  │ ‎1‎/‎1‎/‎2017                                                          │
├──────────────────┼────────────────────────────────────────────────────────────────────────┤
│ node             │ NumberFormat {}                                                        │
│                  │ 148,325,760,000,000%                                                   │
└──────────────────┴────────────────────────────────────────────────────────────────────────┘
```

### LINKED ISSUE #5603: Intl ICU: Call ucal_getType instead of calling ucal_setGregorianChange and checking for failure?
This issue is regarding a bit of code the ICU implementation for Intl. (cc: @jackhorton).

Currently, it looks like ChakraCore calls `ucal_setGregorianChange` and sees if it *fails* with `U_UNSUPPORTED_ERROR ` in order to detect non-Gregorian calendars.

Link to the code:
https://github.com/Microsoft/ChakraCore/blob/c567e4e674e1d1e6af0006060c0277846fe1f862/lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp#L2658

However, it seems like you could instead directly call the ICU API `ucal_getType`, and then simply check for the string "`gregorian`" instead to see if the underlying calendar object was a Gregorian calendar or not.

Link to ICU API docs: http://icu-project.org/apiref/icu4c/ucal_8h.html#ac3da68a172e0dff2097004c811a49b13

This seems like it would help clean it up a bit. :)

### PR DESCRIPTION
**Pull request by jackhorton**
Fixes #637 
Fixes #5603 
Fixes #3427 
Fixes #3513
Fixes #3692

Adds build support for ICU 62.1 by enabling /utf-8 in all ICU files rather than just i18n

@rhuanjl's function.length PR took our pass rate from 486 to 530; this further increases it to 580 (compared to V8's 582 and SpiderMonkey's 597). The remaining failures are all known, but slightly more complicated issues, where we shell out to ICU when the spec wants us to do something particularly snowflake-y -- V8 fails most of these tests as well. The remaining ~350 tests are for features that we don't implement and V8/SM either haven't implemented or have turned off by default.

For what its worth, some of the features we haven't implemented are extremely straightforward -- the Intl version of String.prototype.toLocale{Lower|Upper}Case and {Typed}Array.prototype.toLocaleString are tiny. Fixing those tests (by implementing those features) would bump us up to 596.

### CODE REVIEW

File: lib/Runtime/Library/EngineInterfaceObject.cpp [hunk 1]
```diff
@@ -315,32 +315,47 @@ namespace Js
...
         }
 
-        return scriptContext->GetLibrary()->GetUndefined();
+        if (!creatingConstructor)
+        {
+            FunctionInfo *info = func->GetFunctionInfo();
+            info->SetAttributes((FunctionInfo::Attributes) (info->GetAttributes() | FunctionInfo::Attributes::ErrorOnNew));
+
+            func->SetAttributes(PropertyIds::prototype, PropertyConfigurable);
+            func->DeleteProperty(PropertyIds::prototype, PropertyOperationFlags::PropertyOperation_Force);
```
Comment (jackhorton) [inline lib/Runtime/Library/EngineInterfaceObject.cpp]: I noticed that DeleteProperty doesn't respect PropertyOperation_Force, at least not the way I thought it should. It makes it so the operation doesn't throw, but it doesn't bypass configurability. I can change that if we all agree that force should bypass any other restrictions.

File: deps/Chakra.ICU/Chakra.ICU.Build.props [hunk 2]
```diff
@@ -36,6 +36,9 @@
         _CRT_SECURE_NO_DEPRECATE;
         %(PreprocessorDefinitions)
       </PreprocessorDefinitions>
+
+      <!-- Some ICU files use embedded UTF-8 -->
```
Comment (jefgen) [inline deps/Chakra.ICU/Chakra.ICU.Build.props]: FWIW, as of ICU v59, all of the source files are supposed to be encoded as UTF-8.

File: lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp [hunk 3]
```diff
@@ -2653,14 +2653,13 @@ DEFINE_ISXLOCALEAVAILABLE(PR, uloc)
...
             UCalendar *cal = const_cast<UCalendar *>(udat_getCalendar(*dtf));
-            ucal_setGregorianChange(cal, -8.64e15, &status);
-
-            // status can be U_UNSUPPORTED_ERROR if the calendar isn't gregorian, which
-            // there does not seem to be a way to check for ahead of time in the C API
-            AssertOrFailFastMsg(U_SUCCESS(status) || status == U_UNSUPPORTED_ERROR, ICU_ERRORMESSAGE(status));
-
-            // If we passed the previous check, we should reset the status to U_ZERO_ERROR (in case it was U_UNSUPPORTED_ERROR)
-            status = U_ZERO_ERROR;
+            if (strcmp(ucal_getType(cal, &status), "gregorian") == 0)
```
Comment (jefgen) [inline lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp]: Thanks Jack! 👍

File: deps/Chakra.ICU/Chakra.ICU.Build.props (hunk 2 above)
Comment (jackhorton) [reply deps/Chakra.ICU/Chakra.ICU.Build.props]: Yeah, it makes more sense in Chakra.ICU.Build.props anyways.

File: lib/Runtime/Library/EngineInterfaceObject.cpp [hunk 4]
```diff
@@ -315,32 +315,47 @@ namespace Js
...
 
-        if (callInfo.Count >= 2 && JavascriptFunction::Is(args.Values[1]))
+        AssertOrFailFast((callInfo.Count == 3 || callInfo.Count == 4) && JavascriptFunction::Is(args[1]) && JavascriptString::Is(args[2]));
+
+        JavascriptFunction *func = JavascriptFunction::UnsafeFromVar(args[1]);
+        JavascriptString *methodName = JavascriptString::UnsafeFromVar(args[2]);
+
+        func->GetFunctionProxy()->SetIsPublicLibraryCode();
+
+        const char16 *methodNameBuf = methodName->GetSz();
```
Comment (MSLaguana) [inline lib/Runtime/Library/EngineInterfaceObject.cpp]: I don't expect the intl js code to do anything too zany here, but is it worth using `GetString` instead of `GetSz`? Since we're passing the length around anyway either should work, and I know that @sethbrenith  has made some good points that it is typically better hygiene to use the `GetString` version

Comment (jackhorton) [reply lib/Runtime/Library/EngineInterfaceObject.cpp]: We use `wcsrchr` below, which doesn't take a length parameter. It used to be GetString and we always call it on literal strings, but in case we ever call it on a non-literal-string in the future, the `wcsrchr` would start searching past the end of the string we actually wanted.

Comment (MSLaguana) [reply lib/Runtime/Library/EngineInterfaceObject.cpp]: Makes sense.

File: lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp (hunk 3 above)
Comment (MSLaguana) [reply lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp]: I can't see much documentation for this; are we expected to free/release the string returned by `ucal_getType`? Or is it static?

File: lib/Runtime/Library/EngineInterfaceObject.cpp (hunk 4 above)
Comment (jackhorton) [reply lib/Runtime/Library/EngineInterfaceObject.cpp]: Also, this runs on Intl initialization, so its not particularly hot. I can add a comment for it.

File: lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp (hunk 3 above)
Comment (MSLaguana) [reply lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp]: Any idea what the error scenarios are too? If `status` ends up not being success, is the returned string guaranteed to be nullptr or otherwise safe? Should we be checking the status code prior to using the returned value?

Comment (jackhorton) [reply lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp]: I can assert right after getType, though I believe anything that returns a `const char *` returns a static string that shouldn't be freed.

File: lib/Runtime/Library/EngineInterfaceObject.cpp (hunk 1 above)
Comment (MSLaguana) [reply lib/Runtime/Library/EngineInterfaceObject.cpp]: Since this is used by library code only, are there any cases of non-configurable prototype properties? Do you construct lambdas which go through this path?

Just out of caution I would be inclined to leave `Force` as it is, but it does sound like the intention is that it skips those kinds of restrictions, at least for adding properties.

**Comment by MSLaguana** [comment]
Looks like some TTD tests are complaining about this change.

File: lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp (hunk 3 above)
Comment (jefgen) [reply lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp]: Yeah, I would agree that the documentation is rather lacking for this ICU API.

The API will return a static string that does not need to be free'ed. The only way `status` would be set to a failure state is if the incoming parameter is already a failure. The API itself doesn't modify the `status` variable.

I've filed a ticket on upstream ICU to improve the docs for this function:
https://unicode-org.atlassian.net/browse/ICU-20082
(Thanks for the feedback! :) )

File: lib/Runtime/Library/EngineInterfaceObject.cpp (hunk 1 above)
Comment (jackhorton) [reply lib/Runtime/Library/EngineInterfaceObject.cpp]: We don't _currently_ put any lambdas through this codepath, but theres nothing stopping us from doing so in the future. Additionally, we don't install anything on the prototypes of functions that go through this particular code path, where the prototype gets deleted. Constructor's prototypes get modified, but they don't hit this.

**Comment by jackhorton** [comment]
Yeah, which is odd. I will try to run the TTD tests locally with ICU enabled -- i hope its not _actually_ an xplat-only failure.

**Comment by jackhorton** [comment]
Last of the low-hanging fruit is done :fire:

image

**Comment by zenparsing** [comment]
@jackhorton 🔥, indeed

File: lib/Runtime/Library/EngineInterfaceObject.cpp [hunk 5]
```diff
@@ -317,30 +317,43 @@ namespace Js
...
         }
 
-        return scriptContext->GetLibrary()->GetUndefined();
+        if (!creatingConstructor)
+        {
+            FunctionInfo *info = func->GetFunctionInfo();
+            info->SetAttributes((FunctionInfo::Attributes) (info->GetAttributes() | FunctionInfo::Attributes::ErrorOnNew));
+
+            AssertOrFailFast(func->GetDynamicType()->GetTypeHandler()->IsDeferredTypeHandler());
+            DynamicTypeHandler::SetInstanceTypeHandler(func, scriptContext->GetLibrary()->GetDeferredFunctionTypeHandlerNoPrototype());
```
Comment (jackhorton) [inline lib/Runtime/Library/EngineInterfaceObject.cpp]: @pleath @boingoing Thoughts on this way of making sure these builtins don't have prototypes, rather than forcefully deleting the prototype property?

Comment (rhuanjl) [reply lib/Runtime/Library/EngineInterfaceObject.cpp]: Per the piece I did on adding length properties - this type seems correct for this BUT - the tt-debug errors you're getting look like a problem I had with my initial attempts at changing function types to add lengths so there's a chance that this change caused the TTDebug test fails - I got that particular test fail when my types were wrong such that accessing a function caused it's type to transform.

**Comment by dilijev** [comment]
Sorry for the delay reviewing this.

File: lib/Runtime/Base/JnDirectFields.h [hunk 6]
```diff
@@ -517,6 +517,11 @@ ENTRY(tagPublicLibraryCode)
 ENTRY(winglob)
 ENTRY(platform)
 ENTRY(formatToParts)
+ENTRY(FallbackSymbol)
+
+// This symbol is not part of the regular Symbol API and is only used in rare circumstances in Intl.js for backwards compatibility
+// with the Intl v1 spec. It is visible to the user only using Object.getOwnPropertySymbols(Intl.NumberFormat.call(new Intl.NumberFormat())).
```
Comment (dilijev) [inline lib/Runtime/Base/JnDirectFields.h]: >It is visible to the user only using Object.getOwnPropertySymbols(Intl.NumberFormat.call(new Intl.NumberFormat())). [](start = 26, length = 115)

is it supposed to be visible to the user this way?

File: lib/Runtime/ByteCode/ByteCodeCacheReleaseFileVersion.h [hunk 7]
```diff
@@ -4,6 +4,6 @@
 //-------------------------------------------------------------------------------------------------------
 // NOTE: If there is a merge conflict the correct fix is to make a new GUID.
 
-// {39DEDDF4-EEE4-43E8-A2C8-2550A26007D6}
+// d338af4b-9ef1-48f9-b103-7b2ea58a9478
```
Comment (dilijev) [inline lib/Runtime/ByteCode/ByteCodeCacheReleaseFileVersion.h]: nit: format of this comment

File: lib/Runtime/Base/JnDirectFields.h (hunk 6 above)
Comment (jackhorton) [reply lib/Runtime/Base/JnDirectFields.h]: Oh. We have never had the correct behavior here so I just tried to emulate what the other engines do. I believe both V8 and SM showed the symbol through GetOwnPropertySymbols (since the symbol is defined on `this`, without being an internal property, I am not sure how it could have ever not been user-visible? Perhaps I am missing something.)

Comment (gsathya) [reply lib/Runtime/Base/JnDirectFields.h]: Ah, you're correct. I was under the incorrect impression that this was using a private symbol that Dan was alluding to [here](https://github.com/tc39/ecma402/pull/84#issuecomment-282483765). It's weird that the spec chose to expose this publicly.

> I am not sure how it could have ever not been user-visible? 

One way would be for the spec to define the lookup using a WeakMap.

Comment (jackhorton) [reply lib/Runtime/Base/JnDirectFields.h]: The rest of the spec works off of internal slots; if FallbackSymbol were an internal slot, then that should serve the same purpose, no? Regardless, my understanding was that the fallback symbol was put in place because intl v2 broke a specific library that was using Intl in a relatively odd way, but since at least Edge has never gotten this behavior correct, I assume that the fallback behavior is too rare to be worth trying to update at this point.

File: lib/Runtime/Library/EngineInterfaceObject.cpp (hunk 5 above)
Comment (rhuanjl) [reply lib/Runtime/Library/EngineInterfaceObject.cpp]: @jackhorton I added that type in #5405 and was now planning on renaming it in #5610 (as other function types say "prototype" in their name if they have one and don't mention it if they don't whereas they explicitly mention if they have a length - which this does)

Just an FYI that if 5610 is merged before this and this used here will need to rename it here (unless I drop the name change from 5610)

Comment (jackhorton) [reply lib/Runtime/Library/EngineInterfaceObject.cpp]: Yeah I was going to wait to merge this until we got 5610 and fromEntries merged so that you dont have to keep rebasing/re-bytecode-genning on top of all of our changes. I wanted to wait for some more opinion on 5610 but I may just merge it today.
