### PR TITLE
Fix exception was thrown if value arg is undefined for DataView.set

### LINKED ISSUE #5548: DataView.setFloat32 should convert undefined value to NaN
Hi everyone, 
according to [24.3.4.13](https://www.ecma-international.org/ecma-262/8.0/index.html#sec-dataview.prototype.setfloat32) DataView.setFloat32 should cast to NaN when value argument is not present.

OS: Ubuntu 16.04
version: 1.10.1

steps to reproduce:
```
var buffer = new ArrayBuffer(8);
var sample = new DataView(buffer, 0);
var result = sample.setFloat32(0);
print(sample.getFloat32(0))
```
Actual results:
TypeError: Invalid arguments in DataView

Expected results:
NaN

V8, SpiderMonkey and JSC works as expected.

cinfuzz

### PR DESCRIPTION
**Pull request by hez2010**
Fix exception was thrown if value arg is undefined for DataView.set

Fixes #5548

### CODE REVIEW

File: lib/Runtime/Library/DataView.cpp [hunk 1]
```diff
@@ -360,12 +360,12 @@ namespace Js
...
         }
-        if (args.Info.Count < 3)
+        if (args.Info.Count < 2)
         {
-            JavascriptError::ThrowTypeError(scriptContext, JSERR_DataView_NeedArgument,  _u("offset or value"));
+            JavascriptError::ThrowTypeError(scriptContext, JSERR_DataView_NeedArgument,  _u("offset"));
         }
         DataView* dataView = VarTo<DataView>(args[0]);
-        int8 value = JavascriptConversion::ToInt8(args[2], scriptContext);
+        int8 value = args.Info.Count == 2 ? 0 : JavascriptConversion::ToInt8(args[2], scriptContext);
```
Comment (rhuanjl) [inline lib/Runtime/Library/DataView.cpp:368]: The logic looks correct to me, BUT, looking at this several branches are taken, imagine the "normal" case where no error will be thrown, we do:

1. if arg0 (i.e. `this`) doesn't exist throw
2. if arg0 is not a dataView, throw
3. if there are less than 2 args (i.e. if arg1 doesn't exist), throw
4. if there is no 3rd arg, i.e. follow the default to 0/NaN case
5. only if none of those conditions were met do the "normal" version

Could we optimise this slightly?

Minimally the args == 0 check can be combined with the < 2 check

More extensively we could do:
1. define the value variable at the start without initialising.
2. check for less than 3 args
3. within the `false` path, do the VarIs<DataView> check but no others, set the value to the conversion result
4. within the `true` path  do all the other checks a) less than 2 args = throw b) arg0 not a DataView = throw, otherwise set the value to 0 (or Nan)

File: test/Bugs/dataview_setfloat_nan_if_undefined.js [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+  sample.setUint32(0);
+  if (sample.getUint32(0) === 0) passCnt++;
+  sample.setUint16(0);
+  if (sample.getUint16(0) === 0) passCnt++;
+  sample.setUint8(0);
+  if (sample.getUint8(0) === 0) passCnt++;
+} catch (err) { }
+
+if (passCnt === 8) print("PASSED")
+else print("FAILED")
```
Comment (rhuanjl) [inline test/Bugs/dataview_setfloat_nan_if_undefined.js:24]: This looks like a good test, though it would be good to avoid adding a new file for it if we can - at some point I'd like us to combine a lot of the old test files, this could be slotted into the existing test/typdearray/dataview2.js test file.

Comment (zenparsing) [reply test/Bugs/dataview_setfloat_nan_if_undefined.js:24]: If you move the tests into that file you can use use the `assert` methods, which can help with better error reporting.

File: lib/Runtime/Library/DataView.cpp [hunk 3]
```diff
@@ -517,14 +517,14 @@ namespace Js
...
         }
-        if (args.Info.Count < 3)
+        if (args.Info.Count < 2)
         {
-            JavascriptError::ThrowTypeError(scriptContext, JSERR_DataView_NeedArgument);
+            JavascriptError::ThrowTypeError(scriptContext, JSERR_DataView_NeedArgument, _u("offset"));
         }
         DataView* dataView = VarTo<DataView>(args[0]);
-        float value = JavascriptConversion::ToFloat(args[2], scriptContext);
+        float value = args.Info.Count == 2 ? static_cast<float>(JavascriptNumber::NaN) : JavascriptConversion::ToFloat(args[2], scriptContext);
```
Comment (zenparsing) [inline lib/Runtime/Library/DataView.cpp:527]: Nit: let's start to tame the overlong line lengths in the codebase for readability:

```cpp
float value = args.Info.Count == 2
    ? static_cast<float>(JavascriptNumber::NaN)
    : JavascriptConversion::ToFloat(args[2], scriptContext);
```

File: test/Bugs/dataview_setfloat_nan_if_undefined.js (hunk 2 above)
Comment (hez2010) [reply test/Bugs/dataview_setfloat_nan_if_undefined.js]: Done.

File: lib/Runtime/Library/DataView.cpp (hunk 3 above)
Comment (hez2010) [reply lib/Runtime/Library/DataView.cpp]: Done.

File: lib/Runtime/Library/DataView.cpp (hunk 1 above)
Comment (hez2010) [reply lib/Runtime/Library/DataView.cpp]: Done.

**Comment by rhuanjl** [comment]
I'll merge this when the checks pass.

**Comment by rhuanjl** [comment]
Thanks for the contribution @hez2010 I look forward to seeing more :)
