### PR TITLE
Make JsSerialize to work with strings

### LINKED ISSUE #4824: JsSerialize miscalculates script size if passed a JavascriptString
The JSRT method `JsSerialize` accepts either `ExternalArrayBuffer`s or `JavascriptString`s, which can be encoded in utf8 or utf16. If it is given a `JavascriptString`, then it will incorrectly use the string length (that is, number of characters) as the number of bytes, leading to issues. It also looks like it tries to support utf8 strings, but (until another PR lands) all javascript strings will be utf16 encoded, so that looks suspect as well.

### PR DESCRIPTION
**Pull request by irinayat-MS**
Fixes #4824:
- treat strings as wide
- get the buffer lengh in bytes (not chars)

Added UTs for both array and string call patterns.

### CODE REVIEW

File: lib/Jsrt/Jsrt.cpp [hunk 1]
```diff
@@ -4971,25 +4971,21 @@ CHAKRA_API JsSerialize(
...
+    const bool isUtf8 = !isString && !(parseAttributes & JsParseScriptAttributeArrayBufferIsUtf16Encoded);
 
     LoadScriptFlag scriptFlag;
     const byte* script = isExternalArray ?
         ((Js::ExternalArrayBuffer*)(scriptVal))->GetBuffer() :
         (const byte*)((Js::JavascriptString*)(scriptVal))->GetSz();
     const size_t cb = isExternalArray ?
         ((Js::ExternalArrayBuffer*)(scriptVal))->GetByteLength() :
-        ((Js::JavascriptString*)(scriptVal))->GetLength();
+        ((Js::JavascriptString*)(scriptVal))->GetAllocatedByteCount();
```
Comment (MSLaguana) [inline lib/Jsrt/Jsrt.cpp]: I didn't realize we had this function. I don't think that this is always correct though; looks like a substring can report 0 for this... Might be safer to just use `->GetLength() * 2`? Although the call to `GetSz` just before will flatten strings and might mean that this ends up behaving as expected.

File: bin/NativeTests/JsRTApiTest.cpp [hunk 2]
```diff
@@ -2664,4 +2664,87 @@ namespace JsRTApiTest
     {
         JsRTApiTest::RunWithAttributes(JsRTApiTest::JsCreateStringTest);
     }
+
+    void ApiTest_JsSerializeArrayTest(JsRuntimeAttributes /*attributes*/, JsRuntimeHandle /*runtime*/)
+    {
+        LPCSTR raw_script = "(function (){return true;})();";
+        LPCWSTR raw_wscript = L"(function (){return true;})();";
+
+        // JsSerializeScript has could test coverage and can be used as an oracle for JsSerialize
```
Comment (MSLaguana) [inline bin/NativeTests/JsRTApiTest.cpp]: Small typo `has could`, should be `has good` I think?

Comment (irinayat-MS) [reply bin/NativeTests/JsRTApiTest.cpp]: yes :)

---
In reply to: [177916805](https://github.com/Microsoft/ChakraCore/pull/4896#discussion_r177916805) [](ancestors = 177916805)

File: lib/Jsrt/Jsrt.cpp (hunk 1 above)
Comment (irinayat-MS) [reply lib/Jsrt/Jsrt.cpp]: What would it mean to have scriptVal as SubString here? How could I test it? From the general design point of view, if GetAllocatedByteCount doesn't work for subclasses they must override it (which SubString does, but I don't understand semantics: why is it correct to return 0 if still have original reference?). I'd rather not do math manually here because it will become wrong when we enable narrow strings (and hard to spot that it needs to be fixed).

---
In reply to: [177916631](https://github.com/Microsoft/ChakraCore/pull/4896#discussion_r177916631) [](ancestors = 177916631)

Comment (MSLaguana) [reply lib/Jsrt/Jsrt.cpp]: My hypothetical scenario would be if you retrieved a string from script instead of explicitly creating it (e.g. you run a function like `function () { return "1234".substring(2);}`) and then pass that value into `JsSerialize`. I don't endorse this, nor do I expect it, but right now it's at least possible.

Considering that `JavascriptString::GetAllocatedByteCount` also returns 0 in the case when it isn't finalized (essentially if it isn't yet flattened into a single buffer; we have a number of tree-like structures for representing intermediate string forms) it may be worth addressing.... but also considering that `JavascriptString::GetSz()` flattens and finalizes strings, as long as we `GetSz` before checking the allocated bytes it may be ok.

Comment (irinayat-MS) [reply lib/Jsrt/Jsrt.cpp]: Added JavascriptString::GetSizeInBytes

---
In reply to: [177919117](https://github.com/Microsoft/ChakraCore/pull/4896#discussion_r177919117) [](ancestors = 177919117)
