### PR TITLE
Fix function expressions not to allow overwrite themselves

### LINKED ISSUE #2899: bugs with non-lazy operators
See https://github.com/nodejs/node-chakracore/issues/223

[Last case](https://github.com/nodejs/node-chakracore/issues/223#issuecomment-298456449) was tested under `node-chakracore 8.0.0-nightly20170429a043cb86fe`

### PR DESCRIPTION
**Pull request by irinayat-MS**
Fixes #2899

The proposed fix would lead to generating bytecode like this:
  Line  26: foo &= 0;
  Col    2: ^
    0008   And_A                R5  R4  R2
    000c   Unused               R5

We could probably avoid generating any bytecode at all by doing a top level GetIsFuncExpr check but I'm not sure whether that might affect other scenarios.

### CODE REVIEW

**Comment by rhuanjl** [comment]
The same issue also impacts — and ++ (knopincpost/knopdevppst/knopincpre/knopdecpre)

IMO should fix those at the same time.

File: test/Closures/update-funcexpr.js [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+}
+
+var tests = [
+    {
+        name: "Functions can overwrite themselves",
+        body: function () {
+            function foo1() {
+                foo1 = 42;
+                assert.isTrue(typeof foo1 == "number", "foo1 should overwrite itself to a number");
+                assert.areEqual(42, foo1, "value of foo1 after assingment");
```
Comment (sethbrenith) [inline test/Closures/update-funcexpr.js]: >ng [](start = 67, length = 2)

nit: gn

File: test/Closures/update-funcexpr.js [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+if (this.WScript && this.WScript.LoadScriptFile) { // Check for running in ch
+    this.WScript.LoadScriptFile("..\\UnitTestFramework\\UnitTestFramework.js");
+}
+
+var tests = [
+    {
+        name: "Functions can overwrite themselves",
+        body: function () {
+            function foo1() {
+                foo1 = 42;
```
Comment (akroshg) [inline test/Closures/update-funcexpr.js]: hmm, I thought this are syntax or early reference error.

Comment (akroshg) [reply test/Closures/update-funcexpr.js]: or may be not.

---
In reply to: [181449110](https://github.com/Microsoft/ChakraCore/pull/4987#discussion_r181449110) [](ancestors = 181449110)

File: lib/Runtime/ByteCode/ByteCodeEmitter.cpp [hunk 3]
```diff
@@ -10760,38 +10760,34 @@ void Emit(ParseNode *pnode, ByteCodeGenerator *byteCodeGenerator, FuncInfo *func
...
         // (i.e., is a constant).
-        if (pnode->isUsed || fReturnValue || funcInfo->RegIsConst(pnode->AsParseNodeBin()->pnode1->location))
-        {
-            // If the assign-op result is used, grab a register to hold it.
-            funcInfo->AcquireLoc(pnode);
+        const bool lhs_unassignable =
+            pnode->isUsed
+            || fReturnValue
+            || funcInfo->RegIsConst(lhs->location)
+            || (lhs->nop == knopName && lhs->AsParseNodePid()->sym->GetIsFuncExpr());
```
Comment (pleath) [inline lib/Runtime/ByteCode/ByteCodeEmitter.cpp]: I don't think we can count on the sym to be non-null here. It may, for instance, be an undeclared name, in which case I don't think we create a sym for it.

File: test/Closures/update-funcexpr.js [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+                assert.isTrue(typeof foo3 == "number", "foo3 should overwrite itself to a number");
+                assert.areEqual(0, foo3, "value of foo3 after assingment");
+            }
+            foo3();
+        }
+    },
+    {
+        name: "Function expressions cannot overwrite themselves",
+        body: function () {
+            (function foo1() {
```
Comment (tcare) [inline test/Closures/update-funcexpr.js]: another interesting case here might be:

var foo = function foo() { … }

Comment (pleath) [reply test/Closures/update-funcexpr.js]: You mean, to make sure the assignment to the var does happen?

Comment (tcare) [reply test/Closures/update-funcexpr.js]: In that case the inner foo won't get overwritten (as this is testing) but the outer var does not change either since the reference in the body points to the function expression name rather than the var.

**Comment by irinayat-MS** [comment]
Good point. Looking into it.

---
In reply to: [381191500](https://github.com/Microsoft/ChakraCore/pull/4987#issuecomment-381191500) [](ancestors = 381191500)

**Comment by irinayat-MS** [comment]
Simple assignment executes all calls for function expressions as for normal vars, they just happen to do nothing.

Why we don't skip the whole thing in other cases when lhs isn't assignable (RegIsConst)?


---
In reply to: [381204778](https://github.com/Microsoft/ChakraCore/pull/4987#issuecomment-381204778) [](ancestors = 381204778)

**Comment by pleath** [comment]
It's not worth optimizing, no. But are you saying that we throw a syntax error in some cases of strict mode assignment to function expression but not in others?

**Comment by irinayat-MS** [comment]
As far as I understand, we always throw in strict mode but we still overwrite the function expression before the throw in the non-plain assignment cases.

---
In reply to: [381278112](https://github.com/Microsoft/ChakraCore/pull/4987#issuecomment-381278112) [](ancestors = 381278112)

File: test/Closures/update-funcexpr.js (hunk 4 above)
Comment (irinayat-MS) [reply test/Closures/update-funcexpr.js]: (function foo() {
    var foo = foo;
    console.log(foo);
})();
// prints out 'undefined' (same in Chrome)

var bar = function bar() { console.log(bar); }
bar();
// prints out 'function bar() { console.log(bar); }' (same in Chrome)

So it seems that we are doing the right thing already (and I'd think it's a different scenario from attempting to assign to a function expression I'm fixing). Or did you have something else in mind?

**Comment by irinayat-MS** [comment]
@dotnet-bot test OSX static_osx_osx_release please
