### PR TITLE
Properly set name property of named class expressions assigned to object property

### LINKED ISSUE #4635: Named class expression does not set class name property when assigned to object member
```js
const o = {};
o.myclass = class MyClass { }
assert(o.myclass.name === "MyClass")  // fails
```

This has been a bug for quite some time, and is breaking an updated Node-ChakraCore test.

### PR DESCRIPTION
**Pull request by boingoing**
When we have a named class expression in an object property assignment, we ignore the name of the class and don't set it as the 'name' property of the class.

Fixes #4635

### CODE REVIEW

File: test/es6/bug_issue_4635.js [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+        obj.a = class A { };
+        assert.areEqual('A', obj.a.name, "Since the class expression is named, it should have a name property");
+    }
+  },
+  {
+    name: "Unnamed function expression should not have a name property",
+    body: function () {
+        var obj = {};
+        obj.a = class { };
+        assert.areEqual('', obj.a.name, "Since the class expression is unnamed, it should not have a name property");
```
Comment (jackhorton) [inline test/es6/bug_issue_4635.js]: Is it worth having a test that tests for `obj.a.constructor.name`? Or are they guaranteed to be the same? The code that originally brought this bug to light used `this.constructor.name`.

Comment (boingoing) [reply test/es6/bug_issue_4635.js]: I added these both for instance and via method cases. Should be redundant since should be the case of `this.constructor === obj.a`. No reason not to be a little more thorough here.

**Comment by boingoing** [comment]
@dotnet-bot test OSX static_osx_osx_debug please

**Comment by boingoing** [comment]
Thanks!
