### PR TITLE
osx: fix osx binary backward compatibility

### LINKED ISSUE #4393: Symbol not found: _clock_gettime
Building Chakra on macOS ≤ 10.12 resulted in `Symbol not found: _clock_gettime`

screen shot 2017-12-07 at 10 31 32 pm

//cc @bterlson

### PR DESCRIPTION
**Pull request by obastemur**
Fixes #4393

### CODE REVIEW

**Comment by obastemur** [comment]
Please help CR and merge.

**Comment by obastemur** [comment]
Release 1.7 branch is broken / failing on Windows with the error below;

```
07:54:32 3>    ch.exe    -DumpOnCrash -WERExceptionSupport -ExtendedErrorStackForTestHost -BaselineMode -forceNative -off:simpleJit -bgJitDelay:0 -dynamicprofileinput:profile.dpl.UnnamedTest62  -$262 D:\j\w\ci_dev12_x64_---276a6eb6\test\$262\$262test.js >D:\j\w\ci_dev12_x64_---276a6eb6\test\$262\testout2 2>&1
07:54:32 3>ERROR: name of output file: D:\j\w\ci_dev12_x64_---276a6eb6\test\$262\testout2; size: 152; creation: Fri Dec 08 07:45:55 2017, last access: Fri Dec 08 07:45:55 2017, now: Fri Dec 08 07:45:57 2017
07:54:32 3>ERROR: bad output file follows ============
07:54:32 3>test262/error Test262Error: Expected SameValue(«1ok», «0ok») to be true
07:54:32 3>test262/error Test262Error: Expected SameValue(«0ok», «1ok») to be true
```

This error is unrelated to what this PR does (xplat only). Any idea on this?

**Comment by MSLaguana** [comment]
@dotnet-bot test Windows 7 ci_dev12_x64_debug please

File: pal/src/misc/time.cpp [hunk 1]
```diff
@@ -329,7 +329,10 @@ GetTickCount64Fallback()
 {
     ULONGLONG retval = 0;
 
-#if HAVE_CLOCK_MONOTONIC_COARSE || HAVE_CLOCK_MONOTONIC
+    // The `__APPLE__` below is unlikely. However, if osx future version
+    // supports one of the clock types below, we may miss that and
+    // break backward compatibility.
+#if !defined(__APPLE__) && HAVE_CLOCK_MONOTONIC_COARSE || HAVE_CLOCK_MONOTONIC
```
Comment (MSLaguana) [inline pal/src/misc/time.cpp]: Can you please put parens around this like `#if !define (__APPLE__) && (HAVE_CLOCK_MONOTONIC_COARSE || HAVE_CLOCK_MONOTONIC)` because I can never remember which boolean operators have stronger precedence.

**Comment by obastemur** [comment]
@MSLaguana do we track that issue?

File: pal/src/misc/time.cpp (hunk 1 above)
Comment (obastemur) [reply pal/src/misc/time.cpp]: 👍

**Comment by MSLaguana** [comment]
This is the first I heard about that test being flaky, but considering it succeeded on re-run it seems that's the case.

**Comment by obastemur** [comment]
@MSLaguana updated the PR, thanks for the review.
