### PR TITLE
xplat-intl: default to non intl compare for localeCompare

### LINKED ISSUE #4623: xplat-intl: localeCompare fails
```
"0".localeCompare("1") ==> 0

expected 1
```
looks like https://github.com/Microsoft/ChakraCore/blob/release/1.8/lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp#L1385 was the cause.

Sending the fix. /cc @dilijev @jackhorton we better default to non-intl behavior then a default number approach. If you know a similar case, please open an issue or send a PR.

### PR DESCRIPTION
**Pull request by obastemur**
Fixes #4623 

Also enabling a test case that only tests the interface.

### CODE REVIEW

File: lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp [hunk 1]
```diff
@@ -1381,8 +1381,11 @@ namespace Js
             // xplat-todo: Need to replace this with platform-agnostic API
             compareResult = CompareStringEx(givenLocale != nullptr ? givenLocale : defaultLocale, compareFlags, aLeft, size1, aRight, size2, NULL, NULL, 0);
 #else
-            // FIXME (doilij): when CompareStringEx is implemented in PlatformAgnostic, call that function here
-            compareResult = 2; // 2 means strings are equal (reasonable default)
+            compareResult = wcsncmp(aLeft, aRight, min(size1, size2));
+            if (compareResult == 0 && size1 != size2)
+            {
+                compareResult = size1 > size2 ? 1 : -1;
+            }
```
Comment (jackhorton) [inline lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp]: You have to add 2 to compareResult because CompareStringEx returns 0 on error, 1 for less, 2 for equal, and 3 for greater. The rest of the code below assumes this.

**Comment by jackhorton** [comment]
Also of note, this will be fixed even more once intl-icu merges back into master.

File: lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp (hunk 1 above)
Comment (obastemur) [reply lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp]: kept the impl. separate and added a comment to make the intention clear  -> `(once ICU interface supports this, keep the implementation below for non-icu!)`

**Comment by obastemur** [comment]
@jackhorton @dilijev Thanks for the review!

**Comment by rhuanjl** [comment]
@obastemur this doesn't seem to be working on xplat in 1.9 and master - I think it has broken CI (though it works on 1.8)

**Comment by obastemur** [comment]
The reason is the test baseline on release/1.9 doesn't match with spec. While spec says the result should be neg, zero, or positive, the baseline checks for a particular integer. Sending the PR
