### PR TITLE
Convert JavascriptString::EntryLocaleCompare to use LogicalStringCompare

### LINKED ISSUE #4841: Convert JavascriptString::EntryLocaleCompare to use PlatformAgnostic::UnicodeText::LogicalCompareString when Intl is not enabled

### LINKED ISSUE #4843: Convert PlatformAgnostic::UnicodeText::LogicalStringCompare to take explicit buffer lengths
These functions will fail if strings have embedded null characters.

### PR DESCRIPTION
**Pull request by msdimitrov**
Resolves #4841
Resolves #4843 

I didn't change the error message, since I'm not sure if a new error message should be added to `rterros.h` or throw the error from `GetLastError()` .

### CODE REVIEW

File: lib/Runtime/PlatformAgnostic/Platform/Windows/UnicodeText.cpp [hunk 1]
```diff
@@ -416,9 +416,19 @@ namespace PlatformAgnostic
...
+            if (ret == 0)
+            {
+                AssertMsg(FALSE, "GetUserDefaultLocaleName failed");
+                return -CSTR_EQUAL;
+            }
+
+            // CompareStringEx called with these flags is equivalent to calling StrCmpLogicalW
             // and we have the added advantage of not having to link with shlwapi.lib just for one function
-            int i = CompareStringW(LOCALE_USER_DEFAULT, NORM_IGNORECASE | SORT_DIGITSASNUMBERS, string1, -1, string2, -1);
+            int i = CompareStringEx(localeName, NORM_IGNORECASE | SORT_DIGITSASNUMBERS, string1, -1, string2, -1, NULL, NULL, 0);
```
Comment (jackhorton) [inline lib/Runtime/PlatformAgnostic/Platform/Windows/UnicodeText.cpp]: I believe you can pass either `""` or `nullptr` for the user default locale (not both -- one meant user default and the other meant invariant). That should make it so you don't have to call `GetUserDefaultLocaleName`.

File: lib/Runtime/Library/JavascriptString.cpp [hunk 2]
```diff
@@ -1358,30 +1360,21 @@ namespace Js
 #endif
 
         const char16* pThisStr = pThis->GetString();
-        int thisStrCount = pThis->GetLength();
-
         const char16* pThatStr = pThat->GetString();
-        int thatStrCount = pThat->GetLength();
+        
+        int result = UnicodeText::LogicalStringCompare(pThisStr, pThatStr);
```
Comment (jackhorton) [inline lib/Runtime/Library/JavascriptString.cpp]: Strings can have embedded nulls in JS, so we will need to change this API to pass in the actual length of each string, rather than assuming null termination (especially since GetString is not required to actually give back a null-terminated buffer -- that's what GetSz is for). Since we obviously don't have a test for this case, it would be great to add one!

File: test/Strings/compare.js [hunk 3]
```diff
@@ -9,10 +9,12 @@ var str1 = "abcd1234"
 var str2 = "1234567a"
 var str3 = "abcd12345"
 var str1a = "abcd1234"
+var str1null = "\0ab\0cd1234\0";
 
 assert.isTrue(str1.localeCompare(str1a) == 0);
+assert.isTrue(str1.localeCompare(str1null) == 0);
```
Comment (MSLaguana) [inline test/Strings/compare.js]: Seems like this is failing on non-ICU versions of chakracore, it seems that winglob doesn't ignore nulls in comparisons?

Comment (msdimitrov) [reply test/Strings/compare.js]: Correct. I'm currently changing the the function to take the length of the strings.

File: lib/Runtime/PlatformAgnostic/Platform/Common/UnicodeText.ICU.cpp [hunk 4]
```diff
@@ -266,9 +266,9 @@ namespace PlatformAgnostic
             return u_hasBinaryProperty(ch, UCHAR_ID_CONTINUE);
         }
 
-        int LogicalStringCompare(const char16* string1, const char16* string2)
+        int LogicalStringCompare(const char16* string1, int str1size, const char16* string2, int str2size)
         {
-            return PlatformAgnostic::UnicodeText::Internal::LogicalStringCompareImpl(string1, string2);
```
Comment (jackhorton) [inline lib/Runtime/PlatformAgnostic/Platform/Common/UnicodeText.ICU.cpp]: We may want to have this definition be `#ifndef _WIN32` like GetLegacyCharacterClassificationType above, since even when we are using ICU on Windows, this function is trying to emulate CompareStringEx. This isn't an issue you introduced but it would be nice to fix it while this code is being touched. If you want to fix this, you will have to move the LogicalStringCompare definition in Platform\Windows\UnicodeText.cpp as well so it gets compiled in on Windows.

File: lib/Runtime/PlatformAgnostic/Platform/Windows/UnicodeText.cpp [hunk 5]
```diff
@@ -414,11 +414,11 @@ namespace PlatformAgnostic
...
         }
 
-        int LogicalStringCompare(const char16* string1, const char16* string2)
+        int LogicalStringCompare(const char16* string1, int str1size, const char16* string2, int str2size)
         {
-            // CompareStringW called with these flags is equivalent to calling StrCmpLogicalW
+            // CompareStringEx called with these flags is equivalent to calling StrCmpLogicalW
             // and we have the added advantage of not having to link with shlwapi.lib just for one function
-            int i = CompareStringW(LOCALE_USER_DEFAULT, NORM_IGNORECASE | SORT_DIGITSASNUMBERS, string1, -1, string2, -1);
+            int i = CompareStringEx(LOCALE_NAME_INVARIANT, NORM_IGNORECASE | SORT_DIGITSASNUMBERS, string1, str1size, string2, str2size, NULL, NULL, 0);
```
Comment (jackhorton) [inline lib/Runtime/PlatformAgnostic/Platform/Windows/UnicodeText.cpp]: Same LOCALE_NAME_USER_DEFAULT as noted above.

File: lib/Runtime/PlatformAgnostic/Platform/Common/UnicodeText.Common.cpp [hunk 6]
```diff
@@ -67,11 +68,20 @@ namespace PlatformAgnostic
                     num = newNum;
 
                     str++;
+                    numLength++;
                 }
 
+                *len += numLength;
```
[the remark this answers is not in the document]
Comment (msdimitrov) [reply lib/Runtime/PlatformAgnostic/Platform/Common/UnicodeText.Common.cpp]: *len is accumulating because the string may contain other digits or characters before that, so `=` would just overwrite the value and would lead to unnecessary iterations overall.

**Comment by msdimitrov** [comment]
Sorry for taking so long. I squashed the commits, and I think I've fixed the issue you mentioned with the emulation of CompareStringEx on Windows ICU.

File: bin/NativeTests/UnicodeTextTests.cpp [hunk 7]
```diff
@@ -84,4 +102,10 @@ namespace UnicodeTextTest
         Test(_u("20sTRing"), _u("st2ring"), -1);
         Test(_u("st3rING"), _u("st2riNG"), 1);
     }
+
+    TEST_CASE("LogicalCompareString_EmbeddedNullCharacters", "[UnicodeText]")
+    {
+        TestNullCharacters(_u("\0\0ab\0\0c123def\0\0"), 15, _u("abc123def"), 9, 0);
```
Comment (jackhorton) [inline bin/NativeTests/UnicodeTextTests.cpp]: I am honestly surprised that these should compare equal -- I just checked firefox and they agree, but I would have thought "\0" would be less than "a" and thus left should be less than right, _or_ left should be greater than right since its longer. Good test case!

**Comment by jackhorton** [comment]
No worries on the delay, I have been busy doing infrastructure work so I probably wouldn't have seen any updates anyways. @dilijev or @MSLaguana want to take a look at this before I merge?

File: lib/Runtime/PlatformAgnostic/Platform/Common/UnicodeText.Common.cpp [hunk 8]
```diff
@@ -88,14 +98,18 @@ namespace PlatformAgnostic
...
             /// The algorithm treats the characters in a case-insensitive manner
             ///
-            int LogicalStringCompareImpl(const char16* p1, const char16* p2)
+            int LogicalStringCompareImpl(const char16* p1, int p1size, const char16* p2, int p2size)
             {
                 Assert(p1 != nullptr);
                 Assert(p2 != nullptr);
 
-                while (*p1 && *p2)
+                int str1size = 0;
```
Comment (MSLaguana) [inline lib/Runtime/PlatformAgnostic/Platform/Common/UnicodeText.Common.cpp]: I find this name slightly confusing, since I was expecting that the size parameter would be fixed. It looks like it is only used to make sure we don't walk past the end of the strings, would it make sense to instead compute something like `const char16* str1End = p1 + p1size, *str2End = p2 + p2Size` and then just check `p1 < str1End && p2 < str2End` in the loop condition? That way we also don't accidentally bump either pointer without bumping the length-so-far.

Comment (msdimitrov) [reply lib/Runtime/PlatformAgnostic/Platform/Common/UnicodeText.Common.cpp]: Completely agree with you. Thanks!

**Comment by dilijev** [comment]
Looking

File: lib/Runtime/PlatformAgnostic/Platform/Common/UnicodeText.Common.cpp [hunk 9]
```diff
@@ -170,6 +180,17 @@ namespace PlatformAgnostic
...
+                    while (isNull(*p1) && p1 < str1End)
+                    {
+                        p1++;
+                    }
+
+                    while (isNull(*p2) && p2 < str2End)
+                    {
+                        p2++;
+                    }
+
```
Comment (dilijev) [inline lib/Runtime/PlatformAgnostic/Platform/Common/UnicodeText.Common.cpp]: nit: extra blank line

**Comment by jackhorton** [comment]
@digitalinfinity this fix impacts --no-icu and Lite builds of ChakraCore. Should it stay in master or go to 1.10?

**Comment by dilijev** [comment]
I'd vote 1.10

**Comment by dilijev** [comment]
Marked as `External Contributor` as a reminder that a Chakra team member needs to adopt, test, and merge this change.
