### PR TITLE
Fixes #5993 - path to fromCodePoint in JIT now throws range error on large input

### LINKED ISSUE #5950: Assertion failure at lib/Backend/BackwardPass.cpp:2673
The debug build crashes due to assertion failure at lib/Backend/BackwardPass.cpp:2673

PoC:
```
(function () {                                                                     
    while (!(arguments !== arguments));                                            
})();
```

Commit: e055dbb
Build Option: None
OS: Ubuntu 18.04.1 LTS
Arch: x86_64

### LINKED ISSUE #5993: Assertion failure at lib/Common/Common/NumberUtilities_strtod.cpp:2725
The debug build crashes with assertion failure at lib/Common/Common/NumberUtilities_strtod.cpp:2725.
PoC:
```
var var_0 = new Array(1024);
for (var var_1 = 0; ; var_1 += 1024) {
  var_0[var_1] = String.fromCodePoint(var_1);
}
```
Commit: 39f9727
Build Option: None
OS: Ubuntu 18.04.1 LTS
Arch: x86_64

### PR DESCRIPTION
**Pull request by wyrichte**

### CODE REVIEW

File: lib/Runtime/Base/CharStringCache.cpp [hunk 1]
```diff
@@ -78,10 +78,19 @@ using namespace Js;
     {
         Assert(c >= 0x10000);
         CompileAssert(sizeof(char16) * 2 == sizeof(codepoint_t));
+
+		ScriptContext* scriptContext = JavascriptLibrary::FromCharStringCache(this)->GetScriptContext();
```
Comment (zenparsing) [inline lib/Runtime/Base/CharStringCache.cpp]: Nit: looks like some whitespace issues (maybe tabs instead of spaces?).

File: test/Strings/fromCodePoint.js [hunk 2]
```diff
@@ -0,0 +1,22 @@
+//-------------------------------------------------------------------------------------------------------
+// Copyright (C) Microsoft. All rights reserved.
+// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
+//-------------------------------------------------------------------------------------------------------
+
+function f()
```
Comment (zenparsing) [inline test/Strings/fromCodePoint.js]: Nit: for JS, we should probably stick with not having braces on new lines, because of ASI.
