### PR TITLE
Asm.js Math builtin cleanup

### LINKED ISSUE #3151: AsmJsByteCodeGenerator incorrect cast (potentially incorrect)
In lib\Runtime\Language\AsmJsByteCodeGenerator.cpp's AsmJSByteCodeGenerator::EmitCall, we do a c-cast of an AsmJsFunctionDeclaration to AsmJsMathFunction. This can potentially lead to incorrect (but not unsafe) behavior. The relevant code is below:

```c++
if (IsFRound((AsmJsMathFunction*)sym))
{
    expectedType = AsmJsRetType::Float;
}
```

Thanks to @Cellule and @MikeHolman for earlier review and analysis of the issue.

### PR DESCRIPTION
**Pull request by Cellule**
Fix bad cast to AsmJsMathFunction for Fround check, turns out the check was useless to begin with. Simply forced EmitMathBuiltin fround case to Float type.

All around cleanup of AsmJs MathBuiltin checks 

Fixes #3151

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/3154)

### CODE REVIEW

File: lib/Runtime/Language/AsmJsByteCodeGenerator.cpp [hunk 1]
```diff
@@ -1042,18 +1037,11 @@ namespace Js
             }
         }
 
-
-        if (IsFRound((AsmJsMathFunction*)sym))
```
Comment (Cellule) [inline lib/Runtime/Language/AsmJsByteCodeGenerator.cpp]: This was the potentially bad cast

File: lib/Runtime/Language/AsmJsByteCodeGenerator.cpp [hunk 2]
```diff
@@ -1934,45 +1921,43 @@ namespace Js
...
 
         // for fround, if we have a fround(NumericLiteral), we want to just emit Ld_Flt NumericLiteral
-        if (argCount == 1 && IsFRound(mathFunction) && ParserWrapper::IsFroundNumericLiteral(argNode))
+        if (argCount == 1 && isFRound && ParserWrapper::IsFroundNumericLiteral(argNode))
         {
-            Assert(expectedType == AsmJsRetType::Float);
             StartStatement(pnode);
             RegSlot dst = mFunction->AcquireTmpRegister<float>();
-            EmitExpressionInfo emitInfo(dst, expectedType.toType());
+            EmitExpressionInfo emitInfo(dst, AsmJsType::Float);
```
Comment (Cellule) [inline lib/Runtime/Language/AsmJsByteCodeGenerator.cpp]: This is the force to Float type in Fround case making the previous bad check useless

File: lib/Runtime/Language/AsmJsBuiltInNames.h [hunk 3]
```diff
@@ -38,45 +42,45 @@
...
+ASMJS_MATH_FUNC_NAMES(log,      log,    Math::EntryInfo::Log    )
+ASMJS_MATH_FUNC_NAMES(pow,      pow,    Math::EntryInfo::Pow    )
+ASMJS_MATH_FUNC_NAMES(sqrt,     sqrt,   Math::EntryInfo::Sqrt   )
+ASMJS_MATH_FUNC_NAMES(abs,      abs,    Math::EntryInfo::Abs    )
+ASMJS_MATH_FUNC_NAMES(atan2,    atan2,  Math::EntryInfo::Atan2  )
+ASMJS_MATH_FUNC_NAMES(imul,     imul,   Math::EntryInfo::Imul   )
+ASMJS_MATH_FUNC_NAMES(fround,   fround, Math::EntryInfo::Clz32  )
+ASMJS_MATH_FUNC_NAMES(min,      min,    Math::EntryInfo::Min    )
+ASMJS_MATH_FUNC_NAMES(max,      max,    Math::EntryInfo::Max    )
+ASMJS_MATH_FUNC_NAMES(clz32,    clz32,  Math::EntryInfo::Fround )
```
Comment (Penguinwizzard) [inline lib/Runtime/Language/AsmJsBuiltInNames.h]: Is this swapped with the line 3 above it?
