### PR TITLE
Fixed #5621 - toLocaleString now accesses object property

### LINKED ISSUE #5621: Array.toLocaleString should return typeof string instead string value
Hi everyone,

I find out an inconsistency in Array.toLocaleString when `typeof this` is called  the return is `test`. V8, SpiderMonkey and JavaScriptCore return `string` as expected. 

Chakra version: 1.10.2.0
O.S: MacOS High Sierra version 10.13.6

step to reproduce: 
```js
"use strict";

Object.defineProperty(String.prototype, "toLocaleString", {
    get() {
        return function() { return typeof this; };
    }
})

print(["test"].toLocaleString())
```
actual result: 
test

expected result:
string

cinfuzz

### PR DESCRIPTION
**Pull request by Dachande663**
As per issue https://github.com/Microsoft/ChakraCore/issues/5621, this PR enables toLocaleString to call JavascriptString underlying property.

### CODE REVIEW

**Comment by sethbrenith** [comment]
Thanks @Dachande663 . Would you mind also adding unit tests as part of this change? It looks like test/Array/toLocaleString.js would be an appropriate place. The test file basically just prints out text and the unit test runner compares the output text against the expected text in test/Array/toLocaleString.baseline. We should test at least these cases (feel free to add other relevant cases if you think of them):

* The case from #5621
* If we set `String.prototype.toLocaleString = undefined`, then `["test"].toLocaleString()` should throw a TypeError

File: lib/Runtime/Language/JavascriptConversion.cpp [hunk 1]
```diff
@@ -701,8 +701,16 @@ using namespace Js;
         case TypeIds_Number:
             return JavascriptNumber::ToLocaleString(JavascriptNumber::GetValue(aValue), scriptContext);
 
-        case TypeIds_String:
-            return UnsafeVarTo<JavascriptString>(aValue);
+        case TypeIds_String: {
```
Comment (sethbrenith) [inline lib/Runtime/Language/JavascriptConversion.cpp]: nit: we put opening `{` on the following line

Comment (sethbrenith) [inline lib/Runtime/Language/JavascriptConversion.cpp]: This seems very similar to the `default` case below. Why not just remove the `TypeIds_String` case?

File: lib/Runtime/Language/JavascriptConversion.cpp [hunk 2]
```diff
@@ -701,8 +701,16 @@ using namespace Js;
...
+            RecyclableObject* object = VarTo<RecyclableObject>(aValue);
+            Var value = JavascriptOperators::GetProperty(object, PropertyIds::toLocaleString, scriptContext, NULL);
+            RecyclableObject* toLocaleStringFunction = VarTo<RecyclableObject>(value);
```
Comment (sethbrenith) [inline lib/Runtime/Language/JavascriptConversion.cpp]: `VarTo<RecyclableObject>(value)` will crash the program if `value` is not a recyclable object (suppose maybe it's an int, for example).

**Comment by Dachande663** [comment]
@sethbrenith thanks for the feedback. I've removed the String case allowing it to fallback to default and also added in tests. I'm not sure what isolation the test runner uses in between scenarios so let me know if overloading the String prototype will have any adverse effects.

File: test/Array/toLocaleString.baseline [hunk 3]
```diff
@@ -43,3 +43,15 @@ TypeError : The value of the property 'toLocaleString' is not a Function object
...
 9. Array: toLocaleString should use length property
 10.00, 20.00, 30.00, , , 
+
+
+10. Array: toLocaleString should use toLocaleString accessor on element
+accessor-value
+
+
+11. Array: toLocaleString should throw TypeError on undefined
+TypeError : Cannot redefine non-configurable property 'toLocaleString'
```
Comment (sethbrenith) [inline test/Array/toLocaleString.baseline]: This is a TypeError but not the one I was hoping to trigger. This is happening in the `Object.defineProperty` step, because the previous scenario used `Object.defineProperty` also and didn't specify `configurable: true`, meaning the property can never be reconfigured again.

**Comment by sethbrenith** [comment]
The test runner runs each .js file in an entirely new process, so there's no risk of prototype modifications leaking to other tests. However, the scenarios within this test file don't have any enforced isolation; they're just to make the output look pretty. Ideally we should have each test scenario put things back the way they were, so that if somebody decides to reorder tests or add new ones on the end they wouldn't have any nasty surprises. Something like:

```javascript
var originalToLocaleString = String.prototype.toLocaleString;
guarded_call(function () {
    // test contents that might change prototypes...
});
String.prototype.toLocaleString = originalToLocaleString;
```

**Comment by Dachande663** [comment]
@sethbrenith roger. I've updated the test suite to actually do the tests needed and ensure state is returned afterwards. Cheers for taking the time to provide the comments, massively helpful.

**Comment by sethbrenith** [comment]
@dotnet-bot test Windows 10 x64_test please
