### PR TITLE
Fix #2949: Class const name binding incorrectly marked as module export storage

### LINKED ISSUE #2949: assertion "size > ScopeSlots::FirstSlotIndex" failure - modules with Promise.resolve
Run the following code:

[promiseVoidModule.zip](https://github.com/Microsoft/ChakraCore/files/988285/promiseVoidModule.zip)

Get this output:

script start
script after
ASSERTION 8052: (Repos\ChakraCore\lib\Runtime\Language\JavascriptOperators.cpp, line 6939) size > ScopeSlots::FirstSlotIndex
 Failure: (size > ScopeSlots::FirstSlotIndex)
FATAL ERROR: ch.exe failed due to exception code c0000420

### PR DESCRIPTION
**Pull request by tcare**
We were mistakenly marking both the class let and const decls as module export storage. This resulted in empty instantiated scopes and incorrect class behavior in some cases.

The fix is not to mark the const binding as module export storage, as it is visible to the inside of the class only.

Added some tests to verify the bindings of exported classes.

### CODE REVIEW

File: test/es6module/exportBinding.js [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+var A2Inst = new A2();
+export { A2 };
+
+assert.throws(function () { A2Inst.attemptBindingChange(); }, TypeError, 'Delay exported class name captured in class is const', "Assignment to const");
+assert.doesNotThrow(function () { A2 = 1; }, 'Delay exported class name decl binding is mutable outside class');
+assert.throws(function () { A2Inst.attemptBindingChange(); }, TypeError, 'Mutation of class decl did not change constness', "Assignment to const");
+assert.areEqual(true, A2Inst.bindingModified(), 'Captured class name observes mutation');
+assert.throws(function () { A2Inst.attemptBindingChange(); }, TypeError, 'Delay exported class name captured in class is still const', "Assignment to const");
+
+export let B1 = class B1 {
```
Comment (boingoing) [inline test/es6module/exportBinding.js]: I'd like one more set of these if you don't mind where the let binding name is different from the class expression name. `export let C1 = class NotC1 {` for example.

Comment (tcare) [reply test/es6module/exportBinding.js]: Done. Also fixed my conditional language which was inverted :)

**Comment by dilijev** [comment]
Should there be a test of what is/is not observable from the site where the module is loaded?
