### PR TITLE
Fixes #5576 - Chakra should not redeclare "undefined" keyword

### LINKED ISSUE #5576: Chakra should not redeclare "undefined" keyword
Hi everyone,
this is a inconsistency on Chakra that can declare global binding `undefined`.

OS: Ubuntu 16.04 x64
chakra: 1.10.1.0

steps to reproduce:
```js
function undefined () {print('Test failed')}
undefined()

'use strict'
function undefined () {print('Test failed')}
undefined()
```
Actual results:
Test failed
Test failed

Expected results:
SpiderMonkey: TypeError: Property must be configurable or both writable and enumerable (Early error)
V8: SyntaxError: Identifier 'undefined' has already been declared (Early Error)
JSC: TypeError: undefined is not a function. (In 'undefined()', 'undefined' is undefined)

The others engines throws an Error as expected. I'm not sure if this case should be a TypeError (jsc/sm) or a SyntaxError (V8) but the test cannot pass without failures.

cinfuzz

### PR DESCRIPTION
**Pull request by wyrichte**
Fixed by adding opcode OP_EnsureNoRootRedeclFunc that enforces the section of #sec-globaldeclarationinstantiation where #CanDeclareGlobalFunction is called. This enforces that when a global function that is not configurable, not writable, and not enumerable is overwritten a TypeError is thrown.

### CODE REVIEW

File: lib/Parser/perrors.h [hunk 1]
```diff
@@ -9,81 +9,81 @@
...
-LSC_ERROR_MSG( 1009, ERRnoRcurly      , "Expected '}'")
-LSC_ERROR_MSG( 1010, ERRnoIdent       , "Expected identifier")
-LSC_ERROR_MSG( 1011, ERRnoEq          , "Expected '='")
-LSC_ERROR_MSG( 1012, ERRnoSlash       , "Expected '/'")
-LSC_ERROR_MSG( 1013, ERRbadNumber     , "Invalid number")
-LSC_ERROR_MSG( 1014, ERRillegalChar   , "Invalid character")
-LSC_ERROR_MSG( 1015, ERRnoStrEnd      , "Unterminated string constant")
-LSC_ERROR_MSG( 1016, ERRnoCmtEnd      , "Unterminated comment")
-LSC_ERROR_MSG( 1017, ERRIdAfterLit    , "Unexpected identifier after numeric literal")
+LSC_ERROR_MSG(1004, ERRnoSemic, "Expected ';'")
```
Comment (dilijev) [inline lib/Parser/perrors.h]: nit: Can you revert the formatting changes that were made to this file?

File: test/GlobalFunctions/CanDeclareGlobalFunctionNonEval.baseline [hunk 2]
```diff
@@ -0,0 +1,2 @@
+TypeError: Redeclaring a global function that is not configurable, not writable, and not enumerable is not allowed.
+	at Global code (CanDeclareGlobalFunctionNonEval.js:1:1)
```
Comment (dilijev) [inline test/GlobalFunctions/CanDeclareGlobalFunctionNonEval.baseline]: Any chance we can get the name of the function to appear in the error message, or is that information not convenient to plumb through?

Comment (dilijev) [reply test/GlobalFunctions/CanDeclareGlobalFunctionNonEval.baseline]: Looks like there's no perrors.h cases with %s so I'd assume that's not supported and maybe the rterrors.h codes can't be used in this context?

I'm just thinking it would be a much better dev experience if the message they got said "Redeclaring global property 'undefined'" or some such. On that note, undefined is not actually a function, so is this error message a bit misleading? Does the clause generally apply to any property, function or otherwise, with the descriptor restrictions "not configurable, not writable, and not enumerable"?

File: lib/Runtime/Types/RecyclableObject.h [hunk 3]
```diff
@@ -313,6 +313,7 @@ namespace Js {
         virtual BOOL InitPropertyInEval(PropertyId propertyId, Var value, PropertyOperationFlags flags = PropertyOperation_None, PropertyValueInfo* info = NULL);
         virtual BOOL EnsureProperty(PropertyId propertyId);
         virtual BOOL EnsureNoRedeclProperty(PropertyId propertyId);
+        virtual BOOL EnsureNoRedeclFunc(PropertyId propertyId);
```
Comment (sethbrenith) [inline lib/Runtime/Types/RecyclableObject.h]: I see that you're following the pattern of EnsureNoRedeclProperty, but I don't think the pattern should necessarily apply, because EnsureNoRedeclProperty is used in a much bigger variety of ways.

* Why does it have a return value? As far as I can tell, the returned value is never used.
* Why is this virtual and defined on RecyclableObject? The only call site knows that the type will be RootObjectBase; can't we just cast directly to that and call a non-virtual method?
