### PR TITLE
fixes #5681 avoid c2440 error lose const qualifier

### LINKED ISSUE #5681: Chakra failed with error C2440 when build with permissive- by msvc on Windows
Chakra failed with error C2440 when build with permissive- by msvc on Windows, I use latest version a3737b0 on master branch. Could you please help take a look at this? Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior.

**You can repro this issue as the steps below:**

1. git clone -c core.autocrlf=true https://github.com/microsoft/ChakraCore D:\Chakra\src
2. open a clean x86 prompt (C:\windows\syswow64\cmd.exe) and browse to D:\Chakra\src
3. set _CL_=/d1ParseTrees:identErrors- /permissive-
4. msbuild /m /p:Platform=x86 /p:Configuration=Test /p:WindowsTargetPlatformVersion=10.0.17134.0 Build\Chakra.Core.sln /t:Rebuild

**Error info:**
d:\chakra\src\bin\nativetests\biguinttest.cpp(235): error C2440: '=': cannot convert from 'const char [11]' to 'char *'
d:\chakra\src\bin\nativetests\biguinttest.cpp(235): note: Conversion from string literal loses const qualifier (see /Zc:strictStrings)
d:\chakra\src\bin\nativetests\biguinttest.cpp(247): error C2440: '=': cannot convert from 'const char [11]' to 'char *'
d:\chakra\src\bin\nativetests\biguinttest.cpp(247): note: Conversion from string literal loses const qualifier (see /Zc:strictStrings)
d:\chakra\src\bin\nativetests\biguinttest.cpp(261): error C2440: '=': cannot convert from 'const char [21]' to 'char *' d:\chakra\src\bin\nativetests\biguinttest.cpp(261): note: Conversion from string literal loses const qualifier (see /Zc:strictStrings)

### PR DESCRIPTION
**Pull request by duongnhn**
When /Zc:strictStrings is enable, encounter this error https://msdn.microsoft.com/en-us/library/dn449508.aspx since we cast literal string to non-const char pointer.

### CODE REVIEW

File: bin/NativeTests/BigUIntTest.cpp [hunk 1]
```diff
@@ -226,13 +226,12 @@ namespace BigUIntTest
     TEST_CASE("Init_From_Char_Of_Digits", "[BigUIntTest]")
     {
         BigUInt biDec;
-        char *charDigit;
```
Comment (jackhorton) [inline bin/NativeTests/BigUIntTest.cpp]: For what its worth, you could change this to just be `const char *charDigits` rather than redeclaring it in each block. `const char *charDigits` is ~equivalent to `char const *charDigits`, which makes it clearer when read right-to-left: "a pointer to a constant character". You would only have to redeclare charDigits in each block if it was `char const * const`, which is a constant pointer to a constant character (thus, you cant reassign the pointer). See https://godbolt.org/z/d3dAYe

Comment (duongnhn) [reply bin/NativeTests/BigUIntTest.cpp]: Great info! Thanks Jack!

---
In reply to: [216410613](https://github.com/Microsoft/ChakraCore/pull/5682#discussion_r216410613) [](ancestors = 216410613)
