### PR TITLE
Fix enumeration of proxy properties containing null characters

### LINKED ISSUE #5492: proxy property enumeration can skip items
This code should print both properties but only prints one:

```javascript
const blah = {"\0":"hi","\0\0":"hello"};
for (var i in new Proxy(blah, {})) console.log(blah[i]);
```

This is because JavascriptProxy::ProxyOwnkeysEnumerator::MoveAndGetNext is using a hash set of null-terminated strings, so it doesn't handle embedded nulls correctly. Most places we use CharacterBuffer or similar to do string hashing and comparisons correctly.

### PR DESCRIPTION
**Pull request by mcduke**
This fixes #5492.

### CODE REVIEW

File: lib/Runtime/Library/JavascriptProxy.cpp [hunk 1]
```diff
@@ -1029,10 +1029,11 @@ namespace Js
                             // let desc = Reflect.getOwnPropertyDescriptor(obj, key);
                             Js::PropertyDescriptor desc;
                             BOOL ret = JavascriptOperators::GetOwnPropertyDescriptor(proxy, propertyName, scriptContext, &desc);
+                            const JsUtil::CharacterBuffer<WCHAR> propertyString = JsUtil::CharacterBuffer<WCHAR>(propertyName->GetString(), propertyName->GetLength());
```
Comment (sethbrenith) [inline lib/Runtime/Library/JavascriptProxy.cpp]: Nit: this can be shortened a bit, like so:

```c++
const JsUtil::CharacterBuffer<WCHAR> propertyString(propertyName->GetString(), propertyName->GetLength());
```

Comment (mcduke) [reply lib/Runtime/Library/JavascriptProxy.cpp]: Thanks for the feedback, learned about another C++ feature. I've incorporated your suggested change and amended my pull request.
