### PR TITLE
xplat: Debugger Support

### LINKED ISSUE #2058: xplat: ChakraDebug API missing from OSx build
Building ChakraCore on OSx 10.12.1 from master with latest using

``` bash
./build.sh --icu=/usr/local/opt/icu4c/include -j=4
```

When running ```nm -g libChakraCore.dylib``` on the resulting library, I see the JsTDDxxx symbols exported but not methods such as JsDiagStartDebugging as found on the Windows API.

Is there a way to start debugging on OSx?

OSx Symbols from libChakraCore.dylib:

```
0000000000053240 T _JsAddRef
0000000000054330 T _JsBoolToBoolean
00000000000545c0 T _JsBooleanToBool
000000000005cf40 T _JsCallFunction
0000000000052fb0 T _JsCollectGarbage
000000000005d4c0 T _JsConstructObject
0000000000054630 T _JsConvertValueToBoolean
0000000000054d60 T _JsConvertValueToNumber
0000000000056080 T _JsConvertValueToObject
0000000000055560 T _JsConvertValueToString
0000000000065310 T _JsCopyPropertyIdUtf8
0000000000064960 T _JsCopyString
0000000000064a30 T _JsCopyStringUtf16
0000000000064af0 T _JsCopyStringUtf8
0000000000059660 T _JsCreateArray
0000000000059910 T _JsCreateArrayBuffer
0000000000053a30 T _JsCreateContext
000000000005a410 T _JsCreateDataView
000000000005e160 T _JsCreateError
0000000000059c50 T _JsCreateExternalArrayBuffer
0000000000055c50 T _JsCreateExternalObject
000000000005d9b0 T _JsCreateFunction
000000000005dd20 T _JsCreateNamedFunction
00000000000559c0 T _JsCreateObject
0000000000065250 T _JsCreatePropertyIdUtf8
000000000005e530 T _JsCreateRangeError
000000000005e900 T _JsCreateReferenceError
0000000000052f40 T _JsCreateRuntime
00000000000646b0 T _JsCreateString
0000000000064940 T _JsCreateStringUtf16
0000000000064880 T _JsCreateStringUtf8
000000000005aa80 T _JsCreateSymbol
000000000005ecd0 T _JsCreateSyntaxError
000000000005f0a0 T _JsCreateTypeError
0000000000059f30 T _JsCreateTypedArray
000000000005f470 T _JsCreateURIError
00000000000591b0 T _JsDefineProperty
000000000005ba80 T _JsDeleteIndexedProperty
0000000000058da0 T _JsDeleteProperty
0000000000060010 T _JsDisableRuntimeExecution
0000000000052fe0 T _JsDisposeRuntime
0000000000054c00 T _JsDoubleToNumber
0000000000060080 T _JsEnableRuntimeExecution
000000000005c660 T _JsEquals
000000000005f8e0 T _JsGetAndClearException
000000000005a860 T _JsGetArrayBufferStorage
0000000000053e40 T _JsGetContextData
0000000000053df0 T _JsGetContextOfObject
0000000000053bb0 T _JsGetCurrentContext
000000000005aa10 T _JsGetDataViewStorage
0000000000056fc0 T _JsGetExtensionAllowed
000000000005ce90 T _JsGetExternalData
0000000000054260 T _JsGetFalseValue
0000000000055900 T _JsGetGlobalObject
000000000005c3a0 T _JsGetIndexedPropertiesExternalData
000000000005b1d0 T _JsGetIndexedProperty
00000000000540c0 T _JsGetNullValue
00000000000579d0 T _JsGetOwnPropertyDescriptor
0000000000057e30 T _JsGetOwnPropertyNames
00000000000581e0 T _JsGetOwnPropertySymbols
00000000000575e0 T _JsGetProperty
00000000000602e0 T _JsGetPropertyIdFromName
0000000000060530 T _JsGetPropertyIdFromSymbol
0000000000060a90 T _JsGetPropertyIdType
0000000000060a50 T _JsGetPropertyNameFromId
0000000000056420 T _JsGetPrototype
0000000000060ab0 T _JsGetRuntime
000000000005fe60 T _JsGetRuntimeMemoryLimit
000000000005fdd0 T _JsGetRuntimeMemoryUsage
0000000000055100 T _JsGetStringLength
0000000000060810 T _JsGetSymbolFromPropertyId
0000000000054190 T _JsGetTrueValue
000000000005a760 T _JsGetTypedArrayInfo
000000000005a8e0 T _JsGetTypedArrayStorage
0000000000053ff0 T _JsGetUndefinedValue
0000000000054a40 T _JsGetValueType
000000000005f840 T _JsHasException
000000000005ce60 T _JsHasExternalData
000000000005c2e0 T _JsHasIndexedPropertiesExternalData
000000000005ae30 T _JsHasIndexedProperty
00000000000589d0 T _JsHasProperty
0000000000060b00 T _JsIdle
0000000000056bb0 T _JsInstanceOf
0000000000054c60 T _JsIntToNumber
0000000000060290 T _JsIsRuntimeExecutionDisabled
0000000000054c90 T _JsNumberToDouble
0000000000054cf0 T _JsNumberToInt
0000000000064e50 T _JsParse
0000000000065520 T _JsParseSerialized
0000000000055150 T _JsPointerToString
00000000000572e0 T _JsPreventExtension
0000000000053530 T _JsRelease
0000000000065050 T _JsRun
0000000000065660 T _JsRunSerialized
0000000000065450 T _JsSerialize
0000000000062060 T _JsSerializeScript
0000000000053e80 T _JsSetContextData
0000000000053be0 T _JsSetCurrentContext
000000000005fa40 T _JsSetException
000000000005cef0 T _JsSetExternalData
000000000005bdf0 T _JsSetIndexedPropertiesToExternalData
000000000005b610 T _JsSetIndexedProperty
0000000000053820 T _JsSetObjectBeforeCollectCallback
0000000000060d60 T _JsSetPromiseContinuationCallback
0000000000058580 T _JsSetProperty
00000000000567c0 T _JsSetPrototype
000000000005ff10 T _JsSetRuntimeBeforeCollectCallback
000000000005feb0 T _JsSetRuntimeMemoryAllocationCallback
000000000005fe20 T _JsSetRuntimeMemoryLimit
000000000005ca60 T _JsStrictEquals
0000000000055420 T _JsStringToPointer
0000000000063d30 T _JsTTDCheckAndAssertIfTTDRunning
00000000000621a0 T _JsTTDCreateContext
00000000000620b0 T _JsTTDCreateRecordRuntime
0000000000062130 T _JsTTDCreateReplayRuntime
00000000000626c0 T _JsTTDEmitRecording
0000000000063e90 T _JsTTDGetPreviousSnapshotInterval
0000000000063e30 T _JsTTDGetSnapShotBoundInterval
0000000000063d70 T _JsTTDGetSnapTimeTopLevelEventMove
0000000000062bd0 T _JsTTDHostExit
0000000000064250 T _JsTTDMoveToTopLevelEvent
0000000000062320 T _JsTTDNotifyContextDestroy
00000000000629c0 T _JsTTDNotifyYield
0000000000062840 T _JsTTDPauseTimeTravelBeforeRuntimeOperation
00000000000640b0 T _JsTTDPreExecuteSnapShotInterval
0000000000063520 T _JsTTDRawBufferAsyncModificationRegister
00000000000639a0 T _JsTTDRawBufferAsyncModifyComplete
0000000000062eb0 T _JsTTDRawBufferCopySyncIndirect
0000000000063200 T _JsTTDRawBufferModifySyncIndirect
0000000000062900 T _JsTTDReStartTimeTravelAfterRuntimeOperation
0000000000064300 T _JsTTDReplayExecution
0000000000062360 T _JsTTDStart
0000000000062510 T _JsTTDStop
```

### PR DESCRIPTION
**Pull request by obastemur**
In addition to Debugger support, this PR also brings the required base for compiling code with script profiler.

Fixes #2058

### CODE REVIEW

File: test/Debugger/MultipleContextStack.js [hunk 1]
```diff
@@ -21,8 +21,8 @@ var script1 = WScript.LoadScript("\
   function Script1Func3() { scriptFunc3(); } \
   function setFunc2(func) { scriptFunc2 = func; } \
   function setFunc3(func) { scriptFunc3 = func; }",
-  "samethread", "Script1.js");
```
Comment (agarwal-sandeep) [inline test/Debugger/MultipleContextStack.js]: >"Script1.js" [](start = 16, length = 12)

Why remove this?

File: lib/Runtime/Base/ScriptContext.cpp [hunk 2]
```diff
@@ -3060,13 +3060,43 @@ namespace Js
 
         if (!attach)
         {
+#ifdef ENABLE_SCRIPT_PROFILING
             this->UnRegisterDebugThunk();
```
Comment (agarwal-sandeep) [inline lib/Runtime/Base/ScriptContext.cpp]: >this->UnRegisterDebugThunk(); [](start = 12, length = 29)

This is used in debugging as well. Why are we restricting it for profiling?

File: lib/Runtime/Base/ScriptContext.cpp [hunk 3]
```diff
@@ -3125,11 +3157,12 @@ namespace Js
             return hr;
         }
 
+#if defined(ENABLE_SCRIPT_PROFILING)
         if (attach)
         {
             this->RegisterDebugThunk();
```
Comment (agarwal-sandeep) [inline lib/Runtime/Base/ScriptContext.cpp]: >RegisterDebugThunk [](start = 18, length = 18)

We use ProfileThunk under debugger and its set in this function, if we are not calling this where are we setting the thunk?

File: test/Debugger/MultipleContextStack.js (hunk 1 above)
Comment (obastemur) [inline test/Debugger/MultipleContextStack.js]: When file name is given, LoadScript is trying to find the full path on xplat and that fails

Comment (obastemur) [inline test/Debugger/MultipleContextStack.js]: Not necessarily. The comment there says; `// No fileName provided (WScript.LoadScript()), use dummy "script.js"` IMHO the intention there is clean. This particular script file doesn't do that

File: test/Debugger/rlexe.xml [hunk 4]
```diff
@@ -16,6 +16,8 @@
     <default>
       <compile-flags>-debuglaunch -dbgbaseline:JsDiagGetFunctionPosition.js.dbg.baseline</compile-flags>
       <files>JsDiagGetFunctionPosition.js</files>
+      <!-- xplat-todo: enable back [not supported] -->
```
Comment (agarwal-sandeep) [inline test/Debugger/rlexe.xml]: >not supported [](start = 36, length = 13)

Why? JsDiagGetFunctionPosition doesn't seems to have any xplat specific code? and it is used in node-chakracore debugging which seems to be working fine on xplat.

File: test/Debugger/MultipleContextStack.js (hunk 1 above)
Comment (agarwal-sandeep) [inline test/Debugger/MultipleContextStack.js]: In debugging it makes a difference as when giving the source we will give Unknown script, you can try that by using debugger annotation dumpSourceList().

File: test/Debugger/rlexe.xml (hunk 4 above)
Comment (obastemur) [inline test/Debugger/rlexe.xml]: > Why? JsDiagGetFunctionPosition doesn't seems to have any xplat specific code? and it is used in node-chakracore debugging which seems to be working fine on xplat.

@agarwal-sandeep  `Intl` is not enabled on xplat.

File: test/Debugger/MultipleContextStack.js (hunk 1 above)
Comment (obastemur) [inline test/Debugger/MultipleContextStack.js]: Make sense however, for this particular test, it doesn't make any difference. Opening a GH issue to track this instead.

**Comment by obastemur** [comment]
@agarwal-sandeep ping

File: lib/Common/BackendApi.h [hunk 5]
```diff
@@ -19,7 +19,7 @@
 #define ProfileEntryThunk Js::ScriptContext::DebugProfileProbeThunk
 
 #define DefaultDeferredParsingThunk Js::JavascriptFunction::DeferredParsingThunk
-#ifdef ENABLE_SCRIPT_PROFILING
+#if defined(ENABLE_SCRIPT_PROFILING) || defined(ENABLE_SCRIPT_DEBUGGING)
 #define ProfileDeferredParsingThunk Js::ScriptContext::ProfileModeDeferredParsingThunk
```
Comment (agarwal-sandeep) [inline lib/Common/BackendApi.h]: I don't think we use ProfileDeferredParsingThunk in debugging.

File: lib/Runtime/Base/Utf8SourceInfo.cpp [hunk 6]
```diff
@@ -414,9 +414,11 @@ namespace Js
...
         if (this->HasDebugDocument() && this->GetDebugDocument()->HasDocumentText())
         {
+#ifdef _WIN32
             // ToDo (SaAgarwa): Fix for JsRT debugging
             IDebugDocumentText *documentText = static_cast<IDebugDocumentText *>(this->GetDebugDocument()->GetDocumentText());
             if (documentText->GetName(DOCUMENTNAMETYPE_URL, sourceName) == S_OK)
+#endif
             {
                 return true;
             }
```
Comment (agarwal-sandeep) [inline lib/Runtime/Base/Utf8SourceInfo.cpp]: Whole if should be under #ifdef _WN32, we don't want to retrun true without setting sourceName. and in JsRT there is no sourceName support.

File: lib/Runtime/Base/ScriptContext.cpp [hunk 7]
```diff
@@ -3814,11 +3848,15 @@ namespace Js
...
                     __try
+#endif
                     {
                         aReturn = JavascriptFunction::CallFunction<true>(function, origEntryPoint, args);
                     }
+#ifndef DISABLE_SEH
                     __finally
+#endif
                     {
                         threadContext->GetDebugManager()->GetDebuggingFlags()->SetIsBuiltInWrapperPresent(isOrigWrapperPresent);
```
Comment (agarwal-sandeep) [inline lib/Runtime/Base/ScriptContext.cpp]: >threadContext->GetDebugManager()->GetDebuggingFlags()->SetIsBuiltInWrapperPresent(isOrigWrapperPresent); [](start = 24, length = 104)

How will this work with DISABLE_SEH?

**Comment by agarwal-sandeep** [comment]
Have we run crawler and exprgen with this change? We should do private testing before checking in this change.

**Comment by obastemur** [comment]
> Have we run crawler and exprgen with this change? We should do private testing before checking in this change.

@agarwal-sandeep I tried not to change anything for non xplat. Could you please point out the places might affect Windows?

File: lib/Common/BackendApi.h (hunk 5 above)
Comment (obastemur) [inline lib/Common/BackendApi.h]: Right, the method itself doesn't receive any call but I've fixed it's impl. for xplat instead of adding even more ifdef checks etc.

File: lib/Runtime/Base/ScriptContext.cpp (hunk 7 above)
Comment (agarwal-sandeep) [inline lib/Runtime/Base/ScriptContext.cpp]: I mean if we don't have try finally and CallFunction throws how will we make sure SetIsBuiltInWrapperPresent is restored?

**Comment by agarwal-sandeep** [comment]
I understand the sentiment that we haven't touched the code for windows but testing a change before it goes in doesn't harm. plus we have a single click test system at http://onecirro/ where you just provide a private and it does the rest.

File: lib/Runtime/Base/ScriptContext.cpp (hunk 7 above)
Comment (obastemur) [inline lib/Runtime/Base/ScriptContext.cpp]: If it throws something that requires SEH in place, we can't restore on xplat.

Comment (jianchun) [inline lib/Runtime/Base/ScriptContext.cpp]: Please change these `__try/__finally` to use `TryFinally` function https://github.com/Microsoft/ChakraCore/blob/master/lib/Common/CommonPal.h#L603.

File: bin/ch/jstoc.py [hunk 8]
```diff
@@ -0,0 +1,60 @@
...
+# Copyright (C) Microsoft. All rights reserved.
+# Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
+#-------------------------------------------------------------------------------------------------------
+
+from __future__ import with_statement # py 2.5
+import sys
+import os
+
+def print_usage():
+    print "usage: jstoc.py <js file path> <variable name>"
```
Comment (ThomsonTan) [inline bin/ch/jstoc.py]: >usage: jstoc.py [](start = 11, length = 15)

Output some more help message about what this script does?

File: lib/Runtime/Base/ScriptContext.cpp (hunk 7 above)
Comment (obastemur) [inline lib/Runtime/Base/ScriptContext.cpp]: @jianchun That PAL interface is subject to be removal. No libunwind / seh etc..

**Comment by obastemur** [comment]
Also tested with full project. Test/Debug ..

File: lib/Runtime/Base/ScriptContext.cpp (hunk 7 above)
Comment (jianchun) [inline lib/Runtime/Base/ScriptContext.cpp]: @obastemur The `TryFinally` function I mentioned has nothing to do with `libunwind / seh`, and why "subject to removal"?

**Comment by Oceanswave** [comment]
ping

File: lib/Runtime/Base/ScriptContext.cpp (hunk 7 above)
Comment (jianchun) [inline lib/Runtime/Base/ScriptContext.cpp]: @obastemur This was the `TryFinally` comment not addressed.

Comment (obastemur) [inline lib/Runtime/Base/ScriptContext.cpp]: Nevermind; I was referring to something totally unrelated and this one is update to one we have in CommonPAL

**Comment by obastemur** [comment]
@agarwal-sandeep I got the Crawler result and looks like that one is also good.

**Comment by obastemur** [comment]
ping @jianchun @agarwal-sandeep

File: lib/Runtime/Base/ScriptContext.cpp [hunk 9]
```diff
@@ -3803,11 +3834,12 @@ namespace Js
 
             scriptContext->GetThreadContext()->SetIsProfilingUserCode(isUserCode); // Update IsProfilingUserCode state
         }
+#endif // ENABLE_SCRIPT_PROFILING
 
         Var aReturn = NULL;
         JavascriptMethod origEntryPoint = function->GetFunctionInfo()->GetOriginalEntryPoint();
 
-        __try
+        __TRY_FINALLY_BEGIN // SEH is not guaranteed, see the implementation
```
Comment (obastemur) [inline lib/Runtime/Base/ScriptContext.cpp]: @agarwal-sandeep thanks for the test case, added under the DebuggerCommon. Testing on CI now, lets see how Windows testing is going to react to my baseline file line-endings

Comment (obastemur) [inline lib/Runtime/Base/ScriptContext.cpp]: @jianchun I also didn't observe any SEH specific code. 

2 things I've been trying to to with this PR; 1) do not update any Windows specific code unless it is a bug etc. 2) generally update TRY/FINALLY code to macro.

The second one was out of the scope and we hadn't reach to a consensus there. Updating this implementation very close to original while adding a notice. In case, in the future, if someone expects this part of the code handling SEH, the comment above should be enough to keep the intentions away. In the meantime, adding a macro for future use.

Comment (obastemur) [inline lib/Runtime/Base/ScriptContext.cpp]: @agarwal-sandeep checked other tests we have and saw `returnedvaluetests1` is actually doing the same. No reason to introduce this extra test ?

Comment (jianchun) [inline lib/Runtime/Base/ScriptContext.cpp]: OK, no more issues from me. I haven't reviewed other part, assuming @agarwal-sandeep did.

**Comment by agarwal-sandeep** [comment]
@obastemur @Jianchun I have reviewed debugger specific changes and they look good to me

**Comment by obastemur** [comment]
@agarwal-sandeep @jianchun @ThomsonTan Thanks for the reviews. 

@Oceanswave Thanks for opening the issue and follow ups!

**Comment by Oceanswave** [comment]
@obastemur thank _you_ for the hard work and sticking through. Greatly appreciate the effort.
