### PR TITLE
remove stale entry from sourceinfo after asm.js parse failure

### LINKED ISSUE #5942: Assertion Failure at lib/Runtime/Base/Utf8SourceInfo.h:61
Debug build of ChakraCore crashes due to assertion failure at lib/Runtime/./Base/Utf8SourceInfo.h:61.

PoC:
```
function func_0() {                                                                
    'use asm';                                                                     
}                                                                                  
WScript.Attach(func_0);
```
Build Option: None
OS: Ubuntu 18.04.1 LTS
Arch: x86_64

### PR DESCRIPTION
**Pull request by MikeHolman**
Fixes #5942

### CODE REVIEW

File: test/DebuggerCommon/failedasm.js.dbg.baseline [hunk 1]
```diff
@@ -0,0 +1 @@
+[]
```
Comment (akroshg) [inline test/DebuggerCommon/failedasm.js.dbg.baseline]: you can use debuggercommon\emptyJson.dbg.baseline (which was added for this purpose only)
