### PR TITLE
Make Date.parse recognize padded and negative years (Fixes #4178)

### LINKED ISSUE #4178: Date.parse should be able to parse output of Date.toString, Date.toUTCString, Date.toISOString
As reported by @xiaoyinl in #4067:

> [Sec 20.3.3.2](https://tc39.github.io/ecma262/#sec-date.parse) requires `Date.parse` should be able to parse the values returned by `Date.toString()`, `Date.toUTCString()` and `Date.toISOString()` in each engine's own implementation. In ChakraCore, if the year is <100, `toString()` and `toUTCString()` don't pad the year to 4 digits, and thus `Date.parse` can't parse them.

Partially addressed in #4067

### LINKED ISSUE #4300: Re-enable tests in DateParse2.js
In #4067, we've changed the format of Date.toUTCDate for negative years. After this change, some tests in DateParse2.js fail because `Date.parse()` isn't able to parse negative years in some cases, so these failing tests are disabled in #4067. They should be re-enabled (uncommented) after #4178 is fixed.

Ref: https://github.com/Microsoft/ChakraCore/pull/4067#issuecomment-346196337

### PR DESCRIPTION
**Pull request by xiaoyinl**
This PR will finally make `Date.parse` able to parse any output of `Date.toString()`, `Date.toUTCString`, and `Date.toISOString()`.

Fixes #4178 
Fixes #4300

Todo:
  - [x] Add, update and re-enable tests (#4300)
  - [x] `new Date("2017-jan-01")` causes an assertion failure

### CODE REVIEW

**Comment by xiaoyinl** [comment]
v8 and SpiderMonkey have the same issue. I've reported to them as well.
v8: https://bugs.chromium.org/p/v8/issues/detail?id=7117
sm: https://bugzilla.mozilla.org/show_bug.cgi?id=1420028

**Comment by xiaoyinl** [comment]
Some tests failed on Ubuntu. That's because `toString()` outputs [Local Mean Time](https://en.wikipedia.org/wiki/Local_mean_time), like `'Fri Oct 12 0001 21:23:35 GMT-0752 (LMT)'`, when the date is before the standard time zone was introduced in that city. The problem is that the displayed time zone `GMT-0752` is inaccurate. The actual time zone is GMT-07:52:58, which is used to calculate the local time `21:23:35`. Thus when parsing this string, there's a 58 second discrepancy. It seems the spec assumes that time zone is always a whole minute.

**Comment by dilijev** [comment]
Re: xplat test failures, in the short term you could split the test into two separate test files, move the cases that have xplat failures into the second file, and tag the one with xplat failures `exclude_xplat`.

2: we cannot violate this part of the spec. I think that behavior will be depended on much more readily than 1.

1: Can we manipulate the value returned by LMT so that those values are consistent? Since the actual time and time zone might be implementation-defined (down to the minute so that we can follow all of the spec rules) making sure that we don't have a discrepancy in the number of seconds would solve our problems.

/cc @obastemur

**Comment by obastemur** [comment]
Please disable the neg. year tests on xplat. TLDR; I had initially implemented with BC support on Linux (bunch of tricks involved) but wasn't enough for OSX (different system / different source of random tz data for **years with no actual tz**).

**Comment by dilijev** [comment]
Yes we probably can't have xplat tests for negative years which exactly match on all platforms for the reasons stated above, however we can test that our implementation is spec-compliant on points (1) which is already tested by most tests, and (2) by testing equivalence of those two operations, rather than their actual values.

**Comment by xiaoyinl** [comment]
@dilijev @obastemur Sorry for the long delay! I was kind of busy in the last month.

I just pushed some commits which, I think, have fixed the remaining issues. I split the tests into two files (`toString()` vs `toUTCString()` and `toISOString()`). The former depends on time zone, so it has `exclude_xplat` set, while the latter should pass on all platforms.

To test the potential impact on performance (mentioned in #4300), I use the following benchmark code:
```
let arr_datestring = [];
for (let d = Date.parse("1000-01-01T01:02:03Z"); d < Date.parse("2017-11-27T10:11:12Z"); d += 1000 * 60 * 60 * 4) {
    arr_datestring.push((new Date(d)).toString());
    arr_datestring.push((new Date(d)).toUTCString());
}
let len = arr_datestring.length;
let result = 0;
let start = Date.now();
for (let i = 0; i < len; i++) {
    result = (result + Date.parse(arr_datestring[i])) % 12345;
}
let perf = Date.now() - start;
console.log("result: " + result + ". Time: " + perf + " ms");
```

The result for current `release/1.8` branch is:
```
result: 3975. Time: 4213 ms
result: 3975. Time: 4264 ms
result: 3975. Time: 4287 ms
```
The result for `DateParse_zero_padded_years` branch (this PR) is:
```
result: 3975. Time: 4198 ms
result: 3975. Time: 4075 ms
result: 3975. Time: 4087 ms
```
It seems it even gets slightly faster, so I think probably the runtime cost for this fix is negligible.

I will squash the commits if it looks good to you.

File: lib/Runtime/Library/DateImplementation.cpp [hunk 1]
```diff
@@ -1067,6 +1066,8 @@ namespace Js {
         int tAmPm = 0;
         int tBcAd = 0;
 
+        size_t numOfDigits = 0;
+
```
Comment (obastemur) [inline lib/Runtime/Library/DateImplementation.cpp]: nit: while you are squashing, you might remove this space here

File: lib/Runtime/Library/DateImplementation.cpp [hunk 2]
```diff
@@ -1235,6 +1237,12 @@ namespace Js {
                             goto LError;
                         }
                         lwMonth = pszs->lwVal;
+                        if ('-' == *pch)
```
Comment (obastemur) [inline lib/Runtime/Library/DateImplementation.cpp]: can we have a totally bogus test of `-` is being the last character? i.e. `Wed, 11 Oct-"

**Comment by xiaoyinl** [comment]
@dilijev @obastemur Thanks for the review! I have added the tests you mentioned, and commits are squashed.

**Comment by dilijev** [comment]
Testing internally before merging.
