### PR TITLE
avoid Fatal OOM when script execution disabled (interrupted)

### LINKED ISSUE #4454: Chakra terminates process under stress
Below please find code that crashes the process when attempting to terminate the execution of scripts. This is a real scenario for a service that we are building. 

```c#
using System;
using System.Threading.Tasks;
using System.Threading;
using ChakraHost.Hosting;
using System.Collections.Concurrent;

namespace ChakraStress
{
    class Program
    {
        static void Main(string[] args)
        {
            ThreadPool.SetMinThreads(30, 30);
            int stressThreadCount = 10;

            for (var i = 0; i < stressThreadCount; i++)
            {
                (new Thread(new ThreadStart(StressThread))).Start();
            }

            Thread.Sleep(int.MaxValue);
        }

        private async static void StressThread()
        {
            int MAX_EXECUTION_TIME_MS = 10;

            using (var startedSignal = new AutoResetEvent(false))
            using (var completedSignal = new AutoResetEvent(false))
            {
                while (true)
                {
                    var runtime = JavaScriptRuntime.Create(JavaScriptRuntimeAttributes.AllowScriptInterrupt, JavaScriptRuntimeVersion.Version11, null);
                    runtime.MemoryLimit = (UIntPtr)6400000;
                    var context = runtime.CreateContext();

                    var task = Task<string>.Run(() =>
                    {
                        using (new JavaScriptContext.Scope(context))
                        {
                            startedSignal.Set();
                            try
                            {
                                JavaScriptContext.RunScript("while(1);");
                            }
                            catch
                            {
                            }
                        }
                        completedSignal.Set();
                    });

                    startedSignal.WaitOne(100000);

                    if (await Task.WhenAny(task, Task.Delay(MAX_EXECUTION_TIME_MS)) != task)
                    {
                        runtime.Disabled = true;

                        if (!completedSignal.WaitOne(1000000))
                        {
                            Console.WriteLine("No signal");
                        }
                        else
                        {
                            //runtime.Disabled = false;
                            Console.Write(".");
                        }
                    }
                    else
                    {
                        Console.Write("r");
                    }

                    runtime.Dispose();
                }
            }
        }
    }
}

````
[ChakraStress.zip](https://github.com/Microsoft/ChakraCore/files/1585031/ChakraStress.zip)

### PR DESCRIPTION
**Pull request by jianchun**
Parser was returning ErrnoMemory when script execution disabled /
interrupted. This triggers Fatal OOM in Jsrt (when
`JsDisableRuntimeExecution()` was called).

Changed to return either E_ABORT or VBSERR_OutOfStack.

Fix #4454

### CODE REVIEW

File: lib/Jsrt/Jsrt.cpp [hunk 1]
```diff
@@ -869,10 +869,14 @@ CHAKRA_API JsSetContextData(_In_ JsContextRef context, _In_ void *data)
 void HandleScriptCompileError(Js::ScriptContext * scriptContext, CompileScriptException * se, const WCHAR * sourceUrl)
 {
     HRESULT hr = se->ei.scode;
-    if (hr == E_OUTOFMEMORY || hr == VBSERR_OutOfMemory || hr == VBSERR_OutOfStack || hr == ERRnoMemory)
+    if (hr == E_OUTOFMEMORY || hr == VBSERR_OutOfMemory || hr == ERRnoMemory)
```
Comment (jianchun) [inline lib/Jsrt/Jsrt.cpp]: Review: Please help check if removing `hr == VBSERR_OutOfStack` here is correct. I removed it because otherwise normal out of stack becomes fatal OOM too. That is inconsistent to how we handle normal out of stack in runtime.

Comment (akroshg) [reply lib/Jsrt/Jsrt.cpp]: I agree with you. The vbserr_outofstack should not throw OOM exception.

File: lib/Parser/Parse.cpp [hunk 2]
```diff
@@ -2247,9 +2247,10 @@ void Parser::ReduceDeferredScriptLength(size_t chars)
 
 void Parser::EnsureStackAvailable()
 {
-    if (!m_scriptContext->GetThreadContext()->IsStackAvailable(Js::Constants::MinStackCompile))
+    bool isInterrupt = false;
+    if (!m_scriptContext->GetThreadContext()->IsStackAvailable(Js::Constants::MinStackCompile, &isInterrupt))
     {
-        Error(ERRnoMemory);
+        Error(isInterrupt ? E_ABORT : VBSERR_OutOfStack);
```
Comment (akroshg) [inline lib/Parser/Parse.cpp]: I feel like there is one more place you can change as well, ParseArgList function.

Comment (jianchun) [reply lib/Parser/Parse.cpp]: @akroshg Changed to new error code in commit 2.

**Comment by jianchun** [comment]
> LGTM- is there a native test we can add to verify this case?

@digitalinfinity I tried but it depends on timing. If script execution is disabled early it would not enter parser. To hit this we need to disable script execution after parser started and before somewhere parser checks for stack. So did not add one.

**Comment by akroshg** [comment]
LGTM.

**Comment by jianchun** [comment]
Thanks @curtisman @akroshg @digitalinfinity
