### PR TITLE
OS#14101048: Fixes #249: built-in functions should not have caller/arguments (and related fixes)

### LINKED ISSUE #249: Built-in functions should not have properties 'caller' or 'arguments'
Currently the properties exist, are non-configurable, and always return null.

### PR DESCRIPTION
**Pull request by dilijev**
Replaces #4639

Several tests and test baselines needed to be updated to reflect the change in behavior. This change improves caller/arguments behavior without regressing any previous Chakra behavior. Chakra still differs from the spec and other engines on some aspects of caller/arguments.

See: https://tc39.github.io/ecma262/#sec-forbidden-extensions

Fixes #249
Fixes OS#14101048

---

Test262 results strictly improved.

Using test262 commit https://github.com/tc39/test262/commit/03da22868a3e0b9ecdee4a5d754c72df93baf995:

Previously 44130 passed, now 44138 passed out of 57102. (Duplicates below are strict and non-strict versions of the tests.)

```
+PASS e:/dd/test262/test262/test/built-ins/Function/prototype/restricted-property-arguments.js
+PASS e:/dd/test262/test262/test/built-ins/Function/prototype/restricted-property-arguments.js
+PASS e:/dd/test262/test262/test/built-ins/Function/prototype/restricted-property-caller.js
+PASS e:/dd/test262/test262/test/built-ins/Function/prototype/restricted-property-caller.js
+PASS e:/dd/test262/test262/test/built-ins/ThrowTypeError/forbidden-arguments.js
+PASS e:/dd/test262/test262/test/built-ins/ThrowTypeError/forbidden-arguments.js
+PASS e:/dd/test262/test262/test/built-ins/ThrowTypeError/forbidden-caller.js
+PASS e:/dd/test262/test262/test/built-ins/ThrowTypeError/forbidden-caller.js
```

### CODE REVIEW

File: lib/Runtime/Library/JavascriptFunction.cpp [hunk 1]
```diff
@@ -2467,7 +2467,10 @@ void __cdecl _alloca_probe_16()
             this->functionInfo->IsAsync() ||
             this->IsGeneratorFunction() ||
             this->IsBoundFunction() ||
-            this->IsStrictMode()
+            this->IsStrictMode() ||
```
Comment (boingoing) [inline lib/Runtime/Library/JavascriptFunction.cpp]: Looks like this should also check to see if the function is a method, right? Seems like https://tc39.github.io/ecma262/#sec-forbidden-extensions implies this. This is a little complicated, though, because `FunctionInfo` doesn't have an `IsMethod` helper. To plumb the flag, you could pull it out of `PnFnc::IsMethod` in `ByteCodeGenerator::StartBindFunction`.

Comment (dilijev) [reply lib/Runtime/Library/JavascriptFunction.cpp]: I think `this->functionInfo->IsClassMethod()` up at the top of this clause captures that.

File: lib/Runtime/Library/RuntimeFunction.cpp [hunk 2]
```diff
@@ -59,6 +59,11 @@ namespace Js
         this->functionNameId = nameId;
     }
 
+    bool RuntimeFunction::Is(Var func)
+    {
+        return JavascriptFunction::Is(func) && !JavascriptFunction::UnsafeFromVar(func)->GetFunctionInfo()->HasBody();
```
Comment (dilijev) [inline lib/Runtime/Library/RuntimeFunction.cpp]: @curtisman does this look right?

For reference, ScriptFunction is defined similarly (without negating HasBody()):

```
    bool ScriptFunction::Is(Var func)
    {
        return JavascriptFunction::Is(func) && JavascriptFunction::UnsafeFromVar(func)->GetFunctionInfo()->HasBody();
    }
```

File: lib/Runtime/Library/JavascriptFunction.cpp (hunk 1 above)
Comment (boingoing) [reply lib/Runtime/Library/JavascriptFunction.cpp]: I don't think that's true since `kFunctionIsClassMember` and `kFunctionIsMethod` are different flags on `PnFnc`.

**Comment by dilijev** [comment]
Updated the description with test262 results. /cc @bterlson

File: lib/Runtime/Library/JavascriptFunction.cpp (hunk 1 above)
Comment (dilijev) [reply lib/Runtime/Library/JavascriptFunction.cpp]: I see. In any case the behavior seems to be correct (per comparison other engines on test/es6/ES6RestrictedProperties.js). Will look into this in the future.

---
In reply to: [166775893](https://github.com/Microsoft/ChakraCore/pull/4651#discussion_r166775893) [](ancestors = 166775893)

File: test/es6/ES6RestrictedProperties.js [hunk 3]
```diff
@@ -127,61 +144,53 @@ var tests = [
...
             assert.areEqual('function', typeof p.get, "Function.prototype['caller'] has get accessor function");
             assert.areEqual('function', typeof p.set, "Function.prototype['caller'] has set accessor function");
             assert.throws(function() { p.get(); }, TypeError, "Function.prototype['caller'] has get accessor which throws");
             assert.throws(function() { p.set(); }, TypeError, "Function.prototype['caller'] has set accessor which throws");
-            assert.isTrue(p.get === p.set, "Function.prototype returns the same ThrowTypeError function for get/set accessor of 'caller' property");
 
             var p2 = Object.getOwnPropertyDescriptor(obj, 'arguments');
             assert.isFalse(p2.enumerable, "Function.prototype function has 'arguments' own property which is not enumerable");
-            assert.isFalse(p2.configurable, "Function.prototype function has 'arguments' own property which is not configurable");
+            assert.isTrue(p2.configurable, "Function.prototype function has 'arguments' own property which is is configurable");
```
Comment (dilijev) [inline test/es6/ES6RestrictedProperties.js]: >is  [](start = 110, length = 3)

whoops, typo

**Comment by dilijev** [comment]
See: https://tc39.github.io/ecma262/#sec-forbidden-extensions

**Comment by dilijev** [comment]
@boingoing 

> Oh I thought I saw a comment in one of the test files that said object-literal methods had different behavior on spidermonkey / v8.

Yes, that's right. I didn't realize we would call those methods. Getting that right would fix that behavior. But I think that can be outside the scope of this fix (fixes the bug, no regressions).
