### PR TITLE
make EndSwitch flush cases to the EndSwitch offset

### LINKED ISSUE #6037: [WebAssembly] ASSERTION 2257: ChakraCore v1.11.7
Hello

I have validated that the test case for https://github.com/Microsoft/ChakraCore/issues/5985 runs correctly with a Debug version of ChakraCore and the small test case but there still seems to be something wrong when running against our tests and still receiving the following:

```
ASSERTION 2257: (/Users/Jimmy/websharp/projects/ChakraCore/lib/Backend/IRBuilderAsmJs.cpp, line 1044) !IsLoopBody() || offset <= GetLoopBodyExitInstrOffset()
 Failure: (!IsLoopBody() || offset <= GetLoopBodyExitInstrOffset())
Illegal instruction: 4
```

Not sure how to create a small repo of this either.  Is there some way to help narrow this down even further?

### PR DESCRIPTION
**Pull request by MikeHolman**
This makes it so that if targetOffset is breaking out of a loop we won't have problems (could happen in wasm).

Now cases will go to EndSwitch, which just does direct branch to targetOffset. In normal cases, that will be cleaned up by RetargetBrToBr peep, so codegen doesn't change.

Fixes #6037

### CODE REVIEW

File: lib/Backend/SwitchIRBuilder.cpp [hunk 1]
```diff
@@ -163,7 +163,7 @@ SwitchIRBuilder::BeginSwitch()
 void
 SwitchIRBuilder::EndSwitch(uint32 offset, uint32 targetOffset)
 {
-    FlushCases(targetOffset);
+    FlushCases(offset);
     AssertMsg(m_caseNodes->Count() == 0, "Not all switch case nodes built by end of switch");
```
Comment (meg-gupta) [inline lib/Backend/SwitchIRBuilder.cpp]: What is offset/targetOffset here ? (I don't know this code)

Comment (MikeHolman) [reply lib/Backend/SwitchIRBuilder.cpp]: `offset` is the location of the `EndSwitch` instruction. `targetOffset` is the location that `EndSwitch` branches to.
