### PR TITLE
xplat: fix shared lib linux global symbols for WASM

### LINKED ISSUE #2859: Linux build is missing symbols as it is impossible to link to the shared library
Hi.
I am in the need of a JS engine, and as ChakraCore looks simpler to embed than google's one (I need the debug features), I tried to build an application with it.

The build of the library itself did perform well. But when I try the Hello World [Sample](https://github.com/Microsoft/Chakra-Samples/tree/master/ChakraCore%20Samples/Hello%20World/Linux_OSX_Shared), I get:
`../out/Release/libChakraCore.so : undefined reference to « Js::WasmLibrary::WasmDeferredParseEntryPoint(Js::RecyclableObject*, Js::CallInfo, ...) »`

I succeeded to build a program in « static mode » or with the 1.4 branch.

Build informations:
- ChakraCore Version: the master branch (bfc4da44e3f9560c72bf87aad9f63b8fcdd5cd16)
- OS: Debian testing
- kernel: 4.9.0-2-amd64  (SMP Debian 4.9.18-1)
- arch: amd64
- target: Release Shared
- main libraries/tools:  

component | version/info
-------------- | --------------
libc6 | 2.24-9
libstdc++6 | 6.3.0-12
gcc-6 | 6.3.0-12

### PR DESCRIPTION
**Pull request by obastemur**
- Fixes a wrong global reference for WASM
- Fixes folder case/naming for Release binary testing
- Adds a native test case to catch similar issues on CI
- Removes unnecessary unwind referencing on native tests

Fixes #2859

### CODE REVIEW

**Comment by obastemur** [comment]
@dotnet-bot test OSX osx_osx_test please

File: test/native-tests/test-shared-basic/Platform.js [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+if (isStaticBuild) {
+    // test will be ignored
+    print("# IGNORE_THIS_TEST");
+} else {
+    var platform = WScript.Platform.OS;
+    var binaryPath = WScript.Platform.BINARY_PATH;
+    // discard `ch` from path
+    binaryPath = binaryPath.substr(0, binaryPath.lastIndexOf(path_sep));
+    var makefile =
+"IDIR=" + binaryPath + "/../../lib/Jsrt \n\
```
Comment (jianchun) [inline test/native-tests/test-shared-basic/Platform.js]: >" [](start = 0, length = 1)

Wonder if you can use new template string multiline support to make this more readable.

**Comment by jianchun** [comment]
:shipit:

File: test/native-tests/test-shared-basic/Platform.js (hunk 1 above)
Comment (obastemur) [inline test/native-tests/test-shared-basic/Platform.js]: Could be nice. I have a plan to centralize make file generation too.

**Comment by obastemur** [comment]
@jianchun Thanks for the review
