### PR TITLE
Have getters on RegExp.prototype return default values when called with RegExp.prototype

### LINKED ISSUE #760: RegExp.prototype getters and methods need a web-compat hack
ES6 specified that RegExp.prototype is no longer a RegExp object and as a result, eg. RegExp.prototype.global would result in an exception (as is our current semantics under /es6all). However this change is not web compatible and, rather than going back and making RegExp.prototype a RegExp object, the various methods simply return default values if `this` doesn't have an [[OriginalFlags]] internal slot.

See also https://github.com/tc39/ecma262/issues/262 and https://github.com/tc39/ecma262/issues/511.

### PR DESCRIPTION
**Pull request by goyakin**
Fixes #760.

### CODE REVIEW

**Comment by goyakin** [comment]
@akroshg & @abchatra, could you take a look?

File: lib/Runtime/Library/JavascriptRegularExpression.cpp [hunk 1]
```diff
@@ -963,6 +969,12 @@ namespace Js
         ARGUMENTS(args, callInfo);
         Assert(!(callInfo.Flags & CallFlags_New));
 
+        ScriptContext* scriptContext = function->GetScriptContext();
+        if (ShouldApplyPrototypeWebWorkaround(args, scriptContext))
+        {
+            return scriptContext->GetLibrary()->GetUndefined();
+        }
+
         return GetJavascriptRegExp(args, _u("RegExp.prototype.options"), function->GetScriptContext())->GetOptions();
```
Comment (akroshg) [inline lib/Runtime/Library/JavascriptRegularExpression.cpp]: nit: you could change this to scriptContext.

**Comment by akroshg** [comment]
Rest looks good to me.
