### PR TITLE
Fix #5428: Remove non-ASCII characters from JsBuiltIn.js and generated .bc.*.h

### LINKED ISSUE #5428: Compile failed with code page 936.
Hi, 
I just found that error occurs when compiling latest version ChakraCore with code page 936 (which is default code page on Windows Chinese-Simplified version).

VS print this.
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4819	The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss	Chakra.Runtime.Library	e:\chakracore\lib\runtime\library\JsBuiltIn\JsBuiltIn.js.bc.64b.h	1	
```
It seems that `JsBuiltIn.js.bc.64b.h` is encoded in UTF-8 (code page 650001).  I have to `save-as` it with encoding GB2312(code page 936) every time before compiling the latest commit.

### PR DESCRIPTION
**Pull request by dilijev**
Fixes #5428

### CODE REVIEW

**Comment by MSLaguana** [comment]
Looks like you'll have to actually regenerate the bytecode, there might be some kind of reference to the sources or length in there?

File: lib/Runtime/Library/JsBuiltIn/JsBuiltIn.js.bc.32b.h [hunk 1]
```diff
@@ -250,10 +250,10 @@
 namespace Js
 {
     const char Library_Bytecode_JsBuiltIn[] = {
-/* 00000000 */ 0x43, 0x68, 0x42, 0x63, 0xC6, 0x1F, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
+/* 00000000 */ 0x43, 0x68, 0x42, 0x63, 0xFA, 0x1B, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
```
Comment (MSLaguana) [inline lib/Runtime/Library/JsBuiltIn/JsBuiltIn.js.bc.32b.h]: I'm surprised that there is such a large change here; the size of the bytecode has changed significantly, much more than I would expect for a simple changed comment. It also looks like number of built in properties has changed apparently?

Comment (dilijev) [reply lib/Runtime/Library/JsBuiltIn/JsBuiltIn.js.bc.32b.h]: Possibly this bytecode needed a regen due to other changes to bytecode format? All I know is that this is the bytecode generated by the regen script and the unit test for bytecode regen is happy. @jackhorton do you know of any factors here?

Comment (jackhorton) [reply lib/Runtime/Library/JsBuiltIn/JsBuiltIn.js.bc.32b.h]: if it used to be a single (two-byte) character, then the byte offsets of everything in the JS from that char afterwards would be moved by two, since now it uses two characters/four bytes.

Comment (dilijev) [reply lib/Runtime/Library/JsBuiltIn/JsBuiltIn.js.bc.32b.h]: Yes, that makes sense. Jimmy said it looked like the size of the bytecode changed significantly. I haven't confirmed that yet.

Comment (dilijev) [reply lib/Runtime/Library/JsBuiltIn/JsBuiltIn.js.bc.32b.h]: ` 5 files changed, 1251 insertions(+), 1495 deletions(-)` looks like the bytecode got smaller by around 250 lines -- more than would be expected for a two-character change in a comment.

Comment (jackhorton) [reply lib/Runtime/Library/JsBuiltIn/JsBuiltIn.js.bc.32b.h]: I understand now, @MSLaguana was saying that going from C6 to FA was a big jump, I think. Perhaps? Regardless, my Intl PR required a bytecode regen and didn't change JsBuiltIns, so I don't think its in a bad state.

Comment (MSLaguana) [reply lib/Runtime/Library/JsBuiltIn/JsBuiltIn.js.bc.32b.h]: Right, going from 0x1fc6 to 0x1bfa is quite sizable, and one of the subsequent changes in the header of the bytecode here is the count of built in properties, which seems to be different. I wouldn't have expected very much to change here from just the small change in a comment, but the fact that the test is passing now suggests that it is now a correct reflection of the generated bytecode, so I'm just a bit confused.

Comment (dilijev) [reply lib/Runtime/Library/JsBuiltIn/JsBuiltIn.js.bc.32b.h]: I re-ran the bytecode regen. It's consistent. (No new changes.) I'll merge the PR.
