### PR TITLE
Update for TTD - Node+VSCode, bug fixes, x-plat

### LINKED ISSUE #1244: Investigate whether TTBasic and TTExecuteBasic tests could be run in DisableJIT mode.
Currently ignoring these tests by using the tag `require_backend` (see #1242).

### PR DESCRIPTION
**Pull request by mrkmarron**
-Changes needed for debugging with Node & VSCode (see PR #1215).

- Various bug fixes
  -Perf in interperter loop
  -Break in release ch
  -DisableJIT issues (Fixes #1244)

- x-plat types & API defs in JsRT
- x-plat host support and all TTD tests in Linux

### CODE REVIEW

**Comment by mrkmarron** [comment]
@dilijev @jianchun @agarwal-sandeep @digitalinfinity @Yongqu please review

File: bin/ch/WScriptJsrt.cpp [hunk 1]
```diff
@@ -381,13 +381,9 @@ JsValueRef WScriptJsrt::LoadScript(JsValueRef callee, LPCSTR fileName, LPCSTR fi
...
         IfJsrtErrorSetGo(ChakraRTInterface::JsSetCurrentContext(calleeContext));
 
-#if ENABLE_TTD
-        errorCode = ChakraRTInterface::JsTTDRunScript(-1, fileContent, GetNextSourceContext(), fullPathNarrow, &returnValue);
-#else
         errorCode = ChakraRTInterface::JsRunScriptUtf8(fileContent, GetNextSourceContext(), fullPathNarrow, &returnValue);
-#endif
 
-        if (errorCode == JsNoError)
+        if(errorCode == JsNoError)
```
Comment (dilijev) [inline bin/ch/WScriptJsrt.cpp]: >if( [](start = 8, length = 3)

nit: preferred style throughout our codebase is `if (` (with a space).

File: lib/Jsrt/ChakraDebug.h [hunk 2]
```diff
@@ -22,13 +22,10 @@
...
-#if (!defined(_WIN32) || !defined(_MSC_VER)) && !defined(__MSTYPES_DEFINED)
-typedef uint32_t UINT32;
-typedef int64_t INT64;
-typedef void* HANDLE;
-typedef unsigned char BYTE;
-typedef UINT32 DWORD;
+#ifdef _WIN32
+typedef __int64 int64_t;
 #endif
+//Other platforms should include <stdint.h> and have this defined automatically
```
Comment (dilijev) [inline lib/Jsrt/ChakraDebug.h]: Why not document this need explicitly by adding #include <stdint.h> for non-Windows platforms?

File: lib/Jsrt/Jsrt.cpp [hunk 3]
```diff
@@ -258,42 +257,26 @@ JsErrorCode CreateContextCore(_In_ JsRuntimeHandle runtimeHandle, _In_ bool crea
...
             {
                 //
                 //TODO: We currently force this into debug mode in record as well to make sure parsing/bytecode generation is same as during replay.
                 //      Later we will want to be clever during inflate and not do this.
                 //
+#ifdef _WIN32
                 context->GetScriptContext()->InitializeDebugging();
+#else
+                //
+                //TODO: x-plat does not like some parts of initiallize debugging so just set the flag we need
```
Comment (dilijev) [inline lib/Jsrt/Jsrt.cpp]: >initiallize debugging [](start = 59, length = 21)

spelling of initialize
Also, if you're referring to the method above, write InitializeDebugging instead?

File: lib/Jsrt/Jsrt.cpp [hunk 4]
```diff
@@ -2226,7 +2129,81 @@ CHAKRA_API JsSetExternalData(_In_ JsValueRef object, _In_opt_ void *data)
...
+    {
+        *result = nullptr;
+    }
+
+    return ContextAPIWrapper<true>([&](Js::ScriptContext *scriptContext) -> JsErrorCode {
+        VALIDATE_INCOMING_FUNCTION(function, scriptContext);
+
+        if(cargs == 0 || args == nullptr) {
+            return JsErrorInvalidArgument;
+        }
```
Comment (dilijev) [inline lib/Jsrt/Jsrt.cpp]: nit: style - please put open braces on their own lines

File: lib/Runtime/Debug/TTEventLog.cpp [hunk 5]
```diff
@@ -1064,6 +1193,54 @@ namespace TTD
 
         this->m_callStack.Add(cfinfo);
 
+        ////
```
Comment (dilijev) [inline lib/Runtime/Debug/TTEventLog.cpp]: >//// [](start = 8, length = 4)

Why these lines?

**Comment by mrkmarron** [comment]
@jianchun @digitalinfinity There is also a change to runtests.py that forces it to a single thread. I added a tag "sequential" to rl that allows the tests in a directory to be run sequentially and in-order for a directory but runtests does not recognize this flag yet.

File: bin/ch/ch.cpp [hunk 6]
```diff
@@ -254,16 +248,33 @@ HRESULT RunScript(const char* fileName, LPCSTR fileContents, BYTE *bcBuffer, cha
...
+                    else
+                    {
+                        wprintf(_u("Fatal Error in Move!!!\n"));
+                        break;
+                    }
+                }
 
-                ChakraRTInterface::JsTTDMoveToTopLevelEvent(snapEventTime, nextEventTime);
+                ChakraRTInterface::JsTTDPrepContextsForTopLevelEventMove(chRuntime, needFreshCtxs);
+                ChakraRTInterface::JsTTDMoveToTopLevelEvent(moveMode, snapEventTime, nextEventTime);
```
Comment (agarwal-sandeep) [inline bin/ch/ch.cpp]: Error checking? You can use the macros defined in bin\ch\stdafx.h.

File: bin/ch/ch.cpp [hunk 7]
```diff
@@ -18,12 +18,11 @@ JsRuntimeHandle chRuntime = JS_INVALID_RUNTIME_HANDLE;
 
 BOOL doTTRecord = false;
 BOOL doTTDebug = false;
-char* ttUri = nullptr;
+byte ttUri[MAX_PATH * sizeof(wchar_t)];
```
Comment (agarwal-sandeep) [inline bin/ch/ch.cpp]: >wchar_t [](start = 29, length = 7)

Should be TTDHostCharType instead of wchar_t

File: lib/Common/CommonDefines.h [hunk 8]
```diff
@@ -326,15 +326,31 @@
 
 ////////
 //Time Travel flags
+
+//If this is being included from in CH see if TTD is enabled there and do the same here -- otherwise check DBG and ENABLE_DEBUG_CONFIG_OPTIONS values
+#ifdef HOST_ENABLE_TTD
+#define ENABLE_TTD HOST_ENABLE_TTD
+#else
 #define ENABLE_TTD 1
```
Comment (Yongqu) [inline lib/Common/CommonDefines.h]: does this mean that TTD will be enabled in chakra.dll?

File: lib/Runtime/Base/ThreadContext.h [hunk 9]
```diff
@@ -325,6 +325,10 @@ class ThreadConfiguration
         {
             EnableExperimentalFeatures();
             ResetExperimentalFeaturesFromConfig();
+
+#if TTD_VSCODE_WORK_AROUNDS
+            m_Simdjs = false;
+#endif
```
Comment (agarwal-sandeep) [inline lib/Runtime/Base/ThreadContext.h]: Not needed anymore, we have COMPILE_DISABLE_Simdjs option to disable Simdjs in node scenario at compile time.

File: bin/ch/Helpers.cpp [hunk 10]
```diff
@@ -4,6 +4,212 @@
...
+}
+
+void TTDHostInitEmpty(TTDHostCharType* dst)
+{
+    dst[0] = _u('\0');
+}
+
+void TTDHostInitFromUriBytes(TTDHostCharType* dst, const byte* uriBytes, size_t uriBytesLength)
+{
+    memcpy_s(dst, MAX_PATH * sizeof(TTDHostCharType), uriBytes, uriBytesLength);
```
Comment (jianchun) [inline bin/ch/Helpers.cpp]: (I may be out of context.) Using `MAX_PATH * ...` here completely bypasses the purpose of `memcpy_s`. If you want that, consider passing length of dst as a parameter?

File: bin/ch/Helpers.cpp [hunk 11]
```diff
@@ -4,6 +4,212 @@
...
+{
+    return wcslen(str);
+}
+
+void TTDHostInitEmpty(TTDHostCharType* dst)
+{
+    dst[0] = _u('\0');
+}
+
+void TTDHostInitFromUriBytes(TTDHostCharType* dst, const byte* uriBytes, size_t uriBytesLength)
```
Comment (jianchun) [inline bin/ch/Helpers.cpp]: Why do you design "uri" this way... makes its usage on xplat very hard. Looks the "uri" string has to contain char16, and pass around as raw pointer, here you assemble it back to char16*.

Can it simply be type `const char*`? You can use conversion routines in Utf8Codex dir.

File: lib/Runtime/Debug/TTEventLog.cpp [hunk 12]
```diff
@@ -1064,6 +1193,54 @@ namespace TTD
...
+        //Debug experiment
+#if TTD_VSCODE_WORK_AROUNDS
```
Comment (agarwal-sandeep) [inline lib/Runtime/Debug/TTEventLog.cpp]: >TTD_VSCODE_WORK_AROUNDS [](start = 4, length = 23)

What's the scenario for which we require a work around?

File: bin/ch/Helpers.cpp [hunk 13]
```diff
@@ -4,6 +4,212 @@
 //-------------------------------------------------------------------------------------------------------
 #include "stdafx.h"
 
+//TODO: x-plat definitions
+#ifdef _WIN32
+typedef char16 TTDHostCharType;
```
Comment (jianchun) [inline bin/ch/Helpers.cpp]: Wonder if you could consider using "char16" directly. It is used through out the whole code base. Using it for TTD may be more readable.

File: bin/ch/Helpers.cpp [hunk 14]
```diff
@@ -4,6 +4,212 @@
...
+{
+    size_t dpos = TTDHostStringLength(dst);
+    size_t srcLength = TTDHostStringLength(src);
+    size_t srcByteLength = srcLength * sizeof(TTDHostCharType);
+
+    memcpy_s(dst + dpos, srcByteLength, src, srcByteLength);
+    dst[dpos + srcLength] = _u('\0');
+}
+
+void TTDHostAppendWChar(TTDHostCharType* dst, const wchar* src)
```
Comment (jianchun) [inline bin/ch/Helpers.cpp]: Consider replace all `wchar` with `char16`. One less char type to think about.

File: bin/ch/Helpers.cpp [hunk 15]
```diff
@@ -4,6 +4,212 @@
...
+
+#define TTDHostCharConvert(X) ((char*)X)
+#define TTDHostUtf8CharConvert(X) ((TTDHostCharType*)X)
+
+size_t TTDHostStringLength(const TTDHostCharType* str)
+{
+    return strlen(TTDHostCharConvert(str));
+}
+
+void TTDHostInitEmpty(TTDHostCharType* dst)
```
Comment (jianchun) [inline bin/ch/Helpers.cpp]: Does TTDHostCharType has to be different between _WIN32 and non-_WIN32? If you can consolidate to the same type, you don't need 2 copies of these.

File: lib/Runtime/Library/JavascriptArray.cpp [hunk 16]
```diff
@@ -796,11 +796,16 @@ namespace Js
...
-            FunctionBody *functionBody = weakFuncRef->Get();
-            JavascriptLibrary *lib = scriptContext->GetLibrary();
 
 #if ENABLE_COPYONACCESS_ARRAY
+            JavascriptLibrary *lib = scriptContext->GetLibrary();
+            FunctionBody *functionBody = weakFuncRef->Get();
+
+#if TTD_DISABLE_COPYONACCESS_ARRAY_WORK_AROUNDS
+            if (JavascriptLibrary::IsCopyOnAccessArrayCallSite(lib, arrayInfo, count) && Js::Configuration::Global.flags.TestTrace.IsEnabled(Js::CopyOnAccessArrayPhase))
+#else
```
Comment (agarwal-sandeep) [inline lib/Runtime/Library/JavascriptArray.cpp]: Why is this needed? IsCopyOnAccessArrayCallSite does the check for !PHASE_OFF1(CopyOnAccessArrayPhase)? Also here nothing is TTD specific?

File: lib/Jsrt/ChakraDebug.h (hunk 2 above)
Comment (jianchun) [inline lib/Jsrt/ChakraDebug.h]: Already included in linux branch: https://github.com/Microsoft/ChakraCore/blob/linux/lib/Jsrt/ChakraCommon.h#L71

We need some cleanup after merge.

File: lib/Jsrt/ChakraDebug.h [hunk 17]
```diff
@@ -636,87 +637,93 @@ typedef UINT32 DWORD;
...
     /// </summary>
-    /// <remarks>
-    ///     <para>Exactly one of read or write will be set to true.</para>
-    /// </remarks>
-    /// <param name="uri">The fully resolved location for the TTD data as provied by JsTTDInitializeUriCallback.</param>
-    /// <param name="read">If the handle should be opened for reading.</param>
-    /// <param name="write">If the handle should be opened for writing.</param>
-    /// <returns>A HANDLE opened in read/write mode as specified.</returns>
-    typedef HANDLE (CHAKRA_CALLBACK *JsTTDGetLogStreamCallback)(_In_z_ const wchar_t* uri, _In_ bool read, _In_ bool write);
+    typedef void* JsTTDStreamHandle;
```
Comment (jianchun) [inline lib/Jsrt/ChakraDebug.h]: You can use sth. similar to Windows DECLARE_HANDLE for a bit better type safety.

File: test/runtests.py [hunk 18]
```diff
@@ -554,7 +554,7 @@ def main():
     ]
 
     # run each variant
-    pool = Pool() # Use a multiprocessing process Pool
+    pool = Pool(1) # Use a multiprocessing process Pool -- TODO: forcing this to single threaded until we have support for sequential tag
```
Comment (jianchun) [inline test/runtests.py]: We can add all sequential tests into another list, and run that list with one single process.

File: lib/Runtime/Debug/TTSupport.h [hunk 19]
```diff
@@ -637,6 +680,17 @@ namespace TTD
...
         }
 
+        //clone a utf8 string into the allocator of a known length
+        void CopyStringIntoWLengthUtf8(const char* utf8str, uint32 length, TTStringUtf8& into)
+        {
+            AssertMsg(str != nullptr, "Not allowed for string + length");
+
+            into.Length = length;
+            into.Contents = this->SlabAllocateArray<char>(into.Length + 1);
+            js_memcpy_s(into.Contents, into.Length * sizeof(char), str, length * sizeof(char));
```
Comment (agarwal-sandeep) [inline lib/Runtime/Debug/TTSupport.h]: >str [](start = 67, length = 3)

Should be utf8str

File: lib/Runtime/Debug/TTSnapValues.cpp [hunk 20]
```diff
@@ -95,53 +82,76 @@ namespace TTD
...
-            bool okBOC = streamFunctions.pfWriteBytesToStream(srcStream, byteOrderArray, 2, &byteOrderCount);
-            AssertMsg(okBOC && byteOrderCount == 2, "Write Failed!!!");
+            JsTTDStreamHandle srcStream = threadContext->TTDStreamFunctions.pfGetResourceStream(threadContext->TTDUri.UriByteLength, threadContext->TTDUri.UriBytes, asciiResourceName, false, true);
+
+            if(isUtf8Source)
+            {
+                byte byteOrderArray[3] = { 0xEF, 0xBB, 0xBF };
+                size_t byteOrderCount = 0;
+                bool okBOC = threadContext->TTDStreamFunctions.pfWriteBytesToStream(srcStream, byteOrderArray, 3, &byteOrderCount);
+                AssertMsg(okBOC && byteOrderCount == 3, "Write Failed!!!");
```
Comment (agarwal-sandeep) [inline lib/Runtime/Debug/TTSnapValues.cpp]: Only byteOrderArray is different between if and else, can we refactor and keep the call to pfWriteBytesToStream and assert as common? can use _countof(byteOrderArray) for size. Same thing for read?

File: lib/Runtime/Debug/TTSnapValues.cpp [hunk 21]
```diff
@@ -1045,29 +1069,17 @@ namespace TTD
...
-                SRCINFO *hsi = ctx->AddHostSrcInfo(&si);
-                uint32 flags = 0;
-
-                HRESULT hr = Js::ByteCodeSerializer::DeserializeFromBuffer(ctx, flags, utf8Source, hsi, fbInfo->TopLevelBase.DbgSerializedBytecodeBuffer, nullptr, &globalBody);
-                AssertMsg(SUCCEEDED(hr), "This should not fail!!!");
-
-                utf8SourceInfo = globalBody->GetUtf8SourceInfo();
-                scriptFunction = ctx->GetLibrary()->CreateScriptFunction(globalBody);
+                //
+                //TODO: Bytecode serializer does not suppper debug bytecode (StatementMaps vs Positions) so add this to serializer code.
```
Comment (agarwal-sandeep) [inline lib/Runtime/Debug/TTSnapValues.cpp]: >suppper [](start = 53, length = 7)

support? same below

File: bin/ch/Helpers.cpp (hunk 11 above)
Comment (mrkmarron) [inline bin/ch/Helpers.cpp]: This design allows the host to represent the URI in whatever format it likes (wchar, utf8, etc.) and allows ChakraCore to just pass the buffer of bytes without needing to know anything about them. Thus, the CH host can use char16 for windows and utf8 on posix. I thought about using a single char* representation in the Host but I didn't like having the utf8/char16 conversions anytime I accessed a file/directory.

File: bin/ch/Helpers.cpp (hunk 15 above)
Comment (mrkmarron) [inline bin/ch/Helpers.cpp]: As I understand the std path/file apis for windows use wchar for path names and utf8 on Posix. I could not find any simple way to use a single char encoding on both platforms. If there is an alternative approach I am happy to consider it.

File: lib/Runtime/Debug/TTSnapshot.cpp [hunk 22]
```diff
@@ -182,7 +182,7 @@ namespace TTD
             res = ctx->TTDWellKnownInfo->LookupKnownObjectFromPath(snpObject->OptWellKnownToken);
 
             //Well known objects may always be dirty (e.g. we are re-using a context) so we always want to clean them
-            res = NSSnapObjects::ObjectPropertyReset(snpObject, Js::DynamicObject::FromVar(res), inflator, FALSE);
+            res = NSSnapObjects::ObjectPropertyReset(snpObject, Js::DynamicObject::FromVar(res), inflator, TRUE);
```
Comment (agarwal-sandeep) [inline lib/Runtime/Debug/TTSnapshot.cpp]: >TRUE [](start = 107, length = 4)

Can we use bool instead of BOOL? personally I never liked BOOL.

File: lib/Jsrt/JsrtDiag.cpp [hunk 23]
```diff
@@ -422,12 +422,42 @@ CHAKRA_API JsDiagSetStepType(
...
+            ThreadContext* threadContext = runtime->GetThreadContext();
+
+            TTD::TTDebuggerSourceLocation bpLocation;
+            threadContext->TTDLog->GetPreviousTimeAndPositionForDebugger(bpLocation);
+            threadContext->TTDLog->SetPendingTTDBPInfo(bpLocation);
+
+            threadContext->TTDLog->LoadBPListForContextRecreate();
+
+            jsrtDebugManager->SetResumeType(BREAKRESUMEACTION_CONTINUE);
+#else
```
Comment (agarwal-sandeep) [inline lib/Jsrt/JsrtDiag.cpp]: Please remove this, I don't think we should check-in such hacks

File: lib/Jsrt/JsrtDiag.cpp [hunk 24]
```diff
@@ -422,12 +422,42 @@ CHAKRA_API JsDiagSetStepType(
...
+            threadContext->TTDLog->SetPendingTTDBPInfo(bpLocation);
+
+            threadContext->TTDLog->LoadBPListForContextRecreate();
+
+            //don't worry about BP suppression because we are just going to throw after we return
+
+            jsrtDebugManager->SetResumeType(BREAKRESUMEACTION_CONTINUE);
+#else
+            return JsErrorDiagUnableToPerformAction;
+#endif
```
Comment (agarwal-sandeep) [inline lib/Jsrt/JsrtDiag.cpp]: JsDiagStepTypeStepBack should only be allowed in replay mode of ttd and in all cases this should return JsErrorInvalidArgument

File: lib/Jsrt/Jsrt.cpp [hunk 25]
```diff
@@ -258,42 +257,26 @@ JsErrorCode CreateContextCore(_In_ JsRuntimeHandle runtimeHandle, _In_ bool crea
...
                 //      Later we will want to be clever during inflate and not do this.
                 //
+#ifdef _WIN32
                 context->GetScriptContext()->InitializeDebugging();
+#else
+                //
+                //TODO: x-plat does not like some parts of initiallize debugging so just set the flag we need 
+                //
+                context->GetScriptContext()->GetDebugContext()->SetDebuggerMode(Js::DebuggerMode::Debugging);
+#endif
```
Comment (agarwal-sandeep) [inline lib/Jsrt/Jsrt.cpp]: I had fixed SetDispatchProfile call in RegisterDebugThunk sometime back, are you still seeing the issue? Instead of this we should fix the issue, I think it should just be some initialization issue

File: lib/Jsrt/ChakraDebug.h [hunk 26]
```diff
@@ -636,87 +637,93 @@ typedef UINT32 DWORD;
...
-    ///     Ensure that the location specified for outputting the TTD data is clean. Specifically, ensure that any previous TTD
-    ///     in the location has been removed.
-    /// </summary>
-    /// <param name="fullTTDUri">The fully resolved location for the TTD data output as provied by JsTTDInitializeUriCallback.</param>
-    typedef void (CHAKRA_CALLBACK *JsTTDInitializeForWriteLogStreamCallback)(_In_z_ const wchar_t* uri);
+        /// <summary>
+        ///     Indicates that we want to move to the first/last event.
+        /// </summary>
+        JsTTDMoveFirstEvent = 0x1,
+        JsTTDMoveLastEvent = 0x2,
```
Comment (agarwal-sandeep) [inline lib/Jsrt/ChakraDebug.h]: Have separate comments for each

**Comment by agarwal-sandeep** [comment]
>     /// <param name="flushAndCloseStream">The <c>JsTTDFlushAndCloseStreamCallback</c> function for flushing and closing a HANDLE as needed.</param>

update it after API signature change

---
Refers to: lib/Jsrt/ChakraDebug.h:815 in 9bcf567. [](commit_id = 9bcf56725459d23b441515607f1515863d172677, deletion_comment = False)

File: lib/Jsrt/Jsrt.cpp [hunk 27]
```diff
@@ -3897,39 +4019,145 @@ CHAKRA_API JsTTDMoveToTopLevelEvent(_In_ INT64 snapshotTime, _In_ INT64 eventTim
...
 #endif
 }
 
-CHAKRA_API JsTTDReplayExecution(_Out_ INT64* rootEventTime)
+CHAKRA_API JsTTDReplayExecution(_Inout_ JsTTDMoveMode* moveMode, _Inout_ int64_t* rootEventTime)
 {
 #if !ENABLE_TTD_DEBUGGING
     return JsErrorCategoryUsage;
 #else
     JsrtContext *currentContext = JsrtContext::GetCurrent();
```
Comment (agarwal-sandeep) [inline lib/Jsrt/Jsrt.cpp]: We expect a valid context here so this should be inside ContextAPIWrapper

File: lib/Jsrt/JsrtDiag.cpp [hunk 28]
```diff
@@ -428,6 +428,28 @@ CHAKRA_API JsDiagSetStepType(
...
+            threadContext->TTDLog->GetPreviousTimeAndPositionForDebugger(bpLocation);
+            threadContext->TTDLog->SetPendingTTDBPInfo(bpLocation);
+
+            threadContext->TTDLog->LoadBPListForContextRecreate();
+
+            //don't worry about BP suppression because we are just going to throw after we return
+
+            jsrtDebugManager->SetResumeType(BREAKRESUMEACTION_CONTINUE);
+#else
+            return JsErrorDiagUnableToPerformAction;
```
Comment (agarwal-sandeep) [inline lib/Jsrt/JsrtDiag.cpp]: >JsErrorDiagUnableToPerformAction [](start = 19, length = 32)

This and above should be JsErrorInvalidArgument

**Comment by dilijev** [comment]
@dotnet-bot 
test Windows arm_test please
test Windows x86_debug please

**Comment by digitalinfinity** [comment]
@dotnet-bot  test Windows arm_debug please
