### PR TITLE
Wasm: EntryPoint cleanup

### LINKED ISSUE #2452: Wasm/Asm.js: Entrypoints sharing
We have been working under the assumption that every Function object for the same FunctionBody share the same entry points.
This is wrong in some scenario, including when we queue for jit and if the type of the function is changed (e.g.: adding a property to 1 of the function)
This mixed with deferred parsing in WebAssembly can have some unforeseen  consequences. 
#2451 fixes the known issues superficially, but this needs deeper thinking to guaranty a consistent behavior.

One idea is to have the functions always check for code gen before going to the interpreter.

### PR DESCRIPTION
**Pull request by Cellule**
Always use AsmJsDefault entrypoint instead of a wasm deferred parse entry point.
Fixes #2452
Fixes OS#16054008 (It may not be a complete fix, but it should at least add asserts to better debug the problem)

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/5437)

### CODE REVIEW

**Comment by Cellule** [comment]
ping

File: lib/Runtime/Base/FunctionBody.cpp [hunk 1]
```diff
@@ -3564,23 +3564,33 @@ namespace Js
         JavascriptMethod directEntryPoint = this->GetDefaultEntryPointInfo()->jsMethod;
         JavascriptMethod originalEntryPoint = this->GetOriginalEntryPoint_Unchecked();
 
+        FunctionBody* body = this->GetFunctionBody();
```
Comment (sethbrenith) [inline lib/Runtime/Base/FunctionBody.cpp]: This code used to check `IsFunctionBody` before calling `GetFunctionBody`. Could this possibly be called on a base `FunctionProxy`? Would we want such a call to not crash?

File: lib/Runtime/Language/InterpreterStackFrame.cpp [hunk 2]
```diff
@@ -1592,31 +1592,68 @@ namespace Js
...
+
+            push[esp + 8];    // push function object
+            call InterpreterStackFrame::EnsureDynamicInterpreterThunk;
+skipThunk:
+#ifdef _CONTROL_FLOW_GUARD
+            // verify that the call target is valid
+            push eax;
+            mov  ecx, eax;
+            call[__guard_check_icall_fptr];
+            pop eax;
```
Comment (MikeHolman) [inline lib/Runtime/Language/InterpreterStackFrame.cpp]: CFG check restores ecx. rather than saving/restoring from the stack it's better to do mov ecx, eax

File: lib/Runtime/Base/FunctionBody.cpp (hunk 1 above)
Comment (Cellule) [reply lib/Runtime/Base/FunctionBody.cpp]: It's true that it used to do `IsFunctionBody` but it also used to just call `GetFunctionBody` in the or statement
`(IsFunctionBody() && GetFunctionBody()) || GetFunctionBody()` is essentially what we had. So the `IsFunctionBody()` was pointless.

However, the only difference here is if any of the first 3 conditions were true, then we would not `GetFunctionBody()`
```cpp
IsIntermediateCodeGenThunk(directEntryPoint) || originalEntryPoint == directEntryPoint
 #if ENABLE_PROFILE_INFO
-            || (directEntryPoint == DynamicProfileInfo::EnsureDynamicProfileInfoThunk
```
However, I believe that even in those cases, `IsFunctionBody()` should be true

File: lib/Runtime/Language/InterpreterStackFrame.cpp (hunk 2 above)
Comment (Cellule) [reply lib/Runtime/Language/InterpreterStackFrame.cpp]: done and I've looked for other places where we do this as well

Comment (MikeHolman) [reply lib/Runtime/Language/InterpreterStackFrame.cpp]: thanks for cleaning that up, it looks good to me!
