### PR TITLE
xplat: enable JIT for debugger

### LINKED ISSUE #3352: xplat: Enable JIT for debugging
I compiled ChakraCore using the official build guide. 
On ubuntu 16.04, ch crashes with the following test case.
I also noticed that if we slightly change the code (using a proper indentation), the Seg fault will be gone.
The hashtag of my chakracore build is 
commit cb9c8271c8c9e2a0daec635504b5279168d92f1b

$ ~/chakracore/ChakraCore/out/Release/ch abc.js
Segmentation fault (core dumped)
$ cat abc.js
```
function
run
()
{}
WScript.Attach(run)
WScript
    .
Detach
(
run
)
```

### PR DESCRIPTION
**Pull request by obastemur**
- Xplat XDataAllocator Reg and UnReg are lazy ops. Using a scope delete
class, we let XData address unreg before old codegen is deleted.

- Do not forceNoNative during xplat debug anymore

- Add a new test case

Fixes #3352

### CODE REVIEW

**Comment by obastemur** [comment]
@jianchun ping

File: test/Debugger/failfast.js.dbg.baseline [hunk 1]
```diff
@@ -0,0 +1 @@
+[]
```
Comment (agarwal-sandeep) [inline test/Debugger/failfast.js.dbg.baseline]: nit: rename this file from failfast.js.dbg.baseline to empty.dbg.baseline so that it can be reused as empty file in future.

File: lib/Runtime/Base/ScriptContext.cpp [hunk 2]
```diff
@@ -3065,7 +3098,12 @@ namespace Js
 
         // Rundown on all existing functions and change their thunks so that they will go to debug mode once they are called.
 
+#if !defined(_WIN32) && ENABLE_NATIVE_CODEGEN
+        OldCodeGenAutoDelete autoDelete(this);
+        HRESULT hr = OnDebuggerAttachedDetached(/*attach*/ true, &(autoDelete.oldCodegen));
+#else // !defined(_WIN32) && ENABLE_NATIVE_CODEGEN
         HRESULT hr = OnDebuggerAttachedDetached(/*attach*/ true);
+#endif
```
Comment (agarwal-sandeep) [inline lib/Runtime/Base/ScriptContext.cpp]: Is it necessary to have it differently on windows and xpalt? seems like xpalt way is valid for windows as well.

Comment (obastemur) [reply lib/Runtime/Base/ScriptContext.cpp]: Indeed no obvious reason why it shouldn't work. Still didn't want to change it on Windows as I'm not comfortable with Debugger related implementation.Thus, not able to estimate there well.

If you say it's good to go, I can remove ifdefs and enable it for Windows too.

Comment (agarwal-sandeep) [reply lib/Runtime/Base/ScriptContext.cpp]: Remove the ifdefs and trigger a cirro crawler run. good to have same code on all platform as far as possible.

**Comment by obastemur** [comment]
@dotnet-bot test OSX static_osx_osx_debug please

**Comment by obastemur** [comment]
@agarwal-sandeep waiting for the cirro run. Anything else?
