### PR TITLE
fixes #5513 add toStringTag for global object

### LINKED ISSUE #5513: Global object has no toStringTag unlike other engines
Hello,
The following code behaves strangely (inconsistent with other engines).
```
var test = 1; 
function fail(n, expected, result) { print("test " + test + "; expected " + expected + ", got " + result); }
function test0() {
    var result;
    var check;

    result = (~ 2147483647);
    check = this;
    if(result != check) {{ fail(test, check, result); }} ++test; 
}
test0();
print("BT_FLAG");
```
In ChakraCore, the output is
```
test 1; expected [object Object], got -2147483648
BT_FLAG
```
However, in V8 and SpiderMonkey, output is
```
test 1; expected [object global], got -2147483648
BT_FLAG
```
BT group
2018.7.24

### PR DESCRIPTION
**Pull request by duongnhn**
- add toStringTag for global object to mach other engines.
- recreate baseline files.

### CODE REVIEW

File: lib/Runtime/Library/JavascriptLibrary.cpp [hunk 1]
```diff
@@ -1141,6 +1141,8 @@ namespace Js
         AddMember(globalObject, PropertyIds::NaN, nan, PropertyNone);
         AddMember(globalObject, PropertyIds::Infinity, positiveInfinite, PropertyNone);
         AddMember(globalObject, PropertyIds::undefined, undefinedValue, PropertyNone);
+        // Note: for global object, we need to set toStringTag to global like other engines (v8)
+        AddMember(globalObject, PropertyIds::_symbolToStringTag, scriptContext->GetPropertyString(PropertyIds::global) , PropertyNone);
```
Comment (duongnhn) [inline lib/Runtime/Library/JavascriptLibrary.cpp]: add ToStringTag property for global object
