### PR TITLE
Fixing RegExp parsing for character classes interacting with ranges.

### LINKED ISSUE #258: [RegExp] /[\s-a-c]/ is parsed incorrectly
Currently, Chakra parses `/[\s-a-c]/` as:
- The character class `\s`
- The character `-`
- The range `a-c`

However, other engines parse it as:
- The range `\s-a`, which is treated as the union of class `\s`, and the characters `-` and `a`
- The character `-`
- The character `c`

As a result, Chakra matches the character `b` with this pattern whereas others don't.

Annex B of the spec has been [changed ](https://github.com/tc39/ecma262/commit/fbdfda6f2a613f3c4813d4b34e32f5c5134cf921) to the rules used by other engines, so Chakra should be updated to match the spec.

### PR DESCRIPTION
**Pull request by kfukuda2**
Fixes #258

### CODE REVIEW

File: test/Regex/characterclass_with_range.js [hunk 1]
```diff
@@ -0,0 +1,163 @@
+//-------------------------------------------------------------------------------------------------------
+// Copyright (C) Microsoft. All rights reserved.
+// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
+//-------------------------------------------------------------------------------------------------------
+
+WScript.LoadScriptFile("..\\UnitTestFramework\\UnitTestFramework.js");
+
+let re = /^[\s-a-z]$/;
```
Comment (MSLaguana) [inline test/Regex/characterclass_with_range.js]: Is this regex expected to include codepoints between the last of the spaces and `a`? That is, do the numbers and capital letters fall into that range because they are between `0x20 = ' '` and `0x61 = 'a'`?

Comment (kfukuda2) [reply test/Regex/characterclass_with_range.js]: No, sorry I should have linked the issue initially. https://github.com/Microsoft/ChakraCore/issues/258 
/[\s-a]/ should just be interpreted as the set of all whitespace, '-', and the letter a

**Comment by dilijev** [comment]
@kfukuda2 I updated your PR description to include `Fixes #258` so that the issue will be automatically closed by GitHub when the PR is merged.

File: test/Regex/characterclass_with_range.js [hunk 2]
```diff
@@ -0,0 +1,163 @@
...
+        {
+            assert.isFalse(reNoCharClass.test("y"));
+        }
+    }    
+    /*Non-character class tests End*/
+];
+
+if (typeof modifyTests !== "undefined") {
+    tests = modifyTests(tests);
+}
```
Comment (dilijev) [inline test/Regex/characterclass_with_range.js]: This whole thing about `modifyTests` is not part of the standard UnitTestsFramework template -- I believe it was specific to the test we looked at. You can safely remove these 3 lines.

**Comment by dilijev** [comment]
Spec logic says to interpret the `\s-a` part of `\s-a-c` as a range, and then notice that one endpoint is a character set and instead treat it as a union of the set and the other literal characters. When the following characters are parsed, we are not parsing a character set so they are taken as literals (`-` and `c`).

This `prevprev` approach actually seems like it might be a bit fragile to maintain (and maybe fragile for the parser state as well). If we never have to build on top of this logic, it would probably be fine as-is, but I'm a little worried about maintainability with this approach.

Would it be possible to identify the first "range" which includes the `\s` (`\s-a`), and then enter into a new parser production for that "range", which notices that one of the endpoints (`\s`) is a charset and then treats it as a union of the charset and the remaining literal chars instead of the usual range logic?

It's also possible that this approach might put the parser into a confused state and cause further bad parses related to ranges. I'll read the code more closely and see if I can come up with a bad case or prove it's not possible.

File: test/Regex/characterclass_with_range.js [hunk 3]
```diff
@@ -0,0 +1,163 @@
...
+// Copyright (C) Microsoft. All rights reserved.
+// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
+//-------------------------------------------------------------------------------------------------------
+
+WScript.LoadScriptFile("..\\UnitTestFramework\\UnitTestFramework.js");
+
+let re = /^[\s-a-z]$/;
+let reIgnoreCase = /^[\s-a-z]$/i;
+let reUnicode = /^[\s-z]$/u;
+let reNoCharClass = /^[a-c-z]$/;
```
Comment (dilijev) [inline test/Regex/characterclass_with_range.js]: >/^[a-c-z]$/; [](start = 20, length = 12)

Remember that /^[blah]$/ produces a different MatchSet bytecode than /[blah]/ -- you might want to double check that the change to the parser logic creates the correct set in various bytecodes (since we're creating the set itself in the part of the parser we're looking at here, I don't see why it would be any different, but it's a good idea to check).

File: test/Regex/characterclass_with_range.js [hunk 4]
```diff
@@ -0,0 +1,163 @@
...
+        body : function () 
+        {
+            assert.isTrue(re.test("z"));
+        }
+    },
+    {
+        name : "Ensure '\t' included in set",
+        body : function () 
+        {
+            assert.isTrue(re.test("\t"));
```
Comment (dilijev) [inline test/Regex/characterclass_with_range.js]: >\t [](start = 35, length = 2)

it would be a good idea to test one of the non-ASCII whitespaces included in \s.  (see StandardChars.cpp(192): `StandardChars<char16>::whitespaceStr`)

Comment (dilijev) [reply test/Regex/characterclass_with_range.js]: One of either: paragraph separator (U+2028) or line separator (U+2029) might be a good case here, assuming we already handle them correctly. [https://en.wikipedia.org/wiki/Template:Whitespace_(Unicode](https://en.wikipedia.org/wiki/Template:Whitespace_(Unicode))

---
In reply to: [199985601](https://github.com/Microsoft/ChakraCore/pull/5418#discussion_r199985601) [](ancestors = 199985601)

File: lib/Parser/RegexParser.cpp [hunk 5]
```diff
@@ -2147,30 +2152,30 @@ namespace UnifiedRegex
...
                 {
                     // Just a character
-                    codePointToSet = pendingCodePoint;
                     pendingCodePoint = deferredCharNode.cs[0];
                 }
             }
             else if (nextChar == '-')
             {
-                if (pendingRangeStart != INVALID_CODEPOINT || pendingCodePoint == INVALID_CODEPOINT || ECLookahead(1) == ']')
+                if ((!prevWasACharSet && (pendingRangeStart != INVALID_CODEPOINT || pendingCodePoint == INVALID_CODEPOINT)) ||  ECLookahead(1) == ']')
```
Comment (dilijev) [inline lib/Parser/RegexParser.cpp]: >  [](start = 126, length = 1)

nit: extra space

File: lib/Parser/RegexParser.cpp [hunk 6]
```diff
@@ -2147,30 +2152,30 @@ namespace UnifiedRegex
...
                 {
-                    // - is just a char, or end of a range.
+                    // - is just a char, or end of a range. If the previous char of the RegExp was a charset we want to treat it as the beginning of a range.
```
Comment (dilijev) [inline lib/Parser/RegexParser.cpp]: >charset [](start = 101, length = 7)

clarification: when we say charset here do we mean e.g. an escaped character class like `\s`?

**Comment by dilijev** [comment]
>             }

nit: add an extra newline after this closing brace so it's more clear that this if is not logically associated with the following if/else-if cascade

---
Refers to: lib/Parser/RegexParser.cpp:2140 in 47797ff. [](commit_id = 47797fff7077eb7ca8995bb7d6d643a2c4f116a1, deletion_comment = False)

**Comment by dilijev** [comment]
```
>eshost --tags jsvu-web -h chext,ch-master-latest,ch-1.10-latest -is re.js
## Source
re = /^[\s][a\sb][\s--c-f]$/
" -cdef".split('').forEach((c)=>print(re.test('  '+c)))
"./0Ab!".split('').forEach((c)=>print(!re.test('  '+c)))
print(!re.test(' \\ '))

#### ch-1.10-latest, ch-master-latest, jsvu-ch
true
true
true
false
false
true
false
false
false
false
false
true
true

#### jsvu-jsc, jsvu-sm, jsvu-v8
true
true
true
true
true
true
true
true
true
true
true
true
true

#### chext
true
true
true
true
true
true
true
true
true
true
true
true
false
```

File: test/Regex/characterclass_with_range.js (hunk 4 above)
Comment (kfukuda2) [reply test/Regex/characterclass_with_range.js]: Added test cases for these characters

File: lib/Parser/RegexParser.cpp (hunk 5 above)
Comment (kfukuda2) [reply lib/Parser/RegexParser.cpp]: Removed

File: lib/Parser/RegexParser.cpp (hunk 6 above)
Comment (kfukuda2) [reply lib/Parser/RegexParser.cpp]: I should have made it clearer to say escaped character class, the comment has been removed in the latest commit though due to refactoring the logic to not treat it as a range

File: test/Regex/characterclass_with_range.js [hunk 7]
```diff
@@ -0,0 +1,132 @@
...
+                testRegExp('\t', reNonRange, false);
+                testRegExp('\u2028', reNonRange, false);
+                
+                reNonRange = /[\w-]/
+                testRegExp('-', reNonRange, true);
+                testRegExp('g', reNonRange, true);
+                testRegExp('5', reNonRange, true);
+                testRegExp(' ', reNonRange, false);
+                testRegExp('\t', reNonRange, false);
+                testRegExp('\u2028', reNonRange, false);
```
Comment (dilijev) [inline test/Regex/characterclass_with_range.js]: make sure these non-ranges also don't match `\`

File: test/Regex/characterclass_with_range.js [hunk 8]
```diff
@@ -0,0 +1,132 @@
...
+                testRegExp('  ', re, false);
+        }
+    },
+    {
+        name : "Negation character set tests",
+        body : function () 
+        {
+                let reNegationCharSet = /[\D-\s]+/;
+                testRegExp('555686', reNegationCharSet, false);
+                testRegExp('555-686', reNegationCharSet, true);
```
Comment (dilijev) [inline test/Regex/characterclass_with_range.js]: you might use `.match` and ensure that the matched string (`match[0]`) is what you expected.

File: test/Regex/characterclass_with_range.js [hunk 9]
```diff
@@ -0,0 +1,132 @@
+//-------------------------------------------------------------------------------------------------------
+// Copyright (C) Microsoft. All rights reserved.
+// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
+//-------------------------------------------------------------------------------------------------------
+
+WScript.LoadScriptFile("..\\UnitTestFramework\\UnitTestFramework.js");
+
+function testRegExp(str, regexp, expectedResult)
```
Comment (dilijev) [inline test/Regex/characterclass_with_range.js]: for `expectedResult`, instead of a Boolean, you could test with `.match` and have an expected value for `match[0]`

File: test/Regex/characterclass_with_range.js [hunk 10]
```diff
@@ -0,0 +1,132 @@
...
+        {
+            let reUnicode = /^[a-d]$/u;
+            testRegExp("a", reUnicode, true);
+            testRegExp("c", reUnicode, true);
+            testRegExp("d", reUnicode, true);
+            testRegExp("C", reUnicode, false);
+            testRegExp("g", reUnicode, false);
+            testRegExp("\u2028", reUnicode, false);
+            testRegExp("\u2009", reUnicode, false);
+            assert.throws(() => eval("/^[\\s-z]$/u.exec(\"-\")"), SyntaxError, "Expected an error due to character sets not being allowed in ranges when unicode flag is set.", "Character classes not allowed in class ranges");
```
Comment (dilijev) [inline test/Regex/characterclass_with_range.js]: since this is in a function, is it necessary to eval the regex? (Also, if you need to construct a RegExp from a string, you could use the `RegExp` constructor instead of `eval`.)

File: test/Regex/characterclass_with_range.js [hunk 11]
```diff
@@ -0,0 +1,132 @@
...
+        body : function () 
+        {
+                let re = /^[\s][a\sb][\s--c-f]$/;
+                testRegExp('  \\', re, false);
+                testRegExp(' \\ ', re, false);
+                testRegExp('\\  ', re, false);
+                re = /[-][\d\-]/;
+                testRegExp('--', re, true);
+                testRegExp('-9', re, true);
+                testRegExp('  ', re, false);
```
Comment (dilijev) [inline test/Regex/characterclass_with_range.js]: if you want to make sure you're matching exactly 2 characters, and that you match the entire input string, you can make the regex as `/^...$/` but if you're intentionally testing regexes without BOI/EOI assertions, that's fine.

File: test/UnifiedRegex/bugFixRegression.js [hunk 12]
```diff
@@ -501,13 +501,6 @@ exec(/(?:a*)?/, "");
 exec(/(?:a+)?/, "");
 exec(/(?:a||b)?/, "b");
 
-// WOOB1145588
-exec(/[\s-a-c]*/, " -abc");
-exec(/[\s\-a-c]*/, " -abc");
-exec(/[a-\s-b]*/, " -ab");
-exec(/[a\-\s\-b]*/, " -ab");
-exec(/[\s--c-!]*/, " -./0Abc!");
```
Comment (dilijev) [inline test/UnifiedRegex/bugFixRegression.js]: I didn't notice any tests for out-of-order range endpoints like `[c-!]` in the new test. We should preserve the test (but ensure that it now throws an error).

File: test/Regex/characterclass_with_range.js (hunk 10 above)
Comment (kfukuda2) [reply test/Regex/characterclass_with_range.js]: Using the literal regex or regex constructor will throw a SyntaxError when parsing the script.

File: test/UnifiedRegex/bugFixRegression.js (hunk 12 above)
Comment (kfukuda2) [reply test/UnifiedRegex/bugFixRegression.js]: Added the test case to the regressions.

File: test/Regex/characterclass_with_range.js (hunk 11 above)
Comment (kfukuda2) [reply test/Regex/characterclass_with_range.js]: I was intentionally trying to get a mix of BOI/EOI assertions, and I've just committed a change to do a match and verify the match so that should take care of the concern.

File: test/Regex/characterclass_with_range.js (hunk 9 above)
Comment (kfukuda2) [reply test/Regex/characterclass_with_range.js]: changed testRegExp to matchRegExp and it now verifies the matched string.

File: test/Regex/characterclass_with_range.js (hunk 8 above)
Comment (kfukuda2) [reply test/Regex/characterclass_with_range.js]: changed testRegExp to matchRegExp and it now verifies the matched string.

File: test/Regex/characterclass_with_range.js (hunk 7 above)
Comment (kfukuda2) [reply test/Regex/characterclass_with_range.js]: Added tests for this

File: lib/Parser/rterrors.h [hunk 13]
```diff
@@ -366,6 +366,7 @@ RT_ERROR_MSG(JSERR_NoAccessors, 5673, "Invalid property descriptor: accessors no
 RT_ERROR_MSG(JSERR_RegExpInvalidEscape, 5674, "", "Invalid regular expression: invalid escape in unicode pattern", kjstSyntaxError, 0)
 RT_ERROR_MSG(JSERR_RegExpTooManyCapturingGroups, 5675, "", "Regular expression cannot have more than 32,767 capturing groups", kjstRangeError, 0)
 RT_ERROR_MSG(JSERR_ProxyHandlerReturnedFalse, 5676, "Proxy %s handler returned false", "Proxy handler returned false", kjstTypeError, 0)
+RT_ERROR_MSG(JSERR_UnicodeRegExpRangeContainsCharClass, 5677, "", "Character classes not allowed in class ranges", kjstSyntaxError, 0)
```
Comment (dilijev) [inline lib/Parser/rterrors.h]: >Character classes [](start = 67, length = 17)

nit: mention RegExp in the message to make it clear we're talking about regexp and regexp character class ranges and not something to do with JS classes.

Also, this wording raises a question in my mind, does this also throw if you have `/[[acz]-q]/` or `/[[acz]-q]/` (embedded character class within character class).

File: test/Regex/characterclass_with_range.js [hunk 14]
```diff
@@ -0,0 +1,137 @@
...
+    },
+    {
+        name : "Special character tests",
+        body : function () 
+        {
+                let re = /^[\s][a\sb][\s--c-f]$/;
+                matchRegExp('  \\', re, null);
+                matchRegExp(' \\ ', re, null);
+                matchRegExp('\\  ', re, null);
+                re = /[-][\d\-]/;
```
Comment (dilijev) [inline test/Regex/characterclass_with_range.js]: >\- [](start = 28, length = 2)

with escaped hyphen (which is not a char class escape) it might be a good idea to also check it doesn't match `'\\'`

File: lib/Parser/rterrors.h (hunk 13 above)
Comment (dilijev) [reply lib/Parser/rterrors.h]: Never mind about embedded character classes. ECMAScript doesn't support these.
[https://www.regular-expressions.info/charclassintersect.html](https://www.regular-expressions.info/charclassintersect.html) (Java, Ruby)

---
In reply to: [201167325](https://github.com/Microsoft/ChakraCore/pull/5418#discussion_r201167325) [](ancestors = 201167325)

Comment (tcare) [reply lib/Parser/rterrors.h]: Can we be double sure it's not in the spec?

File: lib/Parser/RegexParser.cpp [hunk 15]
```diff
@@ -2147,22 +2153,27 @@ namespace UnifiedRegex
             else if (nextChar == '\\')
             {
                 Node* returnedNode = ClassEscapePass1(&deferredCharNode, &deferredSetNode, previousWasASurrogate);
+                codePointToSet = pendingCodePoint;
 
                 if (returnedNode->tag == Node::MatchSet)
                 {
-                    codePointToSet = pendingCodePoint;
+                    if (unicodeFlagPresent && pendingRangeStart != INVALID_CODEPOINT)
```
Comment (dilijev) [inline lib/Parser/RegexParser.cpp]: >pendingRangeStart != INVALID_CODEPOINT [](start = 46, length = 38)

This logic reads a bit confusingly. I'd combine the pendingRangeStart blocks and check `unicodeFlagPresent` inside. Move `pendingCodePoint = INVALID_CODEPOINT to the beginning of the block (after the check for FAIL)

File: lib/Parser/RegexParser.cpp [hunk 16]
```diff
@@ -2188,9 +2199,23 @@ namespace UnifiedRegex
...
 
-            if (codePointToSet != INVALID_CODEPOINT)
+            if (codePointToSet != INVALID_CODEPOINT || prevprevWasACharSetAndPartOfRange)
             {
-                if (pendingRangeStart != INVALID_CODEPOINT)
+                if (unicodeFlagPresent && prevprevWasACharSetAndPartOfRange)
+                {
+                    Fail(JSERR_UnicodeRegExpRangeContainsCharClass);
+                }
+                else if (prevprevWasACharSetAndPartOfRange)
```
Comment (dilijev) [inline lib/Parser/RegexParser.cpp]: > else if (prevprevWasACharSetAndPartOfRange) [](start = 15, length = 44)

here's another opportunity to factor these branches more clearly

File: lib/Parser/RegexParser.cpp [hunk 17]
```diff
@@ -2147,22 +2153,27 @@ namespace UnifiedRegex
...
             {
                 Node* returnedNode = ClassEscapePass1(&deferredCharNode, &deferredSetNode, previousWasASurrogate);
+                codePointToSet = pendingCodePoint;
 
                 if (returnedNode->tag == Node::MatchSet)
                 {
-                    codePointToSet = pendingCodePoint;
+                    if (unicodeFlagPresent && pendingRangeStart != INVALID_CODEPOINT)
+                    {
+                        Fail(JSERR_UnicodeRegExpRangeContainsCharClass);
```
Comment (dilijev) [inline lib/Parser/RegexParser.cpp]: >Fail(JSERR_UnicodeRegExpRangeContainsCharClass); [](start = 24, length = 48)

as another comment mentioned, this is pass1 so usually syntax error would have happened in pass 0. Since pass 0 doesn't have information about the unicode flag, this is the only place we can check. Just add a comment explaining this.

File: lib/Parser/RegexParser.cpp [hunk 18]
```diff
@@ -2188,9 +2199,23 @@ namespace UnifiedRegex
                 pendingCodePoint = NextChar();
             }
 
-            if (codePointToSet != INVALID_CODEPOINT)
+            if (codePointToSet != INVALID_CODEPOINT || prevprevWasACharSetAndPartOfRange)
             {
-                if (pendingRangeStart != INVALID_CODEPOINT)
+                if (unicodeFlagPresent && prevprevWasACharSetAndPartOfRange)
+                {
+                    Fail(JSERR_UnicodeRegExpRangeContainsCharClass);
```
Comment (dilijev) [inline lib/Parser/RegexParser.cpp]: I believe this is redundant to the logic above. We would have already thrown SyntaxError before prevprevWasACharSetAndPartOfRange could be set to true.

File: lib/Parser/RegexParser.cpp [hunk 19]
```diff
@@ -2199,6 +2224,7 @@ namespace UnifiedRegex
                         Assert(!unicodeFlagPresent);
                         Fail(JSERR_RegExpBadRange);
```
Comment (dilijev) [inline lib/Parser/RegexParser.cpp]: I'm concerned about this comment. Mostly, I'm not sure if it's accurate to the current logic, and I wonder if at some point this codepath stopped checking the right thing, or just stopped agreeing with the comment, or whether the comment is correct and needs more explaining. I don't think your change affects the truth of this comment, but it's worth examining a bit.

We want to throw an error for an ordinary out of range, which this codepath does.

We also need to handle the case of surrogate code points, if applicable. The assert below the comment producing no runtime failures -- assuming you ran RegexTestCollateral on a debug build -- indicates that it is not possible to reach this point if /u is specified. We know we can't get here with /u and prevprevWasACharSetAndPartOfRange because we would have thrown SyntaxError earlier. As the assert at the beginning of the function `Assert(containsSurrogates ? unicodeFlagPresent : true);` if the input string contains surrogates -- which is already known on the codepath where this function is called (since containsSurrogates is a template parameter) -- then we must have /u as well.

According to the Assert, getting here means it's not possible for all of these checks to be true when `!unicodeFlagPresent`

```cpp
            if (codePointToSet != INVALID_CODEPOINT)
            {
                if (pendingRangeStart != INVALID_CODEPOINT)
                {
                    if (pendingRangeStart > pendingCodePoint)
```

Comment (kfukuda2) [reply lib/Parser/RegexParser.cpp]: In pass0 it will Fail if there is an invalid non-surrogate range, so I assume the comment is because in pass1,
`pendingRangeStart > pendingCodePoint ` 
is true only when there is a range containing surrogates

File: lib/Parser/RegexParser.cpp [hunk 20]
```diff
@@ -2201,18 +2204,21 @@ namespace UnifiedRegex
...
+                        Fail(JSERR_UnicodeRegExpRangeContainsCharClass);
+                    }
+
                     if (pendingCodePoint != INVALID_CODEPOINT)
                     {
                         codePointSet.Set(ctAllocator, pendingCodePoint);
                     }
 
-                    codePointSet.Set(ctAllocator, '-');
+                    codePointSet.Set(ctAllocator, '-'); //Add '-' to set because a range was detected but turned out to be a union of character set with '-' and another atom.
```
Comment (dilijev) [inline lib/Parser/RegexParser.cpp]: Thanks for adding the comment here.

File: lib/Parser/rterrors.h (hunk 13 above)
Comment (dilijev) [reply lib/Parser/rterrors.h]: "Not supported in the other engines" is a pretty strong piece of evidence. In any case it's out of scope of this change.

**Comment by dilijev** [comment]
Woo!
