### PR TITLE
Share more code/ideas between JsBuiltIns and Intl

### LINKED ISSUE #5643: JsBuiltIns show as `funcName` rather than `Constructor.prototype.funcName` in stack traces
```js
try {
  [1, 2, 3].forEach(() => { throw new Error(); });
} catch (e) {
  print(e.stack);
}
```

This shows a line for `forEach (native code)` with jsbuiltins enabled, while it shows `Array.prototype.forEach (native code)` with jsbuiltins disabled. Same for .filter.

### LINKED ISSUE #5644: JsBuiltIn internal functions are shown in stack traces
```js
[1, 2, 3].flatMap(() => { throw new Error() })
```

This shows a line for `FlattenArrayIntoMapped (native code)`, which should be excluded from the stack trace.

### PR DESCRIPTION
**Pull request by jackhorton**
Fixes #5644 
Fixes #5643 
Fixes an unlogged issue where all JsBuiltIns were constructable by default.

This mainly merged a lot of the code between tagPublicLibraryFunction, registerFunction, and registerChakraLibraryFunction. However, there are a number of smaller updates too:
1. Stopped creating a new ScriptFunction on each JsBuiltIn registration. As far as I can tell, the only reason this existed before was to get a ScriptFunction without any framedisplay/environment, but since that can be set manually, its cheaper to just set it on the existing ScriptFunction.
1. Intl functions no longer have to duplicate their name in the tagPublicLibraryCode argument and in script. I have edited a few Intl functions to confirm it works -- not sure if its worth it to go through and make all of the functions anonymous now. I also wanted to investigate changing JavascriptLibrary::InitializeFunction to not set the name attribute for these anonymous jsbuiltin functions since the name will always be overridden, but I am not sure if its possible.
1. function length is now set using default parameters rather than manually/after the fact. Not sure if I like this better or worse than having the function macro list the length and have it set it explicitly. We could theoretically do the same optimization in InitializeFunction to avoid the extra property set.
1. JsBuiltIns now uses a shared/projected enum for function registration like Intl.
1. Ran into an error when using default parameters for functions marked explicitly as "use strict," and I found the error message misleading, so I changed it to be the same as V8's which I found clearer.
1. CheckArrayAndGetLen never hit its error case and reported a slightly worse-looking runtime/accidental error as a result when this == null

Still need to run this through test262 to make sure there are no regressions.

### CODE REVIEW

**Comment by jackhorton** [comment]
Also cc @rhuanjl as the writer of so many of these builtins :)

File: lib/Parser/perrors.h [hunk 1]
```diff
@@ -88,7 +88,7 @@ LSC_ERROR_MSG( 1077, ERRDestructNotInit, "Destructuring declarations cannot have
 LSC_ERROR_MSG(1079, ERRInvalidNewTarget, "Invalid use of the 'new.target' keyword")
 LSC_ERROR_MSG(1080, ERRForInNoInitAllowed, "for-in loop head declarations cannot have an initializer")
 LSC_ERROR_MSG(1081, ERRForOfNoInitAllowed, "for-of loop head declarations cannot have an initializer")
-LSC_ERROR_MSG(1082, ERRNonSimpleParamListInStrictMode, "Cannot apply strict mode on functions with non-simple parameter list")
```
[the remark this answers is not in the document]
Comment (jackhorton) [reply lib/Parser/perrors.h]: yeah, I had only tested the array folder before putting it up last night because I was tired.

File: lib/Runtime/Library/StringCacheList.h [hunk 2]
```diff
@@ -8,6 +8,7 @@ STRING(Quotes, _u("\"\""))
 STRING(Whack, _u("/"))
 STRING(CommaDisplay, _u(","))
 STRING(CommaSpaceDisplay, _u(", "))
+STRING(Dot, _u("."))
```
Comment (MSLaguana) [inline lib/Runtime/Library/StringCacheList.h]: What uses this? I don't see any other references in this PR

Comment (jackhorton) [reply lib/Runtime/Library/StringCacheList.h]: its used when building up the full display string as `library->GetDotString()`

**Comment by rhuanjl** [comment]
Thanks for tagging me.

This looks like some very nice cleanup - also nice to see the stack trace issues fixed.

File: lib/Runtime/Library/EngineInterfaceObject.cpp [hunk 3]
```diff
@@ -313,47 +313,125 @@ namespace Js
...
+        AssertOrFailFast((args.Info.Count == 3 || args.Info.Count == 4) && ScriptFunction::Is(args.Values[1]) && JavascriptString::Is(args.Values[2]));
+
+        ScriptFunction *func = ScriptFunction::UnsafeFromVar(args[1]);
+        JavascriptString *methodName = JavascriptString::UnsafeFromVar(args[2]);
+
+        bool isConstructor = true;
+        if (args.Info.Count == 4)
+        {
+            AssertOrFailFast(JavascriptBoolean::Is(args.Values[3]));
+            isConstructor = JavascriptBoolean::UnsafeFromVar(args.Values[3])->GetValue();
```
Comment (Penguinwizzard) [inline lib/Runtime/Library/EngineInterfaceObject.cpp]: Why not just use ::FromVar and drop the AssertOrFailFast ::Is checks in this function in general?

Comment (jackhorton) [reply lib/Runtime/Library/EngineInterfaceObject.cpp]: I think I got into a pattern with it in Intl as a modification of what was already there and then didn't think about it more. Combined with `operator[]` for ArgumentsReader, we could probably get rid of all of the arguments-related asserts... may make that a future PR?

**Comment by dilijev** [comment]
FWIW LGTM
