### PR TITLE
Assertion when scanning invalid numeric literal after multi-unit characters

### LINKED ISSUE #5571: ChakraCore crashes with assertion failure in Scan.h:495
Debug build of ChakraCore received SIGILL with an ASSERTION FAILURE.

```
$ ./build.sh --debug
$ ./out/Debug/ch test.js
ASSERTION 14607: (/data/ChakraCore/lib/Parser/Scan.h, line 495) static_cast<charcount_t>(m_pchMinTok - m_pchBase) >= m_cMinTokMultiUnits
 Failure: (static_cast<charcount_t>(m_pchMinTok - m_pchBase) >= m_cMinTokMultiUnits)
$ cat test.js
eval('\u20091a')
```

OS: Ubuntu 18.04 LTS
Arch: x86_64

### PR DESCRIPTION
**Pull request by boingoing**
We can throw an error when scanning numeric literals. If the numeric literal is preceeded by multi-unit whitespace (eaten as part of the numeric literal token) we will count up those multi-units into Scanner::m_cMultiUnits. However, if the numeric literal ends up throwing, we should reset the multi-unit counter in scanner to whatever it was before we started to scan the whitespace and numeric literal token. If we don't reset the multi-unit counter, the character offset for the error object will be wrong and debug build will assert.

Fixes #5571

### CODE REVIEW

File: lib/Parser/Scan.cpp [hunk 1]
```diff
@@ -587,7 +587,7 @@ IdentPtr Scanner<EncodingPolicy>::PidOfIdentiferAt(EncodedCharPtr p, EncodedChar
 }
 
 template <typename EncodingPolicy>
-typename Scanner<EncodingPolicy>::EncodedCharPtr Scanner<EncodingPolicy>::FScanNumber(EncodedCharPtr p, double *pdbl, bool& likelyInt)
+typename Scanner<EncodingPolicy>::EncodedCharPtr Scanner<EncodingPolicy>::FScanNumber(EncodedCharPtr p, double *pdbl, bool& likelyInt, size_t saveMultiUnits)
```
Comment (MSLaguana) [inline lib/Parser/Scan.cpp]: Could you please rename this to `savedMultiUnits`? On my first reading I assumed it was a Boolean (GitHub code review interface didn't help by pushing the argument out of view)

Comment (boingoing) [reply lib/Parser/Scan.cpp]: Sure, that makes sense. We are not overly consistent with the naming of these save variables, anyway.

File: test/Scanner/rlexe.xml [hunk 2]
```diff
@@ -6,6 +6,13 @@
       <compile-flags>-args summary -endargs</compile-flags>
     </default>
   </test>
+  <test>
+    <default>
+      <files>NumericLiteralSuffixRequireICU.js</files>
+      <compile-flags>-args summary -endargs</compile-flags>
+      <tags>exclude_noicu</tags>
```
Comment (jackhorton) [inline test/Scanner/rlexe.xml]: maybe prefer to name this RequireIntl? We do still support winglob, and the test works with winglob. I think this could also be achieved with `if (WScript.Platform.INTL_LIBRARY === "winglob" || WScript.Platform.INTL_LIBRARY === "icu")`

Comment (boingoing) [reply test/Scanner/rlexe.xml]: This is what I was looking for, thanks for the heads-up.
