### PR TITLE
Use Unicode Windows API to print ChakraCore version (fix #3178)

### LINKED ISSUE #3178: ch.exe -v doesn't work correctly if path contains non-ascii characters
`PrintChakraCoreVersion()` in `bin/ch/ch.cpp` uses ANSI version of Windows APIs, like `GetModuleFileNameA`, `GetFileVersionInfoA`, etc., so if the current path contains non-ascii characters and the current code page doesn't support these characters, `GetFileVersionInfoA` fails even though the file is there.

unicodetest

Maybe related to #2712.

### PR DESCRIPTION
**Pull request by xiaoyinl**
This PR adds a new WIN32-only function GetChakraDllNameW() to ChakraRtInterface.cpp, which returns wide string "ChakraCore.dll". In ch.cpp, the function PrintChakraCoreVersion() uses GetChakraDllNameW() and Unicode Windows APIs to obtain the file version of ChakraCore.dll, so that it will work even if the pathname contains non-ASCII characters.

Fixes #3178.

unicodetest

### CODE REVIEW

File: bin/ch/ChakraRtInterface.cpp [hunk 1]
```diff
@@ -23,10 +24,16 @@ ChakraRTInterface::ArgInfo* ChakraRTInterface::m_argInfo = nullptr;
 TestHooks ChakraRTInterface::m_testHooks = { 0 };
 JsAPIHooks ChakraRTInterface::m_jsApiHooks = { 0 };
 
-LPCSTR GetChakraDllName()
+LPCSTR GetChakraDllName()
+{
+	return chakraDllName;
+}
```
Comment (agarwal-sandeep) [inline bin/ch/ChakraRtInterface.cpp]: There s no usage of this now. Remove it.

**Comment by xiaoyinl** [comment]
@dotnet-bot test Ubuntu static_ubuntu_linux_test please

File: bin/ch/ChakraRtInterface.cpp (hunk 1 above)
Comment (xiaoyinl) [reply bin/ch/ChakraRtInterface.cpp]: @agarwal-sandeep Done. Thanks!

**Comment by dilijev** [comment]
Testing internally.
