### PR TITLE
fix incorrect argument passed to itow for json syntax error

### LINKED ISSUE #5975: JSON.parse() crashes on strings of 10M characters
Looks like JSON.parse() may have a problem when reporting a syntax error for strings of 10M or more characters. For example, if json is a long string followed by a comma (invalid character), the following script run in ch.exe should report syntax error, but instead the process seems to crash and nothing is logged after JSON.parse():

```javascript
let desiredLength = 10 * 1000 * 1000;
//desiredLength -= 1;
const json = `"${'a'.repeat(desiredLength - 3)}",`; // "aaa...aaa",
console.log(json.length);
JSON.parse(json);
console.log('finished');
```
Output:

> 10000000

However, uncommenting line 2 and decreasing `desiredLength` by 1 produces expected result:

> 9999999
> SyntaxError: JSON.parse Error: Unexpected input at position:9999999
>    at Global code (C:\Temp\cc_windows_1_11_6\x86_release\script.js:8:1)

Does JSON.parse use some internal buffer of 10M characters so that exceeding this size causes it to crash?

ChakraCore: 1.11.6 x86 release
OS: Windows 10 17763.316

### PR DESCRIPTION
**Pull request by MikeHolman**
Fixes #5975

### CODE REVIEW

File: test/JSON/jsonerrorbuffer.js [hunk 1]
```diff
@@ -0,0 +1,11 @@
+//-------------------------------------------------------------------------------------------------------
+// Copyright (C) Microsoft. All rights reserved.
+// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
+//-------------------------------------------------------------------------------------------------------
+
+let desiredLength = 10 * 1000 * 1000;
+//desiredLength -= 1;
+const json = `"${'a'.repeat(desiredLength - 3)}",`; // "aaa...aaa",
+print(json.length);
+JSON.parse(json);
```
Comment (akroshg) [inline test/JSON/jsonerrorbuffer.js]: Instead of printing the whole error - could we just try/catch and print('pass') on that? you could avoid baseline... also I am not sure as the baseline contains the hard path.

Comment (MikeHolman) [reply test/JSON/jsonerrorbuffer.js]: good point
