### PR TITLE
Fix patterns in rest formal parameters.

### LINKED ISSUE #5550: Differing behavior with other engines for nested destructuring in array rest
The unit test in destructuring_bugs.js, "Rest as pattern at param with arguments/eval at function body" yields differing values from other engines. The eshost output is attached below:

```
#### ch-1.10.1
4
5
3
3
4
5
3
1,2

#### sm
undefined
undefined
3
3
undefined
undefined
3
1,2

#### node
undefined
undefined
3
3
undefined
undefined
3
[ 1, 2 ]
```

Generated by:
```
(function ([a, b], c, ...{rest1, rest2}) {
    eval("");
    console.log(rest1);
    console.log(rest2);
    console.log(c);
    console.log(arguments[1]);
})([1, 2], 3, {rest1:4, rest2:5});

(function ([a, b], c, ...{rest1, rest2}) {
    (function () {
        console.log(rest1);
        console.log(rest2);
        console.log(a+b);
    })();
    eval("");
    console.log(arguments[0]);
})([1, 2], 3, {rest1:4, rest2:5});
```

### LINKED ISSUE #5551: Destructuring unrecognized when nested in Array Rest
Currently, the parser does not recognize the destructuring object/array as an array rest parameter and as such, everything in the object/array remains uninitialized. However, the specific case of having object destructuring works syntactically (see issue #5550). For example:
```
function foo(a, ...{...rest}) {
    console.log(JSON.stringify(rest));
}            
foo(1, 2, 3);
```
results in rest being empty, when it should be {0:2, 1:3}.

The parser currently treats the `{...rest}` as a var declaration instead of a destructuring assignment in `ParseFncFormals()`. 

Note: When fixing this, also check for the effect of eval("").

@tcare

### PR DESCRIPTION
**Pull request by zenparsing**
Currently, when a pattern is present as a rest parameter the parser incorrectly interprets the pattern as a non-rest parameter. This change allows patterns to appear in the AST for rest parameters.

Fixes #5550
Fixes #5551

### CODE REVIEW

File: lib/Parser/Parse.cpp [hunk 1]
```diff
@@ -7004,6 +7010,12 @@ void Parser::ParseFncFormals(ParseNodeFnc * pnodeFnc, ParseNodeFnc * pnodeParent
 
             if (flags & fFncOneArg)
             {
+                if (seenRestParameter)
```
Comment (akroshg) [inline lib/Parser/Parse.cpp]: moving this down - will it change the line number/column number of the error when that is reported?

Comment (akroshg) [reply lib/Parser/Parse.cpp]: or this part of the for loop? 

---
In reply to: [279027586](https://github.com/Microsoft/ChakraCore/pull/6111#discussion_r279027586) [](ancestors = 279027586)

Comment (zenparsing) [reply lib/Parser/Parse.cpp]: Yes, this change results in the wrong column number being reported.

Great catch!

File: lib/Runtime/ByteCode/ByteCodeEmitter.cpp [hunk 2]
```diff
@@ -1592,8 +1592,6 @@ void ByteCodeGenerator::EmitScopeObjectInit(FuncInfo *funcInfo)
     Js::PropertyIdArray *propIds = funcInfo->GetParsedFunctionBody()->AllocatePropertyIdArrayForFormals(extraAlloc, slotCount, Js::ActivationObjectEx::ExtraSlotCount());
 
     ParseNodeFnc *pnodeFnc = funcInfo->root;
-    ParseNode *pnode;
-    Symbol *sym;
```
Comment (zenparsing) [inline lib/Runtime/ByteCode/ByteCodeEmitter.cpp]: These declarations were moved closer to their point-of-use in order to avoid variable name shadowing.

File: lib/Runtime/ByteCode/ByteCodeEmitter.cpp [hunk 3]
```diff
@@ -2709,8 +2716,7 @@ void ByteCodeGenerator::EmitDefaultArgs(FuncInfo *funcInfo, ParseNodeFnc *pnodeF
         m_writer.RecordCrossFrameEntryExitRecord(/* isEnterBlock = */ true);
         m_writer.Br(Js::OpCode::TryCatch, catchLabel);
 
-        // Rest cannot have a default argument, so we ignore it.
-        MapFormalsWithoutRest(pnodeFnc, emitDefaultArg);
+        MapFormals(pnodeFnc, emitDefaultArg);
```
Comment (zenparsing) [inline lib/Runtime/ByteCode/ByteCodeEmitter.cpp]: When the rest param is a pattern, we need to run `emitDefaultArg` on it in order to emit destructuring code.

When the rest param is not a pattern, there is no change to the existing bytecode output; `emitDefaultArg` will perform

- `sym->SetNeedDeclaration(false)`, which was happening below
- `EmitPropStore`, which is a no-op for this case
