### PR TITLE
Remove NvContext pointers in StackTrace64

### LINKED ISSUE #5314: RtlVirtualUnwind last parameter is optional and not needed here.
https://github.com/Microsoft/ChakraCore/blob/99f04016d044360b637a654a274c167d026cb020/lib/Common/Core/FaultInjection.cpp#L153

### PR DESCRIPTION
**Pull request by msdimitrov**
Resolves #5314

### CODE REVIEW

File: lib/Common/Core/FaultInjection.cpp [hunk 1]
```diff
@@ -150,7 +149,7 @@ namespace Js
             else
             {
                 RtlVirtualUnwind(UNW_FLAG_NHANDLER, ImageBase, Context.Rip, RuntimeFunction,
-                    &Context, &HandlerData, &EstablisherFrame, &NvContext);
+                    &Context, &HandlerData, &EstablisherFrame, NULL);
```
Comment (digitalinfinity) [inline lib/Common/Core/FaultInjection.cpp]: Nitpicky but can you add a comment to the parameter indicating what the NULL is for- something like:
`NULL /* ContextPointers */`

**Comment by digitalinfinity** [comment]
@msdimitrov thank you for the change! @leirocks can you review this change too please?

**Comment by dilijev** [comment]
Marked as `External Contributor` as a reminder that a Chakra team member needs to adopt, test, and merge this change.
